### ISSUE TITLE
♥️ This is sweet, thank you

### ISSUE THREAD

**Issue by joelpittet** [cweagans/composer-patches#102]
<img src="https://www.evernote.com/shard/s710/sh/8865bc73-5b0f-4b0a-b601-3fa009b6aa7f/57cd705bd73ec95f/res/5c12c8e4-2f05-4aed-ba5b-5dfaa874dfef/skitch.png">

This was so cool!  Just wanted to give you some props!

**Comment by cweagans** [comment]
:)
