### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by pprossi** [cweagans/composer-patches#110]
Hi,

if i try to apply a Patch under Windows Git Bash i get this error.

I've played a bit arround and found line 346 in Patches.php:
$filename = uniqid("/tmp/") . ".patch";

if i change it to:
$filename = uniqid(sys_get_temp_dir()) . ".patch";

It seems to work for me... may be others also?

**Comment by cweagans** [comment]
Dup of https://github.com/cweagans/composer-patches/pull/96

**Comment by pprossi** [comment]
Hi.
May be it could help to get the patched version by composer require?
composer require cweagans/composer-patches shows on 1.6.
