### ISSUE TITLE
Version 1.6.0 is not compatible with PHP5.3

### ISSUE THREAD

**Issue by mskarupianski** [cweagans/composer-patches#111]
This was already fixed in the master branch https://github.com/cweagans/composer-patches/commit/fab4aa322d0cad0b1aaa521c86e6463f449f8dad#diff-cf7534e34ca749ac0a88fd7f5dbe0869 but people on the 1.x Version (with PHP5.3) kill their composer without that commit.

**Comment by cweagans** [comment]
Sorry for breaking it again. Frankly, PHP 5.3 support is not high on my priority list. It's been unsupported for 2.5 years. If you'd like to submit another PR for this, I'll merge it and do what I can to make sure it doesn't break again.

However, keep in mind that this will not be the policy for 2.x. PHP 5.5 or 5.6 will be required.

**Comment by cweagans** [comment]
Related: https://seld.be/notes/php-versions-stats-2016-2-edition

**Comment by patkar** [comment]
@cweagans If you don't want to support PHP 5.3 anymore in 1.x you can still raise the minimum version to 5.5/5.6 in your composer.json and tag a new release. All PHP 5.3 users (wtf!) simply don't get updates anymore, but can still use the latest tag with 5.3 as minimum.

I would even recommend, go PHP 7.1 as min for 2.x :smirk:

**Comment by cweagans** [comment]
2.0.0 will require 5.4-ish at a minimum (I know we at least require traits and short array syntax -- there's probably more). Only 5.6+ is tested. 1.x is best effort.
