### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by OnkelTem** [cweagans/composer-patches#114]
I added everything to the `composer.json` file but it doesn't seem to do anything.
So what steps should I undertake to get/see it do something?

I tried deleting `vendor/` directory, reinstalling everything with `composer install -v`, I watched the log but there's simply nothing about any patching.

**Comment by OnkelTem** [comment]
Probably I was using old version. At least now when I selected "1.6." I see this:
```
  - Installing drush/drush (8.1.10) Loading from cache
Patching is disabled. Skipping.
```
So why does it disabled while I have it in my composer.json?

**Comment by OnkelTem** [comment]
Crap... unbelievable. Sorry, seems like I see the typo. Let me check it...

**Comment by cweagans** [comment]
Glad you got it working!
