### ISSUE TITLE
Patching is disabled. Skipping. When no patches are defined.

### ISSUE THREAD

**Issue by Andrei-Colesnic** [cweagans/composer-patches#119]
When there are no patches defined in the composer.json the message `Patching is disabled. Skipping.` gets printed which is a little bit confusing and is not exactly true. The root of the problem is in the conditions used by `isPatchingEnabled` function.

**Comment by cweagans** [comment]
If you want patches to be applied, you can manually opt in. But if the plugin is installed and there are no patches defined, patching is disabled. If you're just concerned about the noise in the output, that has been resolved in another PR already. If this doesn't help, let me know what you'd like to see happen here and we'll try to come to a resolution.

**Comment by Andrei-Colesnic** [comment]
Thank you for the response. My concern was regarding the noise and that it can be confusing. If this issue was already resolved in another PR - I am glad.

**Comment by cweagans** [comment]
The noise issue has been fixed in 1.6.1.
