### ISSUE TITLE
EntityPopulator.fillcolumns() using method_exists calling private method

### ISSUE THREAD

**Issue by cap-dev** [cweagans/composer-patches#125]
I have come across an issue where fillColumns is using 'method_exists' on line 202. This gives rise to issues with a call to a callable but private method in one of our Doctrine objects. Would it be possible to change this call to 'is_callable' instead, as the private method is not then called and causing the process to fail?

**Comment by cweagans** [comment]
...wrong project?

**Comment by cap-dev** [comment]
Apologies. You are correct. Been posted here by mistake.
