### ISSUE TITLE
Removing projects has no fallbacks

### ISSUE THREAD

**Issue by ao2** [cweagans/composer-patches#126]
Hi,

when a new patch is detected in the main composer.json, composer-patches removes the target project and reinstall it to apply the patches cleanly, e.g.:
```
...
Removing package drupal/syntaxhighlighter so that it can be re-installed and re-patched.
...
```

However it happened to me that the removed project was the one I was working on, and I lost some of the work I did.

Is there a way to prevent that? Maybe composer-patches could make a backup of the project before removing it? Or refuse to remove it if there is a `.git` directory in it?

Maybe this is more of a generic composer issue?

Thanks,
   Antonio

**Comment by cweagans** [comment]
I'm not opposed to making this configurable in 2.0.0. Added to the roadmap (#93)

**Comment by cweagans** [comment]
`main` doesn't do this automatically anymore. It's an explicit action.

I would still recommend not working on things in this way though. `composer` lets you define things like so:

```json
{
[...]
  "repositories": [
    {
      "type": "path",
      "url": "../../../../"
    }
  ],
  "require": {
    "cweagans/composer-patches": "*@dev",
    "cweagans/composer-patches-testrepo": "~1.0"
  },
[...]
}
```

When you do a `composer install`, it will symlink your local repo into place. That way, if the dep is uninstalled, you don't lose your work. It just deletes the symlink.
