### ISSUE TITLE
Composer install fails with contrib project and bad patch

### ISSUE THREAD

**Issue by steveoliver** [cweagans/composer-patches#127]
I have a Commerce 2.x project from `composer create-project drupalcommerce/project-base mystore --stability dev` ([install docs](http://docs.drupalcommerce.org/v2/getting-started/install.html)) that is requiring one project (`commerce_shipping` currently, but any one of the commerce contrib projects produced similar errors), and with one failing-to-apply patch to commerce.

The problem is that with a commerce + contrib + bad patch composer.json file, I *can* `composer update` but I cannot afterwards `composer install`.  IF I either a.) remove the contrib requirement, or b.) fix the patch, I *can* `composer install` after a `composer update`.

Here is the ["bad patch" composer.json](https://gist.github.com/steveoliver/3dadc04ceac1b5260d92cfea8f52871b#file-composer-bad-patch-json-L90) and ["good patch" composer.json](https://gist.github.com/steveoliver/3dadc04ceac1b5260d92cfea8f52871b#file-composer-good-patch-json-L90).

Steps to reproduce:

1. `composer update && composer install` with bad-patch composer.json. Should fail with error:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - drupal/commerce_price 2.x-dev requires drupal/commerce == 2.9999999.9999999.9999999-dev -> no matching package found.
>     - drupal/commerce_price 2.x-dev requires drupal/commerce == 2.9999999.9999999.9999999-dev -> no matching package found.
>     - Installation request for drupal/commerce_price 2.x-dev -> satisfiable by drupal/commerce_price[2.x-dev].
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
2. `composer update && composer install` with the good-patch composer.json.  Should succeed.
3. `composer update && composer install` with the bad-patch composer.json, but `commerce_shipping` require removed.

I've seen patches not apply without composer failing.  **I don't expect dependency errors to arise from composer patches that don't apply**.  _I'd expect to see them regardless of patch failures_.

Am I the only one, or can others reproduce this?

**Comment by steveoliver** [comment]
If we do want composer to fail with bad patches, I think the solution to this issue is to report the actual error--bad patches--instead of a version constraint message.

**Comment by mglaman** [comment]
Can reproduce. If `composer update drupal/project` has patch and fails, next `composer install` freaks out with `2.9999999.9999999.9999999-dev ` constraint.

**Comment by mglaman** [comment]
Generally running the update again fixes it (assuming patch failure was a fluke.(

**Comment by cweagans** [comment]
Added to the 2.0.0 roadmap (#93)

**Comment by cweagans** [comment]
I think this was probably a composer bug. Things have changed significantly since then, so I'm going to assume this is no longer an issue. Please let me know if that's not the case.
