### ISSUE TITLE
Patch up to a specific version

### ISSUE THREAD

**Issue by mougrim** [cweagans/composer-patches#130]
It isn't first request about this feature, for example #75, but the main argument against is "This is not possible right now, but I'm not sure why it's necessary at all.", but I have good case for it.

So I have a library [https://github.com/mougrim/phpunit-soft-mocks](https://github.com/mougrim/phpunit-soft-mocks) that allows intercepting functions and methods in phpunit. That library needs to apply some patches to phpunit, but this patches is different for diffferent phpunit versions. Better solution, I think, in this case to provide patches file for this package, like this:

```json
"extra": {
    "patch-packages": {
        "mougrim/phpunit-soft-mocks": "patches.json"
    }
}
```

`patches.json` should be in `vendor/mougrim/phpunit-soft-mocks/patches.json` (or in `patches.json` if current package is `mougrim/phpunit-soft-mocks`) with next content:

```json
{
  "phpunit/phpunit": {
    "^4.0.0": {
      "phpunit run file": "patches/phpunit4.x/phpunit_phpunit.patch",
      "Add ability to set custom filename rewrite callbacks #1": "patches/phpunit4.x/phpunit_add_ability_to_set_custom_filename_rewrite_callbacks_1.patch",
      "Add ability to set custom filename rewrite callbacks #2": "patches/phpunit4.x/phpunit_add_ability_to_set_custom_filename_rewrite_callbacks_2.patch"
    },
    "^5.0.0": {
      "phpunit run file": "patches/phpunit5.x/phpunit_phpunit.patch",
      "Add ability to set custom filename rewrite callbacks #1": "patches/phpunit5.x/phpunit_add_ability_to_set_custom_filename_rewrite_callbacks_1.patch",
      "Add ability to set custom filename rewrite callbacks #2": "patches/phpunit5.x/phpunit_add_ability_to_set_custom_filename_rewrite_callbacks_2.patch"
    }
  },
  "phpunit/php-code-coverage": {
    "^2.1.0": {
      "Add ability to set custom filename rewrite callbacks": "patches/phpunit4.x/php-code-coverage_add_ability_to_set_custom_filename_rewrite_callbacks.patch"
    },
    "^4.0.4": {
      "Add ability to set custom filename rewrite callbacks": "patches/phpunit5.x/php-code-coverage_add_ability_to_set_custom_filename_rewrite_callbacks.patch"
    }
  }
}
```

It provides simple way to install patches list for any version.

**Comment by cweagans** [comment]
Sorry, but I'm not willing to add this to the core package. For 99% of projects, it's really not necessary. Sure, there are some cases where there might be an argument for it, but the majority of places where this package is used is in a project that consumes libraries that are always at a known version.

That said, 2.x will expose a plugin capability for patch resolution. That is, you'd be able to provide your own logic around what patch should be applied given the context of the project. In this case, you could define a VersionSpecificPatchResolver or something and look for patches in a different way than the core package does it.

**Comment by mougrim** [comment]
If somebody interesting in this issue, there is fork [vaimo/composer-patches](https://github.com/vaimo/composer-patches), which allow provide different patches for different package's versions.
