### ISSUE TITLE
Drupal core update - update documentation

### ISSUE THREAD

**Issue by alioso** [cweagans/composer-patches#131]
Looks like drupal/drupal in order to update core does not work - should be drupal/core ?

**Comment by cweagans** [comment]
I'm not sure what you mean. You should be able to apply a patch to any package. drupal/drupal vs drupal/core shouldn't make a difference. Can you please share what you're seeing?

**Comment by alioso** [comment]
Hey, thanks for the quick answer. It happened after I updated to 8.3
drupal/drupal just would not do anything. no output. Just nothing. changing to drupal/core made it work. Not sure what it is, just sharing my findings. might something with my config, not sure.

**Comment by sk33lz** [comment]
It turns out we have `"name": "drupal/drupal",` set in our composer.json and not a custom name for our install profile. That appears to be why we couldn't apply patches to package `drupal/drupal` with this plugin. Switching to package `drupal/core` for patches has resolved this issue. Thanks!
