### ISSUE TITLE
Introduce a configurable order of stripping leading components

### ISSUE THREAD

**Issue by mkalkbrenner** [cweagans/composer-patches#137]
As described in https://github.com/cweagans/composer-patches/pull/133 the hardcoded order of p1, p0, p2 is the worst strategy for drupal core patches.
In https://github.com/cweagans/composer-patches/pull/136 it is explained that p4 is missing for Magento root patches.
I suggest to turn the hardcoded order of fallbacks into a free configurable one.
Maybe something like
"strip-leading-components": "p2,p1,p0,p4"
in the extras section.

**Comment by cweagans** [comment]
Definitely not gonna happen in 1.x, but you'll be able to set the patch depth on a per-patch basis in 2.0.0.

**Comment by cweagans** [comment]
(see #93 for what will be included in 2.0.0)
