### ISSUE TITLE
Install patches from local file

### ISSUE THREAD

**Issue by joum** [cweagans/composer-patches#146]
I created a `.patch` file for a Drupal module that I have been using, and I would like to have it versioned with my codebase, but not publicly online. That being said, I would like to have the file stored locally and use a similar syntax to what is already possible, but referring a local file instead of an URL. Is this possible?

**Comment by cweagans** [comment]
Yes, this is possible. Instead of a URL, you can specify a path to your patch file relative to the directory that your composer.json is in. For instance, if the patch file is in the same directory as your composer.json, the URL would be either 'patchname.patch' or './patchname.patch'.

**Comment by cweagans** [comment]
(For reference, the plugin just uses file_get_contents() under the hood, so anything you can pass as the first argument will be valid for this plugin)

**Comment by joum** [comment]
@cweagans Thank you for your reply. Is it possible that some folder permissions interfere with this process? I created a `patches` directory next to my `composer.json` file and then I referenced a `.patch` file like you mentioned above and composer terminated with a file not found exception.

I tried debugging your module for a bit and found out it was breaking in the `getAndApplyPatch` function. The `eventDispatcher`triggered for every patch I had, but then the `file_exists` never got the real filename, and then advanced to the download option, which in turn failed because it isn't a valid URI.

 I eventually found another way to solve my problem, but if it's helpful I could open an issue with more details and the error messages.

**Comment by cweagans** [comment]
If you can post a composer.json that reproduces the problem here, I can take a look.

**Comment by milkovsky** [comment]
Change your patch extension to `txt`. Example:

```
"extra": {
        "patches": {
            "drupal/views_infinite_scroll": {
                "Integrate with Ajax Assets Plus" : "patches/foo-bar.patch.txt"
            }
        }
    }
```

**Comment by marklabrecque** [comment]
Adding .txt is what fixed it for me. Thanks @milkovsky !

**Comment by uberhacker** [comment]
The `.txt` extension trick didn't work for me.  Why would an extension matter?

**Comment by uberhacker** [comment]
@cweagans: Can this issue be reopened?  The current version is not accepting local patches named `.patch` or `.txt`.

**Comment by marklabrecque** [comment]
Still works fine for me. Please ensure your path is setup correctly to reference from the project root for composer to find the file in question

**Comment by uberhacker** [comment]
I don't get a file not found message.  It just doesn't apply.  FWIW, this is a Drupal core patch.  I still haven't received an answer to my question about the `.txt` extension.  That doesn't make any sense.

**Comment by uberhacker** [comment]
To reproduce this, try creating a core patch and install it from a local file instead of a remote url.

**Comment by marklabrecque** [comment]
Can you paste your code into a comment here and we might be able to track down the issue?

**Comment by loopy3025** [comment]
Fixing the path in the patch file worked for me. In my case, I was trying to patch a Drupal project. When I created the patch file, it used the path relative to where I was in the project. When applying patches, composer in a Drupal project uses a different path.

As created:
```
diff --git a/docroot/core/lib/Drupal/Core/Config/StorageComparer.php b/docroot/core/lib/Drupal/Core/Config/StorageComparer.php
index 5110111aa..5e3f4fbad 100644
--- a/docroot/core/lib/Drupal/Core/Config/StorageComparer.php
+++ b/docroot/core/lib/Drupal/Core/Config/StorageComparer.php
```

Changes needed for composer to apply:
```
diff --git web/core/lib/Drupal/Core/Config/StorageComparer.php web/core/lib/Drupal/Core/Config/StorageComparer.php
index 5110111aa..5e3f4fbad 100644
--- web/core/lib/Drupal/Core/Config/StorageComparer.php
+++ web/core/lib/Drupal/Core/Config/StorageComparer.php
```
