### ISSUE TITLE
Patch fails on Windows PowerShell

### ISSUE THREAD

**Issue by Pasqualle** [cweagans/composer-patches#147]
> Could not apply patch! Skipping. The error was: Cannot apply patch ...

This is what I got when I try patches from "Windows PowerShell" or from "Command Prompt"

It works correctly from "Git Bash"

Does someone knows what could be the reason?

**Comment by cweagans** [comment]
PowerShell and cmd are more than likely broken. The vast majority of users of this plugin are using bash on various platforms. I'm not opposed to patches that make the plugin work better in Windows shells, but it's extremely unlikely that someone else will be working on this if you choose not to.

**Comment by Pasqualle** [comment]
I am now using "git bash" exclusively for Drupal development..

**Comment by Mtwango** [comment]
Had the same exact problem today. 
By running _composer update -v_ I've found out, that I didn't have in PATH path to directory with patch.exe (in my setup Program Files\Git\usr\bin).
Leaving this comment here if somebody in future has the same problem, so you know, that it isn't problem with composer-patches
