### ISSUE TITLE
Add a switch to completely disable patching

### ISSUE THREAD

**Issue by cweagans** [cweagans/composer-patches#18]
This is a dependency of https://github.com/cweagans/composer-patches/issues/16 if we move forward there, but it may be useful on its own.

**Comment by ericduran** [comment]
Yea, :+1: this is a good idea.

**Comment by generalconsensus** [comment]
Bump, my composer update is failing because of this

**Comment by cweagans** [comment]
You shouldn't run 'composer update' as part of a ci process, FWIW. I haven't gotten to this yet, but I would merge a PR if you made one.

**Comment by generalconsensus** [comment]
@cweagans What is best practice to be exact?

**Comment by cweagans** [comment]
@generalconsensus 

1. Commit `composer.lock` to the repo
2. When a developer wants to update a composer package, run `composer update your/package` (which will respect the version constraints that are in `composer.json`. Note that you may need to include the `--with-dependencies` flag to allow composer to update a package's dependencies if necessary)
3. In your CI process, when you're producing your build artifacts, you only ever want to run `composer install`, which installs the *exact* versions that are specified in `composer.lock`, rather than any package that happens to match the constraints in `composer.json`. This way, you have a reproducible build.
4. Your `composer.lock` is always considered the canonical place that lists your packages. If it's not in `composer.lock`, it doesn't exist. Note that Composer will complain loudly when your `composer.json` and your `composer.lock` don't match up properly.

That aside, if you install the patches plugin before any other package (i.e. list it first in your `composer.json` `require{}` section), the plugin will detect that you're updating a package that has a patch applied, and will actually *remove* the package from your vendor directory first, and then re-install the package.

**Comment by phenaproxima** [comment]
This functionality is needed to solve the problem in #36, which is a potential security hazard if there is no user interaction. How can we go about implementing this? Can plugins define switches? Should we add it to the extra section in composer.json?

**Comment by cweagans** [comment]
I think something in the extra section in `composer.json` would be okay. I'm thinking something like:

```
"extra": {
    "patches-functionality": true|false
  }
```

or something like that. Feel free to bikeshed the name of the key, but the idea is that there should just be a simple true/false switch to turn on/off the patches functionality.

**Comment by phenaproxima** [comment]
I'd go with ```enable-patching``` or ```enable-patches```. Unless I'm missing something, this seems like a reasonably easy thing to implement...

**Comment by cweagans** [comment]
It should be pretty easy, yeah. Either of those keys sounds good to me.

**Comment by phenaproxima** [comment]
Added this to #36.

**Comment by cweagans** [comment]
Fixed in #36

**Comment by aaronbauman** [comment]
Commenting on this ancient thread because I searched and couldn't find other matches.

> You shouldn't run 'composer update' as part of a ci process, FWIW. 

My use case is a scheduled job that checks for package updates, and creates a PR if it finds them.
It's now failing because of "uncommitted changes" 

Should I start a new thread?
