### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by dergachev** [cweagans/composer-patches#180]
Hi Cameron! We're using this library for a big corporate client, and they're asking to us to list all the license terms for each open-source library we're using. This is the only one that doesn't seem to have a license. Could you clarify with a LICENSE file or something in the readme what you expect?

Thanks!

**Comment by cweagans** [comment]
https://github.com/cweagans/composer-patches/blob/master/composer.json#L4 specifies BSD-2-Clause, but I should probably add a license file to the repo.

**Comment by cweagans** [comment]
Actually, BSD-3-Clause might be more appropriate here.

**Comment by cweagans** [comment]
https://github.com/cweagans/composer-patches/commit/a3366c7d745408833e7ef5e82d66a6986699731d for master

https://github.com/cweagans/composer-patches/commit/9504fbdc3285ca6dfbc0e81e37489ae9c1e67532 for 1.x

**Comment by dergachev** [comment]
You're awesome!
