### ISSUE TITLE
Windows fixing "hack" actually breaks FreeBSD (and Unix)

### ISSUE THREAD

**Issue by Techwolf12** [cweagans/composer-patches#182]
Hi!

The hack in this file: https://github.com/cweagans/composer-patches/blob/3466175168856f843ca3c0c05b3563633d226526/src/Patches.php#L426

Breaks support for BSD patch (commonly found under FreeBSD servers or some Mac devices, in my case version: patch 2.0-12u11 FreeBSD)
`--no-backup-if-mismatch` is the flag that breaks this. 

My suggestion is a check for runtime (if running on windows or using gnupatch, add the flag, else leave it out).
I will check if I can create a pull request within a month. Feel free to do this earlier.

**Comment by drupol** [comment]
Using FreeBSD and having the same issue.

Removing the faulty flag fixed the issue.

**Comment by criley** [comment]
Any word on this getting fixed? I have a major project that I was going to convert to Drupal 8 however this really puts a damper on it.

**Comment by kimpepper** [comment]
I came across this issue using Alpine Linux. The fix was to explicitly install the patch package which bumps up the version from 1.x to 2.x.

**Comment by drupol** [comment]
@kimpepper could you describe how you did to fix this ? I'm unable to get it working here on FreeBSD.

Thanks!

**Comment by kimpepper** [comment]
Just `apk add -u patch` on alpine. This bumped the default version of the `patch` package.

**Comment by drupol** [comment]
@cweagans The issue with FreeBSD is still there, do we really need the `--no-backup-if-mismatch` it's been months that we are asking to remove this option and use `--posix`.

Should we be really forced to fork this project ???

**Comment by tmilker** [comment]
I think I determined the real fix for this issue that will make everyone happy(haven't tested on MacOS though):  composer-patches doesn't pass the -t or --batch command like it probably should.  I don't think anyone will ever want to manually type a filename(or have composer-patches stall, waiting for one during an automated deploy) and patch should just fail if it needs one.  A nice side effect is that on FreeBSD(tested on 11.3), if you specify -t it will ignore the invalid --no-backup-if-mismatch argument completely!

@cweagans Please modify composer-patches to add the -t command line argument to patch.  I'd love to remove my ugly, ugly hack of passing patch through my own patch script that adds it.

**Comment by kentr** [comment]
For anyone still facing this, try `vaimo/composer-patches`.  It's working for me on FreeBSD w/ `patch 2.0-12u11`.

Make sure that you don't have this line in your `composer.json`, because if `cweagans/composer-patches` gets installed as a sub-dependency it may still abort the composer operation before `vaimo/composer-patches` has a chance to run:

```json
"composer-exit-on-patch-failure": true
```

**Comment by cweagans** [comment]
PRs welcome. FreeBSD is not a particularly high priority for me, but if `-t` fixes freebsd _and_ doesn't break more common envs, i'm not opposed.

**Comment by williamrdickson** [comment]
Same problem occurs on MacOS Catalina (10.15.4). Curiously, it only happens with some patches. These all succeed:

>             "drupal/ctools": {
>                 "2475595 - Views exposed filters missing autosubmit options": "https://www.drupal.org/files/issues/2475595-ctools-autocomplete-fix-47.patch",
>                 "2785499 - Entity Bundle Condition Plugin does not work in all situations": "https://www.drupal.org/files/issues/2019-03-01/ctools_fix_condition_plugin_entity_bundle-2785499-12.patch",
>                 "2898191 - Add a condition plugin for domain name": "https://www.drupal.org/files/issues/2019-03-03/ctools-domain_name_condition_plugin-2898191-11-D8.patch",
>                 "2960195 - Help is missing on module file": "https://www.drupal.org/files/issues/2019-02-27/ctools-Help_is_missing_on_module_file-2960195-4-D8.patch",
>                 "3001713 - CSS style properties for blocks": "https://www.drupal.org/files/issues/2018-09-23/3001713-css_styles_for_blocks-5.patch"
>             }

...while these all fail:

>             "drupal/ckeditor_a11ychecker": {
>                 "3125175 - Drupal 9 readiness": "https://www.drupal.org/files/issues/2020-04-06/3125175-2.patch"
>             },
>             "drupal/codesnippet": {
>                 "3108118 - Drupal 9 compatibility": "https://www.drupal.org/files/issues/2020-02-04/3108118-4.patch"
>             },
>             "drupal/editor_advanced_link": {
>                 "3105317 - Drupal 9 compatibility": "https://www.drupal.org/files/issues/2020-01-09/3105317-2-drupal9-compatibility.patch"
>             },

They all succeed when applied manually via "git apply".

vaimo/composer-patches doesn't fare any better.

**Comment by DicksB** [comment]
> Same problem occurs on MacOS Catalina (10.15.4). 

Please disregard. The problem was me not understanding that the tarball X.y-dev files on these modules were not up-to-date with their corresponding branches.

**Comment by cweagans** [comment]
`main` now has explicit support for BSD Patch. Please take a look at `src/Patcher/BsdPatchPatcher.php` and let me know if it's doing the right thing.
