### ISSUE TITLE
Unable to "revert" patch when a composer-patches declaration is removed

### ISSUE THREAD

**Issue by markfullmer** [cweagans/composer-patches#201]
## Scenario
A. A patch is needed on the site, and applied via the composer-patches approach. 👍 
B. The patch no longer is necessary, and the composer-patches declaration is removed from `composer.json` 👍 
C. After running `composer update`, the patched file(s) are still patched. 👎 

Assuming that I'm not missing something above, this seems like a significant problem. Our team ran across it in switching between branches of a codebase, one of which had the composer-patches declaration, and one which didn't. 

I can imagine the difficulty in implementation, since composer-patches has no way of tracking whether a patch had been applied in the past and thus should be reverted (though potentially this *could* be achieved via composer.lock information??), and separately how the actual "revert" would happen (simplest way, I think, would be to re-install the package that had been patched).

If this is not something on the 2.x roadmap, is the recommended workaround for individuals to manually remove any packages that would have been patched before running a subsequent `composer update`?

## Desired capability
As a developer, I want to be able to run the standard `composer update` and `composer install` commands and have any patches that have been removed from the `composer-patches` configuration actually be removed from the corresponding packages, so that the configuration matches the codebase.

**Comment by teohhanhui** [comment]
Isn't it easy enough to just remove the relevant directories under `vendor`?

**Comment by cweagans** [comment]
> If this is not something on the 2.x roadmap, is the recommended workaround for individuals to manually remove any packages that would have been patched before running a subsequent composer update?

This is not something I've had on my radar, and the workaround would be to manually delete the package. The next `composer install` would cause it to be reinstalled sans patches. I don't plan to work on this in the near future, as it's a pretty complex scenario that's easily sidestepped, so I'm going to close this for now.

If you end up digging into this and finding a way for it to work based on the data in composer.json and composer.lock in a variety of scenarios (e.g. `composer install` when there is no lock file, `composer install` when there _is_ a lock file, `composer install` when there is a lock file and packages exist on disk, and `composer update` are the main ones, I think), I'm open to making it happen. I just don't have the bandwidth to dive into this.

**Comment by OXRudy** [comment]
@markfullmer You are right about this.
Of course, applying a patch MUST alter the composer.lock file in some way so you can revert it by removing the patch declaration and running ```composer install```.

I understand the "remove the vendor/project manually" workaround because its trivial in an environnment you control.

When you are using any CI/CD ou any automated workflow, this is not an option.

This is the only reason why I won't use your project for now.
Nevertheless, this is a great tool and I love the way to use it. Keep up the good work.

**Comment by KaseyMK** [comment]
Just wanted to note that "remove the vendor directory" requires a fair amount of work when your repo doesn't include the vendor directory and you're working with a server with read-only files.

I have to remove the module from our composer.json, push the code to force an install without the module, then require the module in the composer.json again and push the code again. When my branch gets merged, a couple more commits on master (and then again on production) will be similarly required to square everything away.

I totally appreciate a lack of time and a need to set priorities - and I have no idea how to implement this idea - but I wanted to describe a scenario that would argue for the work being worthwhile. Thanks!

**Comment by liquidcms** [comment]
Pretty old thread but this just started happening on a couple projects. I think it may have gotten triggered by upgrading composer to 2.x and then finding out it didnt work; so i reverted back to 1.x. After that, when i remove patch from composer.json, when i next run composer install it does know to remove the module to reinstall and patch; but then it goes ahead and patches.. even though patch has been removed from composer.json.
