### ISSUE TITLE
Magento 2 patch level

### ISSUE THREAD

**Issue by danielmartinezd** [cweagans/composer-patches#206]
I created a patch to solve a bug form Magento https://github.com/magento/magento2/issues/5872

Patch:
---
 site/vendor/magento/module-media-storage/Model/File/Storage/Request.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/site/vendor/magento/module-media-storage/Model/File/Storage/Request.php b/site/vendor/magento/module-media-storage/Model/File/Storage/Request.php
index 6f7e77ff0..a2a02fd97 100644
--- a/site/vendor/magento/module-media-storage/Model/File/Storage/Request.php
+++ b/site/vendor/magento/module-media-storage/Model/File/Storage/Request.php
@@ -21,7 +21,7 @@ class Request
      */
     public function __construct(HttpRequest $request)
     {
-        $this->pathInfo = str_replace('..', '', ltrim($request->getPathInfo(), '/'));
+        $this->pathInfo = str_replace('..', '', ltrim($request->getPathInfo(), '/media/'));
     }

     /**
--

When applying the patches
    patches/XXX.diff (Bug #1234: Something is wrong)
   Could not apply patch! Skipping. The error was: Cannot apply patch patches/XXX.diff

**Comment by cweagans** [comment]
I don't have any plans for this right now. In 2.x, you'll be able to define your own patch depth on a per-patch basis. See #93 for progress and how/where to help.
