### ISSUE TITLE
ConfigurablePlugin trait is not found

### ISSUE THREAD

**Issue by deviantintegral** [cweagans/composer-patches#207]
As of 13f91ed: `Fatal error: Trait 'cweagans\Composer\Plugin\ConfigurablePlugin' not found`

See [this build log](https://circleci.com/gh/Lullabot/media_mpx/83) for details.

For now, switching back to the last tag is an easy workaround. I'm not even sure why we were using master in the first place!

**Comment by cweagans** [comment]
Yeah, you definitely shouldn't use master. :) I'm a little surprised that everything has worked up to this point, tbh.

Thanks for the heads up about the build failure. I'll get that fixed.

**Comment by cweagans** [comment]
I believe this is resolved in the latest master.
