### ISSUE TITLE
Feature request: allow setting options to be passed to patcher tool(s)

### ISSUE THREAD

**Issue by karol-haltenberger** [cweagans/composer-patches#208]
Use case:
Suppose Drupal core resides inside a "web" folder relative to the composer.json file. (web/core/...)
Paths in core patch files tend to start with **a/core/...**
git apply can be configured to use a directory prefix (--directory=web), but there is no way to set this with composer-patches

I understand there is a 2.0 version on the way (is there?) with some configuration options.
It would be nice to have the ability to specify all sorts of options to be passed to the patch tools on a per patch / per tool basis.

example:
```yaml
{
    "patches": {
        "drupal/core": {
            "Patch without options": "patch-without-options.patch",
            "Patch with options": {
              "patch-with-options",
              "options": {"--option1", "--option2=value"}
           },
           "Patch with options per tool": {
             "patch-with-options-per-tool.patch",
            "options" {
               "--verbose", #default for all tools
               "git" : {"--directory=web", "-p3"},
               "hg" :{"--foo", "--bar"}
            }
           }
        }
    }
}
```

**Comment by cweagans** [comment]
I've made a note to make sure the `-v` and `--verbose` flags to a composer command also make command output verbose in `main`. Probably not going to add per-patcher flags though -- if you want custom behavior, patchers can be defined by third party plugins (Documentation coming soon :tm:)
