### ISSUE TITLE
Reconsider to fail the build by default when patches cannot be applied

### ISSUE THREAD

**Issue by pfrenssen** [cweagans/composer-patches#209]
In https://github.com/cweagans/composer-patches/issues/40 the functionality was added to optionally allow a build to fail if a patch cannot be applied by setting the `composer-exit-on-patch-failure` option.

At the time it was decided that this option would not be made default to preserve backwards compatibility, and that in an upcoming 2.x release it would be made the default.

I would like to propose to make this the default anyway. It looks like a 2.x version is going to be a long time off, and in the meantime we keep getting hit by this. It's impossible to imagine the number of hours that were lost by developers looking into failed tests because a patch didn't apply any more, and it was forgotten to set this option. I have personally been hit by this more times than I would like to admit.

I think it depends on your viewpoint:  this could be considered as a feature that breaks backwards compatibility, or it could be seen as a bugfix for previously unintended behaviour, with a flag to preserve backwards compatibility.

From my point of view, if I define a patch in my composer.json file, I am declaring that my project depends on this patch, I don't consider it to be optional.

An alternative would be to make a 2.0 release in the near future, but that seems excessive for just this feature alone.

**Comment by cweagans** [comment]
This is squarely 2.0.0 material as it's a breaking change in behavior. While I agree it's the _right_ behavior, I'm not willing to shove it in to 1.x and hope for the best. It's already in 2.x, and the best way to get it out the door is to help me with #93 (will be updated within an hour or so with 2.0.0 hitlist - working through issue triage right now).
