### ISSUE TITLE
Patch is not being applied on drupal/core automatically from contrib

### ISSUE THREAD

**Issue by mxr576** [cweagans/composer-patches#219]
Automatic patching is enabled in Drupal's composer.json.

If I run `composer require drupal/apigee_edge` then it installs some required patches but it does not install drupal/core patches until I do not run `composer update none`.

https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/composer.json#L49

Is it an error or some kind of design?

**Comment by mxr576** [comment]
I have the latest stable, 1.6.5 installed.

**Comment by cweagans** [comment]
Probably a bug.

**Comment by eelkeblok** [comment]
I am actually seeing the same thing, although I found patches from my dependency are installed on a second composer install. Might well be that composer update none triggers basically the same thing. It seems that composer patches does not look for new patches in downloaded dependencies, only for "existing" patches (whatever that may mean, exactly).

**Comment by cweagans** [comment]
`main` doesn't do this anymore. There is a command to re-resolve all patches and update the lock file (`composer patches-relock`) and another to re-patch everything (`composer patches-repatch`).
