### ISSUE TITLE
Update outdated examples in README.md

### ISSUE THREAD

**Issue by mxr576** [cweagans/composer-patches#222]
The README.md file contains some outdated/incomplete examples about how composer patches should be used.

- [ ] (Minor) Very old Drupal dependency is referenced.
- [ ] Examples should either depend on drupal/core or install Drupal with drupal-composer/drupal-project. Installing Drupal with drupal/drupal is the worst possible way. See: https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies#note-warning
- [ ] Examples should patch drupal/core instead of drupal/drupal.
- [ ] At least one example should describe patchLevel and why drupal/core patch level should be set to -p2. See: https://github.com/drupal-composer/drupal-project/pull/410

**Comment by frederickjh** [comment]
@mxr576 I would suggest submitting a pull request for these making each task a separate commit.

**Comment by cweagans** [comment]
I've made a note to capture these things when updating docs for 2.x.
