### ISSUE TITLE
Error handling: Provide option to roll back to previous patched requirement version

### ISSUE THREAD

**Issue by JPustkuchen** [cweagans/composer-patches#223]
Hi and thank you very much for this great module! It's such a big helper! Wonderful development.

Just an idea / feature request, if it's technically possible:

Wouldn't it perhaps make sense to add another error handling option to roll back to the previous installed version + patch if a patch could not be applied?

That may happen if a newer version is no more compatible with a patch (needs reroll). Currently the patching fails and you have to quickly react and find out why it fails and what the previous module version has been. It would be helpful to show an error but keep the installation running by rolling back.

Would you like to discuss that? What do you think?

**Comment by cweagans** [comment]
I think that technically, that's doable. However, I'm not sure that it makes sense. In many cases, upgrading to a new release of a package actually mitigates the need for the patch (or at least changes what patch is needed - upstream may have incorporated the patch into mainline, or the patch may no longer apply for whatever reason).

I'm also not sure why you'd need to quickly react - these kinds of changes should only be done in development environments where you have some time to figure out what went wrong and how to resolve it.

**Comment by JPustkuchen** [comment]
Hi Cameron,

yes your absolutely right. Perhaps I gave you a wrong impression of my idea.

> In many cases, upgrading to a new release of a package actually mitigates the need for the patch (or at least changes what patch is needed - upstream may have incorporated the patch into mainline, or the patch may no longer apply for whatever reason).

Exactly!
And my idea was now instead of breaking things with that update with failing patch to restore the correct behaviour. Even in a dev environment that seems a good way to me because this keeps things running and gives you more time to react and understand the reasons.

A patch that was applied before but can no more be applied may have two reasons:
- The patch has been commited into the recent version and is no more needed => We have to ensure this and remove it from the patch list
- The patch needs a reroll => We have to decide if we keep the older patched version or (reroll and) exchange the patch

Both things may need some time and you'd be happy to not have a probably broken environment. So it will give you time to solve things cleanly without manually changing the required version to keep things running. And you only have to touch the composer.json when you actively fix things, not to make the site running in the meantime.

Additionally it may happen that you first have to do some research for the patch reasons etc. in more complex environments because it can not be commented in composer.json.

So from my point of view there are more reasons for a warning plus rollback to previous version than to run with unpatched, probably broken newer version.

What do you think?

**Comment by cweagans** [comment]
I'm probably not going to handle this in the core plugin, but it would be possible to write a plugin that extends this one to add the custom behavior you're looking for.
