### ISSUE TITLE
Add a way to just update the patches section of composer.lock

### ISSUE THREAD

**Issue by cweagans** [cweagans/composer-patches#23]
This should be done after https://github.com/cweagans/composer-patches/issues/12

Need a way to update the patches we're tracking in composer.lock, but not mess with lib versions or anything else. Possibly something like `composer update --patches`.

**Comment by simesy** [comment]
This might be helpful https://github.com/composer/composer/issues/4714

**Comment by ericduran** [comment]
Came here to open this same issue, Need a way to update patches section only.

**Comment by hanoii** [comment]
Also interested in this, is there a workaround? I guess do nothing and still do composer install, that will add the patch, or is there another better way of coping with adding a patch without updating things?

**Comment by bradjones1** [comment]
I believe you should be able to update the patch and then `composer update --lock` which should just update the lockfile...

**Comment by hanoii** [comment]
That did it yes, interesting, I guess then this is a not-issue?

**Comment by cweagans** [comment]
This still needs done. `composer update --lock` only updates the hash in the lock file. The list of patches applied to a given package still needs to be updated, I think.

**Comment by hanoii** [comment]
I tried it and also updated the patch part of the lock file

**Comment by hanoii** [comment]
On my case it was a new patch added

**Comment by axel-rutz** [comment]
There is also `composer update nothing`. Dunno if this behaves different.

**Comment by joelpittet** [comment]
@axel-rutz https://github.com/composer/getcomposer.org/issues/92#issuecomment-174937826 It looks to be an undocumented equivalent of `composer update --lock`

**Comment by Incognito** [comment]
I would find this feature useful.

**Comment by kweij** [comment]
I agree with @cweagans that it would be nice to have a way to (re)apply (all) patches and update the lock file.

I'm sorry @bradjones1, but running `composer update --lock` does not seem to update `patches_applied` part of the lockfile.

**Comment by kweij** [comment]
I was sooo wrong. Sorry @bradjones1, you're totally right
