### ISSUE TITLE
Not possible to patch composer.json of a dependency

### ISSUE THREAD

**Issue by claudiu-cristea** [cweagans/composer-patches#233]
My use case is that I want to apply a patch to a Drupal module `composer.json`. Specifically, I want to add an `"autoload"` section. But after running the mai project composer, I see that the module autoloading addition is not in effect.

My guess is that the packages are parsed before `cweagans/composer-patches` is acting. So, when the autoload files are generated, at the end of the process, is still using the initial package definitions. I didn't tests if this is true also when adding a new composer dependency via a patch.

I have no idea on the compose internals but isn't it possible to reread the package definitions after the patches were applied?

EDIT: Or do that only if a `composer.json` file has been patched?

**Comment by cweagans** [comment]
This is not possible, unfortunately. `composer` doesn't care about any dependency's `composer.json` -- Packagist reads that data and then serves JSON metadata, which the `composer` CLI then consumes. Unfortunately, there isn't really a good way around this right now if you're looking at it strictly from a patch application standpoint. By the time a patch can be applied, it's simply too late.

The good news is that you can put that `autoload` addition in your root composer.json -- I don't think Composer will complain about that, and it should work as intended.

**Comment by cweagans** [comment]
I've documented this limitation (and others) here: https://docs.cweagans.net/composer-patches/troubleshooting/non-patchable-targets/#changes-to-composerjson (primarily for 2.x).
