### ISSUE TITLE
Drupal core patches apply incorrectly if they only add new files

### ISSUE THREAD

**Issue by deviantintegral** [cweagans/composer-patches#234]
The problem is caused by three factors.

1. Patches that only add new files, like [this responsive image migration patch](https://www.drupal.org/files/issues/2018-08-17/drupal-responsive_image_migration-2993367-2.patch).
2. Drupal core is special, because the base of the composer project is the "core" directory, but all the patches are against git which is one directory higher. When composer-patches tries to apply the patch, `-p1` works because it's only adding new files, even though `-p2` is the correct one to apply. 3. There's an undocumented `patch-level` config, but since the config setting is global, if we change it could break other other patches that only add new files.

One workaround is to reroll patches to have the updated prefix. For the plugin, I think we should consider making the patch-level config be per patch instead of global.

**Comment by mlncn** [comment]
This needs to be fixed or at the very least documented better.  I've spent hours trying to figure out what was happening and this issue was not easy to find.

**Comment by deviantintegral** [comment]
We ended up going with a forking model to avoid edge cases like this entirely. If you're interested, I wrote up our process over at https://www.lullabot.com/articles/patch-less-composer-workflow-drupal-using-forks.

**Comment by john-herreno-ds** [comment]
For current 1.x, [patchLevel](https://github.com/cweagans/composer-patches/tree/1.x#allowing-to-force-the-patch-level--px) should help with patches for drupal/core.

Also, see #178 , #203

**Comment by cweagans** [comment]
`main` is now very flexible wrt patch depth. You can define it in a number of ways:

* Per-patch in the patch definition
* (coming soon) Per-package in your composer.json
* Per-package in `Util::getDefaultPackagePatchDepth()` (this is global for all composer-patches users -- just trying to have good defaults for ecosystems with different workflows like Drupal)
* Global default as a fallback (which defaults to `-p1`).
