### ISSUE TITLE
missing header for unified diff at line

### ISSUE THREAD

**Issue by AgaRengma** [cweagans/composer-patches#235]
On windows 7 (32 bit) machine with latest Git, Composer, Php 5.6 and GnuWin (latest) working on a Drupal opensocial project (latest v)

Getting this error .....
 - Installing composer/semver (1.4.2): Downloading (100%)
 Extracting archiveNo patches found for composer/semver.
Patches already gathered. Skipping
  - Installing drupal-composer/drupal-scaffold (2.4.0): Downloading (100%)
 Extracting archiveNo patches found for drupal-composer/drupal-scaffold.
Patches already gathered. Skipping
AND
missing header for unified diff at line 797969 of patch
can't find file to patch at input line 797969
Perhaps you used the wrong -p or --strip option?
File to patch:
Skip this patch? [y]
Skipping patch.
missing header for unified diff at line 797973 of patch
can't find file to patch at input line 797973
Perhaps you used the wrong -p or --strip option?
File to patch:
Skip this patch? [y]
Skipping patch.
missing header for unified diff at line 797977 of patch
can't fi^CTerminate batch job (Y/N)?

Error continues infinitely unless stop the job with Ctrl+C (above error log is a truncated version of a huge file)

**Comment by phonkala** [comment]
Exactly same problem/error here. Win10 64bit, latest Git & Composer & GnuWin32 + PHP 7.1.11 & Drupal 7.59.

**Comment by christophe-dlb** [comment]
lifesaving tip! Heaps of thanks!

**Comment by cweagans** [comment]
I have no idea what was happening here. `main` has changed significantly since then though, so please let me know if you have similar issues now.
