### ISSUE TITLE
Drupal core patch revert doesn't work?

### ISSUE THREAD

**Issue by nicoschi** [cweagans/composer-patches#236]
Hi there, 
in a Drupal installation after 

1. the deletion of patch lines regarding a contrib module in composer.json
2. the execution of composer update drupal/contrib_module

the module is correctly unpatched. 

This actions doesn't work with patches of drupal/core. 

I tested it with "preferred-install": "source" too, but with no luck. 

I'm doing something wrong? Are these the right actions to unpatch?

**Comment by cweagans** [comment]
I've made a note to document and test the process of unpatching a dependency in 2.x.
