### ISSUE TITLE
patches-dev?

### ISSUE THREAD

**Issue by weitzman** [cweagans/composer-patches#237]
Like require-dev and autoload-dev, can there be a patches-dev?

**Comment by cweagans** [comment]
Sounds good to me. This is a lot more straightforward in the master branch (eventual 2.0.0 release) -- https://github.com/cweagans/composer-patches/tree/master/src/Resolvers is where that would need to happen.

**Comment by waynetheisinger** [comment]
👍

**Comment by mikeohara-blz** [comment]
I'd love to see this also. My use case is Drupal core where I want to patch in theme suggestions for views, but would not want or need that in production.

**Comment by tyler36** [comment]
Would like to see this. 

I've patched a PHPUnit extension package. I don't need PHPunit install on the PROD server so the abibilty to `patch-dev` would be really useful.

**Comment by cweagans** [comment]
I've made a note to consider this for 2.x. I'm not 100% sold on this though -- it might be better to just unconditionally define the patches, and then if e.g. `drush` is installed, it'll be patched. If not, it won't be patched.
