### ISSUE TITLE
module is trying to create /PATCHES.txt - permission denied

### ISSUE THREAD

**Issue by beargroup-jay** [cweagans/composer-patches#238]
We have a project (Magento 2 running on Docksal local env) with a patch where we have the patch results committed to the repository. This means that subsequent composer actions show a message about the patch failing to apply which is fine and expected. 
However, problem is that it tries writing out to /PATCHES.txt in the root directory and doesn't have permissions. If I create that file and give my user write access, then the composer action completes fine.
```
$ fin exec composer update amasty/module-improved-layered-navigation-page
    1/11:	http://packagist.org/p/provider-
.. snip ..
    11/11:	http://packagist.org/p/provi
    Finished: success: 11, skipped: 0, failure: 0, total: 11
Gathering patches from patch file.
Removing package magento/product-enterprise-edition so that it can be re-installed and re-patched.
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:	https://repo.magento.com/archives/magento/product-enterprise-edition/magento-product-enterprise-edition-2.2.5.0.zip
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Package operations: 1 install, 0 updates, 0 removals
Gathering patches from patch file.
Gathering patches for dependencies. This might take a minute.
  - Applying patches for magento/product-enterprise-edition
    patches/correct_ga_analytics.diff (Fix Google analytics lost ecommerce data)
   Could not apply patch! Skipping. The error was: Cannot apply patch patches/correct_ga_analytics.diff

  [ErrorException]
  file_put_contents(/PATCHES.txt): failed to open stream: Permission denied
```

**Comment by cweagans** [comment]
That's pretty strange. I don't have a lot of insight into Docksal and/or Fin, so I'm not sure how I can reproduce this to fix it, but my guess is that it's doing something funky with the paths for Composer packages. If you have specific steps to reproduce, I'm happy to take a look.

**Comment by beargroup-jay** [comment]
Docksal manages docker images with a web stack, I believe it defaults to Debian with Apache etc. Shouldn't be anything special with its composer package but I'll try to dig out a bit more info.

**Comment by beargroup-jay** [comment]
Thanks @sudma ! and sorry for the delay, hadn't had a good chance to test until now, but that's exactly what the issue was. The patch "package" was against the Magento meta-package instead of the specific module that was being patched. Closing the issue out.
