### ISSUE TITLE
Dependencies added in a patch applied by composer are not installed

### ISSUE THREAD

**Issue by mlncn** [cweagans/composer-patches#239]
Here's a fun one!

1.  Add requirements in a patch ([like this one](https://www.drupal.org/project/config_sync/issues/3006103#comment-12820530)).
2.  Add that patch to your project, as usual: `"extra": { "patches": { "drupal/config_sync": { "Enable full reset (revert) of extension-provided configuration": "https://www.drupal.org/files/issues/2018-10-18/config_sync-full-reset-3006103-9.patch"  } }`
3.  Run composer update (or `composer update --lock` followed by `composer install`; i ran into errors with just `composer update` the first time that may or may not be related)
4.  The requirements added in that patch will not be installed.

Expected?  Not expected but just have to live with it anyway?

**Comment by cweagans** [comment]
Just kinda have to live with it, unfortunately. That's just how Composer works. `composer` doesn't really care about the `composer.json` that's on your local disk - that data is parsed and presented somewhere else before the package is even downloaded. One thing you _could_ do is use the wikimedia merge plugin to include your updated composer.json file, and then it would be like requiring those extra dependencies in your root composer.json.

You could also add those requirements to your root composer.json manually until the patch lands.

Sorry there's not a better answer at this point!

**Comment by mlncn** [comment]
Thanks-- yup, took the latter approach but wanted to know the bitter truth for sure!
