### ISSUE TITLE
Add --ignore-whitespace option when patching

### ISSUE THREAD

**Issue by rodrigoaguilera** [cweagans/composer-patches#244]
I found a case where the plugin fails to patch a file generated with git diff

The git project is https://www.drupal.org/project/nexus
And I attach the patch 

[test-whitespace.txt](https://github.com/cweagans/composer-patches/files/2729357/test-whitespace.txt)

After some digging I discovered that is a whitespace problem and that adding --ignore-whitespace to the patch command makes the patch to be applied.

My temporary solution was to generate the patch with diff instead of git

Can we add that option by default?

Or at least configurable like the patchlevel

Thank you for such a great project :)

**Comment by kinglozzer** [comment]
+1 for this

**Comment by attisan** [comment]
would be a decent default value 👍

**Comment by seanbeaton** [comment]
I've created #370 which implements this as a config option you can add to your composer.json.

**Comment by cweagans** [comment]
See #370 -- IMO, just fix the patch if it's causing issues.
