### ISSUE TITLE
Warn if git apply fails and native patch command not found

### ISSUE THREAD

**Issue by scottsb** [cweagans/composer-patches#245]
Currently if a patch fails using Git this package will fall back to the native `patch` command. If the local native `patch` command isn't installed, however, it will fail with the generic error, "Cannot apply patch."

It would be useful to have a more explicit message that the native patch command was tried and failed to be found. The default error implies that there is something wrong with the patch, which caused us to pull our hair out when it only occurred on a single server, until we realized `patch` wasn't installed.

I'll submit a PR for this if I can get some form of approval this is desirable.

**Comment by cweagans** [comment]
Happy to merge something like this as long as it's a pretty small change.

**Comment by mschop** [comment]
Supplement: Patching silently fails, if git and patch is not installed. The composer install process should fail, if neither git nor patch is installed and a specific error message should be printed. Additionally, you should add this dependency in the README.

**Comment by cweagans** [comment]
`main` does this a little differently. It is definitely not silent anymore and will eventually link to the relevant section of a troubleshooting guide.
