### ISSUE TITLE
Fatal error when installing D8 using composer

### ISSUE THREAD

**Issue by lsolesen** [cweagans/composer-patches#25]
When installing Drupal 8 using the following command

    composer create-project drupal-composer/drupal-project:8.x-dev d8 --stability dev --no-interaction 

I get this fatal error caused by composer-patches

    PHP Fatal error:  Class 'Composer\Installer\PackageEvents' not found in /home/codio/workspace/d8/vendor/cweagans/composer-patches/src/Patches.php on line 67              
                                                                                                                                                                          
    Fatal error: Class 'Composer\Installer\PackageEvents' not found in /home/codio/workspace/d8/vendor/cweagans/composer-patches/src/Patches.php on line 67

**Comment by cweagans** [comment]
What version of composer are you using?

**Comment by lsolesen** [comment]
Composer version 1.0-dev (2b16a73659b12c35b2ab623b69688295d95ff2de) 2014-12-15 20:34:23

**Comment by lsolesen** [comment]
Ran composer self-update and it seems to be going better now. Thanks for the pointer
