### ISSUE TITLE
composer require cweagans/composer-patches results in strange behavior

### ISSUE THREAD

**Issue by azzisharbel** [cweagans/composer-patches#254]
Instead of re-explaining the issue again and again, please see the full details of this issue here: https://drupal.stackexchange.com/questions/276481/composer-update-command-behaves-in-a-strange-results

Note that running the "composer update --lock" or "composer update" before running the "composer require cweagans/composer-patches" results in no issue at all!

The issue explained in the provided URL is only available when you first run "composer require cweagans/composer-patches" and then try to run "composer update --lock".

any work around for this issue ?

**Comment by DavidBruchmann** [comment]
That's the nice aspect of links to other pages:

> Page not found  
> This question was removed from Drupal Answers for reasons of moderation.

**Comment by azzisharbel** [comment]
Very weird that drupal.stackexchange has deleted this question but you can find it below:

The idea is to apply patches to "Drupal core" and "Drupal modules" using "composer.json" file.
Following this guide at: https://groups.drupal.org/node/518975, I did the below:
1) Run the composer command:
`composer require cweagans/composer-patches`
2) Edit the composer.json file and add the below code:
```
"extra": {
    "patches": {
        "drupal/core": {
            "When a view is opened in a modal dialog, the title is displayed broken": "https://www.drupal.org/files/issues/2018-07-06/2663316-52.patch",
            "Entity Reference view is displayed as not expected in both the Form Display and View Display": "https://www.drupal.org/files/issues/2018-12-12/2174633-227.patch"
        },
        "drupal/field_group": {
            "Field group tabs are rendered as accordions in small screens": "https://www.drupal.org/files/issues/2018-09-12/configurable_breakpoint-2998778-5.patch"
        },
        "drupal/conditional_fields": {
            "error displayed when saving an entity utilizing conditional fields": "https://www.drupal.org/files/issues/conditional_fields-uninitialized_string_offset_in_conditional_fields_evaluate_dependency-2834358-11.patch"
        }
    }
},
```
3) Run:
`composer update --lock`

Step #3: Will generate composer.lock file from composer.json with latest changes like patch changes and make the composer files up to date.

However, after running the **composer update --lock** command, composer is re-installing again everything (Drupal core + all modules + all themes) and the strange is that everything is being downloaded in the directory before the **/web** directory.

Below are images about everything being re-installed:
![1](https://user-images.githubusercontent.com/15653987/55919180-9075bf00-5bfd-11e9-99d2-14e2ecdb9f19.png)
![2](https://user-images.githubusercontent.com/15653987/55919182-92d81900-5bfd-11e9-87fa-1b622f3c2ed9.png)
![3](https://user-images.githubusercontent.com/15653987/55919188-953a7300-5bfd-11e9-8552-64a1077f240e.png)

also below are images about my folder structure **before** and **after** the **composer update --lock**:

**Before running the command:**
![4](https://user-images.githubusercontent.com/15653987/55919189-97043680-5bfd-11e9-814a-5cf513f3cd58.png)

**After running the command:**
![5](https://user-images.githubusercontent.com/15653987/55919191-98cdfa00-5bfd-11e9-81dc-d24b0b60c34c.png)

Also my website become unavailable with the below error:
`Fatal error: Cannot redeclare _drupal_shutdown_function_handle_exception() (previously declared in S:\Sites\dev.website\web\core\includes\bootstrap.inc:1063) in S:\Sites\dev.website\core\includes\bootstrap.inc on line 1063`

Thank you,

**Comment by cweagans** [comment]
I have no idea what was happening here. Maybe a bad patch? Maybe something funky with your environment? Maybe a composer bug? Who knows?

`main` works pretty differently now and deleting and re-installing dependencies is an explicit action that you have to take -- it's not done automatically during the course of installation.
