### ISSUE TITLE
Display the package(s) that required a failing patch

### ISSUE THREAD

**Issue by TravisCarden** [cweagans/composer-patches#256]
When a build fails because composer-patches can't apply a patch declared by a third party package, it can be difficult to find the culprit in order to fix it. Output in that case currently looks like this:

```
  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/2241865-50.patch (#2241865: Do not create a new file entity to overwrite an existing entity)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2241865-50.patch
In Patches.php line 320:
                                                                               
  Cannot apply patch #2241865: Do not create a new file entity to overwrite a  
  n existing entity (https://www.drupal.org/files/issues/2241865-50.patch)!   
```

Perhaps it output could be expanded to include the package(s) that called for the patch. As inspiration, consider the output of `composer depends`:

```
$ composer depends drupal/acquia_connector
acquia/blt-project     dev-fc19a525eb8e51de360633e98ebcd2119399f042  requires  drupal/acquia_connector (*)
drupal/lightning_core  3.7.0                                         requires  drupal/acquia_connector (^1.1)
```

**Workaround:** It appears that this information gets written to `composer.lock` under `extra.patches_applied` in the declaring package object(s), so you can manually search for the answer there (if you get that far). ht @phenaproxima

**Comment by TravisCarden** [comment]
Thank you, @cweagans. Could you point me to  a PR/issue detailing this behavior change whereby "patches from dependencies are no longer resolved out-of-the-box"? I need to fully understand the change so I know whether my Drupal builds need to do anything in response.

**Comment by cweagans** [comment]
#267 is where it was removed. Don't make changes just yet though. This will be detailed in the release announcement down the road a bit + there may be another way to do it by then if I (or somebody else) writes a plugin to re-add the functionality.

**Comment by cweagans** [comment]
Just to be clear - this is for 2.x, which is not released yet. I won't be changing that behavior in 1.x.

**Comment by TravisCarden** [comment]
Great, thanks. 🙂
