### ISSUE TITLE
Backport the removal of PATCHES.txt to 1.x branch

### ISSUE THREAD

**Issue by donquixote** [cweagans/composer-patches#258]
In issue #140 / PR #213, the patch report generation (PATCHES.txt) was removed for the 2.x branch.
A release in this new branch has not happened yet.

I am going to provide a PR that backports this change to the 1.x branch.

**Comment by donquixote** [comment]
The two commits from #213 will be squashed in the backported PR.

**Comment by alisonjo315** [comment]
I applied the change with a PR patch from #259 -- works great, I see no side effects!  (Tested on a Drupal 8 project, with a patch to Drupal core.)

(Side note: I lol'ed when a "PATCHES.txt" file was created in `vendor/cweagans/composer-patches` 😁 -- not a bug at all, obviously, just a funny moment!)

**Comment by cweagans** [comment]
I'm okay with this, but can it be behind a config flag? I know of at least one user that relies on this and I don't want to break their workflow. Definitely okay with this being an opt-out thing though.

**Comment by awd-studio** [comment]
Hey! Would you mind? I made a PR for this.

**Comment by cweagans** [comment]
There is now a config flag for this in 1.x. `main` doesn't have this functionality at all.
