### ISSUE TITLE
Feature request: extend patches key-value list to support patch metadata

### ISSUE THREAD

**Issue by christopher-hopper** [cweagans/composer-patches#260]
## Problem / Motivation

When adding patches to a project it is important to track the source of a patch, to ensure it is kept up-to-date. The patch source will often be an issue queue or pull request containing context and ongoing discussion. 

When updating packages and addressing patch failures developers will find the source issue or pull request for the patch, in order to check the issue or pull request status. This process could be automated, for issue queues that expose an API or feed, if the patch issue URI was stored in a consistent data structure.

## Proposed Solution

A de-facto standard has already emerged for Drupal developers who use `cweeagans/composer-patches` 1.x to store patches in the key-value data structure with an issue number and URI to the issue queue. This standard takes some variation on the following:

```json
        "patches": {
            "drupal/core": {
                "1356276 - Allow profiles to define a base/parent profile and load them in the correct order - https://www.drupal.org/node/1356276": "https://www.drupal.org/files/issues/2018-10-12/1356276-531.patch",
                "2914389 - Allow profiles to exclude dependencies of their parent - http://dgo.to/2914389": "https://www.drupal.org/files/issues/2018-07-09/2914389-8-do-not-test.patch"
            }
        }
```

It would be better to formalize this into a consistent data structure so that plugins could be written to consume the metadata and report on the status of individual patches. This could be a new command similar to the `composer outdated` command that simply checks known issue queues and reports on status for each individual patch (ie. merged, new patch available, wont fix, etc).

If the following metadata was stored consistently, by the composer-patches tool, individual plugins could handle querying issue queues they know about - ie. github, drupal, bitbucket, gitlab, gist, etc. 

...Thinking like:

    patch-source (ie. github, drupal, bitbucket, gist, file) for use by a plugin
    patch-issue-id (ie. 2493183, ABC-123)
    patch-issue-uri (ie. https://www.drupal.org/node/2493183, https://github.com/vendor/repo/issues/81 )

At a minimum the Patch Issue URI could be used by a plugin to determine the Patch Source and Patch Issue Id. The issue queue URIs could be matched on a regex to pull out this information.

By using a plugin system to handle patch issue queue checks, you can focus this project on applying patches and let others extend the functionality to handle individual issue queue/patch sources that they know about. 

Related issues: 

- #81

**Comment by cweagans** [comment]
I'm mostly on board with codifying these fields, but it's important to note that the minimal key: value structure is going to continue to exist, even in 2.x. I'm not willing to break backwards compatibility on that for the time being just due to the sheer number of installations of this plugin. If plugins want to use this kind of data, it's totally fine to codify which fields they should look at, but they'll also need to handle (or probably more appropriately, ignore) the more minimal format.

**Comment by cweagans** [comment]
`main` supports this now. There is a compact definition (which is the same as what 1.x uses) and an expanded definition which has an `extra` field, which can be used for whatever you'd like.
