### ISSUE TITLE
New patch not applying

### ISSUE THREAD

**Issue by nicholasscottfish** [cweagans/composer-patches#261]
Hi there,

Great package, keep up the good work. I am however having a problem installing a new patch that I have created. I have added the entry to the composer.patches.json file, and added the patch to the /patches/composer directory.

```
{
    "patches": {
        "magento/module-sales": {
            "PR-18472: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "patches/composer/PR-18472-Sales.diff"
        },
        "magento/framework": {
            "PR-18472: Alternative fix for Multi Store Emails issue, Fix Async Emails issues, Fix Multiple Email issues": "patches/composer/PR-18472-Framework.diff"
        },
        "magento/module-customer": {
            "ISSUE-14530: Fixes password reset issue that empties basket of active session": "patches/composer/ISSUE-14530-AccountManagement.diff"
        }
    }
}
```

The top two patches are applying fine, just not the new one. No errors.

When running a composer install I see this output in the console:

```
Using compact definition format for package magento/module-customer
```

This leads me to believe that it is aware of the patch file.

Please may somebody help point me in the right direction?

Regards,

Nick

**Comment by DavidBruchmann** [comment]
Probably the patch for "magento/module-customer" includes still changes for another module. You've to separate it in two or more patches then.

**Comment by VincentMarmiesse** [comment]
I'm facing the same issue, also on Magento 2 :)

I'm trying to patch `magento/module-bundle-import-export`, and I have the same message:
```
Using compact definition format for package magento/module-bundle-import-export
```

My patch section is:
```
"patches": {
    "magento/module-bundle-import-export": {
       "Fix parent child relations creation": "patches/fix_bundle_import_relation.patch"
    }
}
```

**Comment by cweagans** [comment]
@nicholasscottfish @VincentMarmiesse  sorry for the long delay. It looks like you're using dev-master. You should try one of the 1.x releases.
