### ISSUE TITLE
Add documentation for triggering applying of patches

### ISSUE THREAD

**Issue by rooby** [cweagans/composer-patches#268]
Although a lot of people will already know, for the sake of complete documentation I think it's worth documenting the commands you would use to actually apply a patch after you have added the patch info to the package.json.

**Comment by marcvangend** [comment]
I think I know, but I'm not even 100% sure if my method (`composer update nothing` or `composer update nothing --no-dev`) is considered correct, and I have seen issues that may or may not be related to this. What is your method @rooby ?

**Comment by rooby** [comment]
It seems like so long since I've done it haha. I haven't really touched Drupal since I wrote that last comment.

Depends what I'm doing at the time.
In some cases I add a patch prior to requiring the module in which case I don't have to do anything except `composer require` the module after adding the patch to the composer.json.
Otherwise, if I'm just adding a patch then I use `composer install`, since that will keep all my existing versions as per the lock file and then install the new patch I've added to the composer.json.

I generally don't use `composer update nothing` for anything since it is really just a hack used for its side-effects. It could also have unwanted results if you were working on a project that had a nothing package (a probably silly edge case I know).

Anything that syncs your files with the config in the composer.json should trigger the patch to install I think.

I also don't know if my ways are the preferred, which is why I was hoping the maintainer would advise via the documentation.

**Comment by davereid** [comment]
The problem is with using composer install to add a new patch, it doesn't actually update the composer.lock file's "patches_applied" information, even though it applied the patch. I have to use `composer update --lock` instead

**Comment by rooby** [comment]
Ah good to know.

**Comment by snoroozi** [comment]
I was given instructions to update a magento amazon pay module, but the final steps are 

composer -v install
composer update --lock

how can I make sure only the patch is applied and not all my other magento modules get updated with composer update --lock?

**Comment by KalleVuorjoki** [comment]
In production I use `composer install --no-dev --no-scripts` and I notice it won't apply the patches. I've some scripts that are required in local development. Is there any way to use `composer install` without running the scripts, but applying the patches?

**Comment by KalleVuorjoki** [comment]
Seems like this is a known issue https://github.com/cweagans/composer-patches/issues/273

**Comment by cweagans** [comment]
I've made a note to document this, but in `main`, you can run `composer patches-repatch` to repatch your dependencies.

**Comment by rooby** [comment]
> I've made a note to document this, but in `main`, you can run `composer patches-repatch` to repatch your dependencies.

Does “made a note to document this” mean it’s not actually done?
If so it seems like this shouldn’t be closed yet.

**Comment by blacktek** [comment]
Do you know why I get the error below?
Command "patches-repatch" is not defined. 

composer -V
Composer version 2.8.5 2025-01-21 15:23:40
PHP version 8.4.4 (C:\php8.4\php.exe)

**Comment by cweagans** [comment]
You're probably not using 2.x.

**Comment by blacktek** [comment]
you're right. 2.x is beta. I'm on 1.7.3

tnx
