### ISSUE TITLE
Could not apply patch! Skipping.

### ISSUE THREAD

**Issue by killua99** [cweagans/composer-patches#27]
The error is happening to me in multiple environments. On a Linux server, on a vagrant machine and windows. This is the log

      - Installing drupal/google_map_field (dev-8.x-1.x 1823e1d)
        Cloning 1823e1d790a592d1258ae99c34beae5d6cda57de
    Executing command (CWD): git clone --no-checkout 'https://git.drupal.org/project/google_map_field' 'web/modules/contrib/google_map_field' && cd 'web/modules/contrib/google_map_field' && git remote add composer 'https://git.drupal.org/project/google_map_field' && git fetch composer
    Executing command (web/modules/contrib/google_map_field): git branch -r
    Executing command (web/modules/contrib/google_map_field): git checkout '8.x-1.x' --
    Executing command (web/modules/contrib/google_map_field): git checkout -B '8.x-1.x' 'composer/8.x-1.x' --
    Executing command (web/modules/contrib/google_map_field): git reset --hard '1823e1d790a592d1258ae99c34beae5d6cda57de' --

        REASON: Required by root: Install command rule (install drupal/google_map_field dev-8.x-1.x)

      - Applying patches for drupal/google_map_field
    Checking CA file /etc/ssl/certs/ca-certificates.crt
        https://www.drupal.org/files/issues/undefined_method_checkPlain-2629530-4.patch (node/2629530 - Call to undefined method checkPlain)
    Downloading https://www.drupal.org/files/issues/undefined_method_checkPlain-2629530-4.patch
       Could not apply patch! Skipping.

**Comment by yched** [comment]
Did you check if the patch at https://www.drupal.org/files/issues/undefined_method_checkPlain-2629530-4.patch actually applies on the version of google_map_field you're downloading ? :-)

Since you're using the 8.x-1.x-dev of the module, it seems very likely that this is a moving target. You  probably want to stick to a fixed tag/release, or if not possible, at list pin to a specific git hash

**Comment by webflo** [comment]
I had a similar issues today and tracked it down to recent changes in composer itself. Because composer is unable to validate SSL certificates with SNI (https://github.com/composer/composer/issues/4782, https://github.com/composer/composer/pull/4798)

**Comment by Seldaek** [comment]
Please try again after running `composer self-update`, I merged the two PRs in composer and it should all be good now.

**Comment by killua99** [comment]
I can confirm after ran `composer self-update` the patch was applied without problem. Thanks for follow this issue and track the real problem with the SSL certificates.

**Comment by cweagans** [comment]
Wow, thanks for the effort here, everyone! And thanks @Seldaek for the follow up here after things were committed. That's very helpful :)

Looks like this is resolved now, so closing.

Thanks again!

**Comment by Niklan** [comment]
For me it was missing `patch` package from the system. I've installed it `yum install patch` and it works.

For those who can't solve prolem just type with `-v` parameter. It can tell you more.

**Comment by WPaceStaves** [comment]
So what was the fix!?!?

**Comment by cweagans** [comment]
@WPaceStaves in this particular issue, it was a problem in Composer that was resolved upstream. I imagine that you're seeing a similar error message to the issue title, and my guess is that whatever patch you have defined doesn't apply properly. Try manually applying the patch with `patch -p1` and if that doesn't work, reroll your patch.

**Comment by iThom** [comment]
I also had the same problem with an alpine docker container and the solution was to force the install/upgrade of the `patch` package (now in 2.7.6) `apk add --update --no-cache patch` as it was blocked to the version 1.30 natively in busybox  which doesn't support the -d option (to chage the working directory). Now everything work fine.

**Comment by mehdichaouch** [comment]
Using a Docker `php:7.4-alpine-composer`, I also get the error _"Could not apply patch! Skipping. The error was: Cannot apply patch .....patch"_.
Adding `apk add --update --no-cache patch` to my CI build worked.

Thanks @iThom.
