### ISSUE TITLE
Broken logic when patches{} is empty

### ISSUE THREAD

**Issue by dandelionred** [cweagans/composer-patches#271]
Hey guys! Thanks for the epic piece of code!

I've got a problem with 1.6.5. Comparing the current 1.x branch to 1.6.5 I don't see any relevant changes so the behaviour should be the same for the current state of 1.x branch.

Here is my usage case:
- have `"enable-patching": true` under root composer.json/`extra` to always bypass `isPatchingEnabled()`
- have some packages patched with cweagans/composer-patches in the root composer.json
- undo one of the patches
  - route 1: move the patch from "patches" into "patches-ignore" and issue `composer -vv update --lock`
  - route 2: delete the patch from "patches" and issue `composer -vv update --lock`

Having 3 patches overall I try to undo one of them either route and it works.
2 patches left. Now I try to undo another one either route and it works.
**1 patch left**. I try to undo it either route and **it doesn't work at all**, it says
```
Gathering patches for root package.
No patches supplied.
```

Look at these piece

https://github.com/cweagans/composer-patches/blob/1d89dcc730e7f42426c434b88261fcfb3bce651e/src/Patches.php#L104-L124

(\*) Assume installed packages don't use cweagans/composer-patches on their own (like 99.95% of usage cases).
Assume we only have some (it doesnt matter how many) patches installed via root composer.json and want to undo them **all** in one go either route. In both cases composer.json/extra/patches would become empty.

So $tmp_patches is empty in line 104.
Line 107 is always false because (\*).
Line 118 merges $tmp_patches with an empty array always because (\*).
Hence by line 121 $tmp_patches is still empty and the function immediately returns while there is a change to the patch set actually.

So the code always stops at line 123 when composer.json/extra/patches is empty even though it doesn't mean the patchset has not been changed.

Atm I use a dirty trick in composer.json: append a `"stub":{}` placeholder to composer.json/extra/patches so it is never empty. It works but dirty tricks are dirty.

**Comment by cweagans** [comment]
This works a lot differently in `main`. This trick should not be necessary anymore.
