### ISSUE TITLE
composer install

### ISSUE THREAD

**Issue by ryangroth5** [cweagans/composer-patches#272]
Can't install:

  - Installing cweagans/composer-patches (1.6.5): Loading from cache
Plugin installation failed, rolling back
  - Removing cweagans/composer-patches (1.6.5)

Installation failed, reverting ./composer.json to its original content.

  [ErrorException]
  include(/opt/org/vendor/cweagans/composer-patches/src/Pa
  tches.php): failed to open stream: No such file or directory

**Comment by ryangroth5** [comment]
It has to do with a vagrant box sharing a windows filesystem.

**Comment by malcomio** [comment]
Seems to be a duplicate of #285, which has more information

**Comment by pokono** [comment]
Did anybody solve this?
