### ISSUE TITLE
Patch applies locally but fail on server

### ISSUE THREAD

**Issue by andrzej-lumini** [cweagans/composer-patches#274]
I want to apply [this patch](https://www.drupal.org/files/issues/2018-09-10/1349080-411.patch) against drupal core from [this issue](https://www.drupal.org/project/drupal/issues/1349080)

The patch applies locally without problem but fails on my server.
I have same php versions (7.2.18) same composer version (1.8.5 2019-04-09 17:46:47)

here my very simple composer.json file :

{
    "name": "test",
    "description": "test",
    "type": "project",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "cweagans/composer-patches": "~1.0",
        "drupal/core": "8.7.2"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "vendor-dir": "drupal/vendor",
        "secure-http": false,
        "sort-packages": true,
        "platform": {
            "php": "7.2"
        }
    },
    "extra": {
        "patches": {
            "drupal/core": {
                "node_access filters out accessible nodes when node is left joined": "https://www.drupal.org/files/issues/2018-09-10/1349080-411.patch"
            }
        }
    }
}

When i look in details i see why the patch is not applying - there are some minor changes in the source file - my question is why it applies locally ?
It seems to be more permissive locally.

**Comment by cweagans** [comment]
Try removing all composer-installed dependencies, and then do a `composer install`. Does the patch still fail?

You might also have different versions of `git` or `patch`.

**Comment by andrzej-lumini** [comment]
I've removed composer cache, composer.lock and the drupal folder. Then i've executed composer install -vvv and i have this strange error :

---
 - Applying patches for drupal/core
    https://www.drupal.org/files/issues/2018-09-10/1349080-411.patch (node_access filters out accessible nodes when node is left joined)
Downloading https://www.drupal.org/files/issues/2018-09-10/1349080-411.patch
patch '-p1' --no-backup-if-mismatch -d '/drupal/vendor/drupal/core' < '/tmp/5cf14d58c539c.patch'
Executing command (CWD): patch '-p1' --no-backup-if-mismatch -d '/drupal/vendor/drupal/core' < '/tmp/5cf14d58c539c.patch'
sh: 1: patch: not found
---

**sh: 1: patch: not found** 

strange...

**Comment by cweagans** [comment]
Looks like maybe `patch` isn't installed at all.

**Comment by andrzej-lumini** [comment]
... brillant :)
Didn't even know that patch was a package... i thought every think was in 'git' : git apply, git diff, etc..
thanks !

**Comment by cweagans** [comment]
No problem :)

`patch` is used if it's available. `git apply` is usually a better tool, but sometimes `patch` picks up the slack.

**Comment by mamsincl** [comment]
just for the record (after digging into our agency's pipeline build/deploy workflow since we've faced with the same issue)

might be obvious (and it was not the case in the original issue above), but module **shouldn't be required as dev module** ... that also could causing that patch will not been applied to live but local development only

**Comment by robgos04** [comment]
Hi is there any way to apply patch for vendor files?
Basically there's this package in vendor directory that I need to modify the code. After modify and create patch file, I put it inside my composer.json as:
"patches": {
            "<packagename>/<packagesubname>": {
                "<description>": "patches/<patchname>.patch"
            },
            
 But when run composer install, it just removing this package, but not reinstall or adding the patch.
 I heard that create patch for vendor is not common.
 Any idea about this?
