### ISSUE TITLE
Option to add dev-only patches?

### ISSUE THREAD

**Issue by bserem** [cweagans/composer-patches#276]
Would it be possible to add a `dev` only patch? One that would be applied only to specific environments and that will *not* be applied on production.

Long story:
I need to apply this patch to protect some environments:
https://www.drupal.org/project/drupal/issues/2842858#comment-12028577
But have no need for it on production.

**Comment by cweagans** [comment]
Dup of https://github.com/cweagans/composer-patches/issues/237

Short answer: not opposed, but this is not a high priority for me.
