### ISSUE TITLE
Patches defined in non-root composer.json files (sometimes) cause target projects to not be reinstalled

### ISSUE THREAD

**Issue by mlncn** [cweagans/composer-patches#277]
Scenario:

* drutopia_core requires `drupal/facets ^1.3` and applies a patch to it.
* contacts requires `drupal/facets 1.x-dev` (which has that patch already committed)
* my composer.json can override drutopia_core and get the dev version of facets, cool.
* first time running `composer update`, it fails to apply the patch (cool, no problem, i can ignore the error message but if there's a way to override a patch from the root composer.json that'd be cool) but also the facets module is no longer there when composer update finishes running!
* running `composer update` again and the patch still fails to apply (naturally) but facets module was present where expected at the end.

This is the exact same behavior described [in this comment on a related merged merge request](https://github.com/cweagans/composer-patches/pull/30#issuecomment-247632096 ).

**Comment by mlncn** [comment]
Oh and here's the [composer.json file](https://gitlab.com/find-it-program-locator/findit-dev/blob/c63e33a4d84ee50fa842357b7923ce06ac3c3580/composer.json)

**Comment by mlncn** [comment]
... and now this problem has become a complete blocker, as there's a second module affected.  And you guessed it: running `composer update` another time brings back the first module but deletes the second, and vice versa, and so on ad infinitum.

**Comment by cweagans** [comment]
`main` no longer resolves patches from dependencies, nor does it automatically delete stuff that has been installed.
