### ISSUE TITLE
Add option to debug

### ISSUE THREAD

**Issue by MPParsley** [cweagans/composer-patches#278]
It would be nice to have an option to enable debug for this project.

When running composer install we get random failures:

```
- Applying patches for drupal/entity_browser
   https://www.drupal.org/files/issues/2019-07-06/entity_browser-problems-with-multilingual-2721665-46.patch (Problems with multilingual entities)
  Could not apply patch! Skipping. The error was: Content-Length mismatch, received 0 bytes out of the expected 3519
 - Applying patches for drupal/suggest_similar_titles
   https://www.drupal.org/files/issues/2019-07-15/suggest_similar_titles-d8_port-2829320-4.patch (Drupal 8 refactor)
  Could not apply patch! Skipping. The error was: Content-Length mismatch, received 0 bytes out of the expected 6295
 - Applying patches for drupal/migrate_plus
   https://www.drupal.org/files/issues/2019-07-17/2958672-dom-migration-lookup-16.patch (Use migration lookup on text fields)
  Could not apply patch! Skipping. The error was: Content-Length mismatch, received 0 bytes out of the expected 4041 (edited)
```

I [discussed this with the Drupal infrastructure team](https://drupal.slack.com/archives/C51GNJG91/p1566205691171600) but they need more debug output to further troubleshoot this.

> drumm
> Either of these issues needs more information to troubleshoot, like a `curl -v …` request that returns 0  bytes, but has some headers started.

See https://www.drupal.org/project/infrastructure/issues/3076207

**Comment by cweagans** [comment]
It looks like the original issue has been resolved, but this is probably a good thing to include. We don't use curl to download patches though -- we use the built in Composer file downloader instead. I'm not sure if there's some kind of debug flag that can be passed there, but I'm definitely not opposed to passing it if `-vvv` is specified.

**Comment by cweagans** [comment]
This appears to have been a transient failure. If you're persisting the composer cache between builds, this won't happen in `main` (downloaded patches are cached locally).
