### ISSUE TITLE
Retry failed download

### ISSUE THREAD

**Issue by Berdir** [cweagans/composer-patches#279]
For a while now, d.o has some infrastructure problems that causes failed downloads, the result looks like this:

Could not apply patch! Skipping. The error was: Content-Length mismatch, received 0 bytes out of the expected 3784

This is completely random and causes failed CI builds, deployments and so on.

Until that's dealt with, it would be nice of composer-patches could maybe just retry a download 1-2 times in case of such a generic error?

**Comment by Berdir** [comment]
Cross-referencing https://www.drupal.org/project/infrastructure/issues/3076207.

**Comment by MPParsley** [comment]
In cweagans\Composer\Patches::getAndApplyPatch the download is initiated:

```
      $downloader->copy($hostname, $patch_url, $filename, FALSE);
```

I suggest we add an option **retry** to the config:

```
{
  "config": {
    "preferred-install": "source",
    "retry": "true"
  },
  ...
}
```

**Comment by Berdir** [comment]
Created a merge request with a minimal implementation, without a configuration key. Given the current issues, I think we should at default that key to TRUE if we're going to add one?

**Comment by Berdir** [comment]
Maybe it should display a warning or something like that, didn't really look how that would be done.
