### ISSUE TITLE
Handle manual patch conflict resolution

### ISSUE THREAD

**Issue by cweagans** [cweagans/composer-patches#28]
If `patch1.diff` and `patch2.diff` both modify the same file, patching will fail. As a user, I should be able to manually apply both patches, and then somehow tell composer-patches about the result of applying both patches. At this point, composer-patches would generate a new diff, store it in the repository and tell the user to commit it to VCS. For future `composer install` operations, composer patches would then use the pre-resolved version that's stored in the repository.

**Comment by simesy** [comment]
I wonder if `git rerere` would help you here.

**Comment by cweagans** [comment]
I don't think so. Internally, this plugin just uses `diff` (rather than `git diff`), because we can't make assumptions about the VCS in use (some people may be using svn or mercurial or something). Using git for everything would be nice, and could simplify things. Maybe in the future, we can abstract out some of that logic and detect the best patching strategy for the VCS currently in use or something.
