### ISSUE TITLE
Defined base structure and all options available README

### ISSUE THREAD

**Issue by Ig0r-M-magic42** [cweagans/composer-patches#281]
For people new to this is important to know what options are available and what are the benefits of using them, for example did not knew that prefer install to source will allow to use git apply instead of patch which was one of the reasons a patch was applied but still flagged as not applied (did not look further into this to understand why).
```json
  "config": {
    "preferred-install": "source"
  },
```

**Comment by weitzman** [comment]
Agreed - i did not know that either.

**Comment by cweagans** [comment]
I've made a note to document this in `main`.

**Comment by cweagans** [comment]
Can you take a look at https://docs-staging.cweagans.net/composer-patches/usage/configuration/ and let me know if it's along the lines of what you were looking for?

**Comment by cweagans** [comment]
(The configuration options there are specific to 2.x)

**Comment by Ig0r-M-magic42** [comment]
@cweagans documentation looks good, what about `"preferred-install": "source"` which was defining via what software a patch was applied, i.e. either using `patch` or `git` (see body of the issue), currently i do not see this configuration and was wondering if the logic changed maybe since this issue has been raised?

**Comment by cweagans** [comment]
It has changed. Right now, main _only_ uses git to apply patches. If the target isn't a git repo, the plugin creates a temporary git repo so that the patch can be applied.
