### ISSUE TITLE
1.6.7 Install error: src/Patches.php - no such file or directory

### ISSUE THREAD

**Issue by keithstewart23** [cweagans/composer-patches#285]
Hi

I get a very odd error when running 'composer require cwaegans/composer-patches' on my Drupal VM website directory:

  _- Installing cweagans/composer-patches (1.6.7): Loading from cache
Plugin installation failed, rolling back
  - Removing cweagans/composer-patches (1.6.7)

Installation failed, reverting ./composer.json to its original content.
                                                                                                                                                   
  [ErrorException]                                                                                                                                 
  include(/var/www/drupalvm/reading-challenge/vendor/cweagans/composer-patches/src/Patches.php): failed to open stream: No such file or directory_ 

I can see from the code that the file exists in src/Plugins/Patches.php, not src/Patches.php.

Suprised nobody else has had this problem? Makes me think there is something specific about my environment that is messing it up. Same thing happens for any version that I attempt to install.

Any thoughts?

**Comment by keithstewart23** [comment]
I might have fixed it by explicitly choosing version 1.6.7 in the composer.json file.

**Comment by mgathu1** [comment]
Same problem here.

**Comment by aaronvaca** [comment]
One more, same problem.

**Comment by csmith31247** [comment]
Similair problem here.

- Installing cweagans/composer-patches (1.6.7): Loading from cache",
"Plugin installation failed, rolling back",
"  - Removing cweagans/composer-patches (1.6.7)",
"",
"Installation failed, reverting ./composer.json to its original content.",
"",
"                                                                                                         ",
"  [UnexpectedValueException]                                                                             ",
"  Plugin cweagans/composer-patches could not be initialized, class not found: cweagans\\Composer\\Patches  "

**Comment by Amstutz** [comment]
Same here, vagrant on macOS, install in shared dir.

**Comment by tomo-dev-2018** [comment]
Same here, vagrant 2.2.7 on Win10

**Comment by sbrow** [comment]
I also have this problem, does anyone know a solution?

**Comment by cweagans** [comment]
Sounds like a lot of these are vagrant. To start narrowing down what might be happening, can you please provide some details about how the files are mounted/copied into the VM? NFS? rsync? Something else?

**Comment by sbrow** [comment]
I encountered this error using vagrant  with a kubuntu linux guest on a windows host. I solved it by deleting my vendor directory and composer.json, and re-running `composer install`.

**Comment by mdance** [comment]
I am experiencing this issue with drupalvm (running vagrant/virtualbox) with the default share type, if I change it to NFS a composer install seems to work fine.

Unfortunately, NFS shares break with a certain Mac update our development team as a workaround is using the default share type.

**Comment by amandeep-singh9** [comment]
Has anybody been able to resolve this? I am getting this issue when I'm trying to create drupal project using composer on vagrant shared folder inside VM on Windows.

**Comment by danlobo02** [comment]
try running with the `--no-plugins` flag

**Comment by Fichen** [comment]
> try running with the `--no-plugins` flag

It works for me on Vagrant 2.2.7 and Win 10 pro.

**Comment by rfmarcelino** [comment]
`--prefer-source` flag worked for me

**Comment by pokono** [comment]
This breaks any production build having a composer-lock. Any resolution?

**Comment by blue-sky-code** [comment]
Having this same issue. Mac, Vagrant, breaking on compose install...

**Comment by cweagans** [comment]
I really can't help without details here and nobody has provided anything concrete. The most expedient thing would be a simple Vagrantfile that reproduces the problem, but literally any detail would help here. Details about macOS version, Vagrant version, etc would help here.

> try running with the --no-plugins flag

Note that this will cause patches to _not_ be applied, as it disables composer-patches (and any other composer plugin you have installed).
