### ISSUE TITLE
Could not apply patch! Skipping. 

### ISSUE THREAD

**Issue by stockwerk23** [cweagans/composer-patches#288]
I can't install a drupal 8 thunder distribution on a production environment. And I don't know where to start with debugging. 

CENT OS
git version 1.8.3.1
composer version 1.9.1
PHP 7.3.11

Thanks for lookin!

Output of composer install -vvv:

Applying patches for drupal/core
    https://www.drupal.org/files/issues/2019-07-22/3055443-2-37.patch (Switch to a memory backend for running the database updates)
Downloading https://www.drupal.org/files/issues/2019-07-22/3055443-2-37.patch
patch '-p1' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/5dd2b17e25a3f.patch'
Executing command (CWD): patch '-p1' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/5dd2b17e25a3f.patch'
patching file core/lib/Drupal/Core/Update/UpdateBackend.php

patching file core/lib/Drupal/Core/Update/UpdateCacheBackendFactory.php

can't find file to patch at input line 122

Perhaps you used the wrong -p or --strip option?

The text leading up to this was:
--------------------------

|diff --git a/core/lib/Drupal/Core/Update/UpdateServiceProvider.php b/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
|index 22c9131eb3..7ac68e6b18 100644
|--- a/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
|+++ b/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
--------------------------

File to patch: 

Skip this patch? [y] 

Skipping patch.

2 out of 2 hunks ignored

can't find file to patch at input line 169

Perhaps you used the wrong -p or --strip option?

The text leading up to this was:
--------------------------

|diff --git a/core/modules/system/system.install b/core/modules/system/system.install
|index a4d467d253..fdbcca13b9 100644
|--- a/core/modules/system/system.install
|+++ b/core/modules/system/system.install
--------------------------

File to patch: 

Skip this patch? [y] 

Skipping patch.

1 out of 1 hunk ignored

patching file core/modules/system/tests/src/Functional/Update/UpdateCacheTest.php

patch '-p0' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/5dd2b17e25a3f.patch'
Executing command (CWD): patch '-p0' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/5dd2b17e25a3f.patch'
patching file b/core/lib/Drupal/Core/Update/UpdateBackend.php

patching file b/core/lib/Drupal/Core/Update/UpdateCacheBackendFactory.php

can't find file to patch at input line 122

Perhaps you used the wrong -p or --strip option?

The text leading up to this was:
--------------------------

|diff --git a/core/lib/Drupal/Core/Update/UpdateServiceProvider.php b/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
|index 22c9131eb3..7ac68e6b18 100644
|--- a/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
|+++ b/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
--------------------------

File to patch: 

Skip this patch? [y] 

Skipping patch.

2 out of 2 hunks ignored

can't find file to patch at input line 169

Perhaps you used the wrong -p or --strip option?

The text leading up to this was:
--------------------------

|diff --git a/core/modules/system/system.install b/core/modules/system/system.install
|index a4d467d253..fdbcca13b9 100644
|--- a/core/modules/system/system.install
|+++ b/core/modules/system/system.install
--------------------------

File to patch: 

Skip this patch? [y] 

Skipping patch.

1 out of 1 hunk ignored

patching file b/core/modules/system/tests/src/Functional/Update/UpdateCacheTest.php

patch '-p2' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/5dd2b17e25a3f.patch'
Executing command (CWD): patch '-p2' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/5dd2b17e25a3f.patch'
patching file lib/Drupal/Core/Update/UpdateBackend.php

patching file lib/Drupal/Core/Update/UpdateCacheBackendFactory.php

patching file lib/Drupal/Core/Update/UpdateServiceProvider.php

patch: **** Failed to set the owning group of file lib/Drupal/Core/Update/UpdateServiceProvider.php.o1OXdDk : Invalid argument

patch '-p4' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/5dd2b17e25a3f.patch'
Executing command (CWD): patch '-p4' --no-backup-if-mismatch -d 'docroot/core' < '/tmp/5dd2b17e25a3f.patch'
patching file Core/Update/UpdateBackend.php

patching file Core/Update/UpdateCacheBackendFactory.php

can't find file to patch at input line 122

Perhaps you used the wrong -p or --strip option?

The text leading up to this was:
--------------------------

|diff --git a/core/lib/Drupal/Core/Update/UpdateServiceProvider.php b/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
|index 22c9131eb3..7ac68e6b18 100644
|--- a/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
|+++ b/core/lib/Drupal/Core/Update/UpdateServiceProvider.php
--------------------------

File to patch: 

Skip this patch? [y] 

Skipping patch.

2 out of 2 hunks ignored

can't find file to patch at input line 169

Perhaps you used the wrong -p or --strip option?

The text leading up to this was:
--------------------------

|diff --git a/core/modules/system/system.install b/core/modules/system/system.install
|index a4d467d253..fdbcca13b9 100644
|--- a/core/modules/system/system.install
|+++ b/core/modules/system/system.install
--------------------------

File to patch: 

Skip this patch? [y] 

Skipping patch.

1 out of 1 hunk ignored

patching file tests/src/Functional/Update/UpdateCacheTest.php

   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2019-07-22/3055443-2-37.patch

                                                                                                                                                       
  [Exception]                                                                                                                                          
  Cannot apply patch Switch to a memory backend for running the database updates (https://www.drupal.org/files/issues/2019-07-22/3055443-2-37.patch)!  
                                                                                                                                                       

Exception trace:
 () at example.com/vendor/cweagans/composer-patches/src/Patches.php:320
 cweagans\Composer\Patches->postInstall() at n/a:n/a
 call_user_func() at phar:///home/user/composer/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:176
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///home/user/composer/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:116
 Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent() at phar:///home/user/composer/composer.phar/src/Composer/Installer.php:622
 Composer\Installer->doInstall() at phar:///home/user/composer/composer.phar/src/Composer/Installer.php:229
 Composer\Installer->run() at phar:///home/user/composer/composer.phar/src/Composer/Command/InstallCommand.php:122
 Composer\Command\InstallCommand->execute() at phar:///home/user/composer/composer.phar/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///home/user/composer/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/user/composer/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///home/user/composer/composer.phar/src/Composer/Console/Application.php:267
 Composer\Console\Application->doRun() at phar:///home/user/composer/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///home/user/composer/composer.phar/src/Composer/Console/Application.php:106
 Composer\Console\Application->run() at phar:///home/user/composer/composer.phar/bin/composer:61
 require() at /home/user/composer/composer.phar:24

**Comment by cweagans** [comment]
Looks like a bad patch.
