### ISSUE TITLE
Improve feedback/message when a patch was "previously applied"

### ISSUE THREAD

**Issue by alisonjo315** [cweagans/composer-patches#289]
It would be really cool to have different feedback when a patch has been committed to a project -- or, I realize "when a patch has been committed to a project" is impossible to know, but, maybe offering a modified message to indicate that the patch was "already applied," so to speak?

Right now, we get the normal `Could not apply patch! Skipping. The error was: Cannot apply patch https://www.example.com/path/to/thepatch.patch` -- if you add `-vvv` to your require/update command, you see that in fact, there are messages like these along the way:
```
Reversed (or previously applied) patch detected!
  Assume -R? [n] 

Apply anyway? [n] 

Skipping patch.

1 out of 1 hunk ignored
 -- saving rejects to file config/schema/menu_block.schema.yml.rej

The next patch would create the file menu_block.post_update.php,
which already exists!
  Assume -R? [n] 

Apply anyway? [n] 

Skipping patch.

1 out of 1 hunk ignored
```

It would be soooo cool if the feedback without `-vvv` were like, 
`Could not apply patch! Skipping. The error was: Reversed (or previously applied) patch detected, cannot apply patch https://www.example.com/path/to/thepatch.patch`

Idk if that's generic enough, or if it's realistic to detect this situation well enough to give a different feedback message, but, it would be cool!

.............
If it's not realistic, maybe just adding a line to the non-verbose message, so that it goes something like:
```
Could not apply patch! Skipping. The error was: Cannot apply patch https://www.example.com/path/to/thepatch.patch
For more details, re-run your command with -vvv.
```

**Comment by cweagans** [comment]
This should happen a lot less frequently in `main` since it doesn't pull in patches from dependencies. The root composer.json and/or a separate patches.json are considered the canonical list of all patches applied to the project, so if a patch is applied twice, it'll be because it was added twice.
