### ISSUE TITLE
composer patch with new file will generate a b/ folder in modules

### ISSUE THREAD

**Issue by uabassguy** [cweagans/composer-patches#290]
Example:
a patch that contains something similar to this:

new file mode 100644
index 00000000000..d1a53645563
--- /dev/null
+++ b/vendor/magento/module-inventory-reservations/Model/ResourceModel/GetReservationsQuantityCache.php

Will create a file at
vendor/magento/module-inventory-reservations/b/vendor/magento/module-inventory-reservations/Model/ResourceModel/GetReservationsQuantityCache.php

Same result on 1.6.2 and 1.6.7

**Comment by cweagans** [comment]
https://github.com/cweagans/composer-patches/tree/1.x#allowing-to-force-the-patch-level--px

**Comment by devamitbera** [comment]
@uabassguy 
Do find any solution?

```
{
  "extra": {
    "patchLevel": {
      "vendorname/patch": "mypatch.patch"
    }
  }
}
```

that is not working?

**Comment by diazwatson** [comment]
Example:
```
  "amasty/module-visual-merchandiser": {
      "Adds additional SortBySellableQty option" : "patches/amasty/AddsSortBySellableQty.patch"
  },
  "patchLevel": {
      "amasty/module-visual-merchandiser": "-p2"
  }
 ```
