### ISSUE TITLE
Both "patches-file" and "patches" should work in order

### ISSUE THREAD

**Issue by saltednut** [cweagans/composer-patches#291]
I have seen intermittent issues with this.  One initial test showed that patches from a `patches-file` as well as a patch listed right below that under `patches` both applied to the codebase.

However, after pulling in unrelated code, deleting my lock file and running `composer install` again, I instead see only the patch listed under `patches` being applied and the `patches-file` is ignored.

The only workaround at that point was to delete the `patches` definition and only use `patches-file` - at that point I could consistently get all patches to apply, though it stands to reason that all patches, both from a `composer.patches.json` in addition to ones listed in `composer.json` would both apply. 

There are use cases where an external (remote repo, raw file download) is desirable as the `patches-file` where a few additional `patches` should also be added.

**Comment by cweagans** [comment]
What if only the external patches file worked? I was talking with somebody on Twitter about this the other day. This would be specifically for 2.0, but it could simplify things quite a bit.

**Comment by brantwynn** [comment]
Right now that is how we are seeing it work. But if one wants to add
additional patches downstream it is still difficult to do. #292 should be
addressed there.

**Comment by cweagans** [comment]
`main` doesn't resolve patches from dependencies anymore.
