### ISSUE TITLE
Patches listed in a dependency's `patches-file` are not loaded during install

### ISSUE THREAD

**Issue by saltednut** [cweagans/composer-patches#292]
We were trying this with `acquia/df` repo.  We moved all our patches into a `patches-file` definition.  Other projects, such as `acquia/df-project` pull down `acquia/df` as a dependency.

When `acquia/df/composer.json` contains a reference to a local `patches-file` the file is only loaded when running composer install on that repo. When it is a listed dependency, there are no errors, but we expect to see a lot of patches for core and contrib to come through and those do not land.

The workaround we came up with is to reference this patches file as an external raw file.  So something like, `"patches-file": "https://raw.githubusercontent.com/acquia/df/8.x-4.x/composer.patches.json",`

This is a work-around that only applies to this select use case.  If another dependency were to also use a patches file, we wouldn't be able to bring in both files like this.

Additionally, if we wanted to add more `patches` on top of the `patches-file` provided ones, we cannot. See: #291

**Comment by cweagans** [comment]
`main` doesn't resolve patches from dependencies anymore.
