### ISSUE TITLE
Custom repo definitions should be optionally loaded via a `repositories-file`

### ISSUE THREAD

**Issue by saltednut** [cweagans/composer-patches#293]
Similar to the `patches-file` we would benefit greatly from a `repositories-file` where we could include it externally across multiple repos, only needing to update the VCS definitions once and they would propagate down the chain.

E.g. a repo like `acquia/df` gets included in other project a lot. In order for it to land correctly, its VCS definitions need to be mirrored exactly the same.  This causes for a fair amount of redundancy across projects.

Ex, any change to:  https://github.com/acquia/df/blob/4da604849db7234dc0000faa58acc9f113835f5f/composer.json#L13-L38 

Would require a change to:
https://github.com/acquia/df-project/blob/8.x-4.x/composer.json#L15-L40

**Comment by brantwynn** [comment]
Example of how we'd fix this would be by adding a line like this:

```
"repositories-file": "https://raw.githubusercontent.com/acquia/df/8.x-4.x/composer.repositories.json",
```

**Comment by brantwynn** [comment]
I won't file another issue (unless you want one) but it would be great to be able to also have a `patches-ignore-file` as well.  We tend to ignore a lot of patches because we are a sub-profile of Lightning, for example. NBD, but maybe worth noting here.

**Comment by cweagans** [comment]
This doesn't seem to be related to composer patches?
