### ISSUE TITLE
Make git apply working in non-root-git directories

### ISSUE THREAD

**Issue by mvorisek** [cweagans/composer-patches#294]
`git` is the right choise for appliing patches as it is available more than every other solution at the most dev/prod systems, espetially non-linux ones like Windows, where the `patch` alternative is not often installed (or at least it is not available from the `PATH`).

I have analysed the issue related with issue #148 ( https://stackoverflow.com/questions/24821431/git-apply-patch-fails-silently-no-errors-but-nothing-happens/#27283285 ):

Problem:
patch is not applied via `git apply` if outside `.git` directory, in this case `Skipped patch '<file path>'.` verbose warning is show.

Analysis:
1. trigerred here: https://github.com/git/git/blob/b02fd2accad4d48078671adf38fe5b5976d77304/apply.c#L4696
2. based on condition https://github.com/git/git/blob/b02fd2accad4d48078671adf38fe5b5976d77304/apply.c#L4681
3. the condition is not matched in case of not matching `state->prefix` (.git directory root path) https://github.com/git/git/blob/b02fd2accad4d48078671adf38fe5b5976d77304/apply.c#L2077
4. `state->prefix` is set solely here https://github.com/git/git/blob/b02fd2accad4d48078671adf38fe5b5976d77304/apply.c#L93
5. from `setup_git_directory_gently()` https://github.com/git/git/blob/99c33bed562b41de6ce9bd3fd561303d39645048/git.c#L416 line as the `git apply` command is marked with `RUN_SETUP_GENTLY` option
6. `setup_git_directory_gently()` function tries to find `.git` directory and then it tests it with `is_git_directory` https://github.com/git/git/blob/bc12974a897308fd3254cf0cc90319078fe45eea/setup.c#L311 , this function tests the presence of these files:
   - `.git/objects/`
   - `.git/refs/`
   - `.git/HEAD`

These files needs to be presented in order to make `git patch` working.

PR submitted.

**Comment by mvorisek** [comment]
Probably the best solution will be to use git which is more than every other solution available at the most dev/prod Windows systems.

So workaround about the `git apply`:
https://github.com/cweagans/composer-patches/blob/1.6.7/src/Patches.php#L530
should be created, like creating git repo and then applying the patch.

**Comment by mvorisek** [comment]
Or what about using pure PHP lib - https://github.com/yetanotherape/diff-match-patch ?

**Comment by cweagans** [comment]
See https://github.com/cweagans/composer-patches/pull/296#issuecomment-647074418
