### ISSUE TITLE
Drupal 8 install on Windows chokes on composer-patches

### ISSUE THREAD

**Issue by dorianwinterfeld** [cweagans/composer-patches#298]
I am getting the following error when using composer to install Drupal 8 on Windows.  I deleted the entry for composer-patches in composer.json and then the install works.  Sorry if this is a known issue.  Is there a fix for this?  

`PS D:\> composer create-project drupal-composer/drupal-project:8.x-dev asc-dev --stability dev --no-interaction
Installing drupal-composer/drupal-project (8.x-dev 04a3fe08d35bfdbdcb9718556fbe8181cd111ff0)
  - Installing drupal-composer/drupal-project (8.x-dev 04a3fe0): Cloning 04a3fe08d3 from cache
Created project in asc-dev
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 149 installs, 0 updates, 0 removals
  - Installing cweagans/composer-patches (1.6.7): Loading from cache
    Failed to download cweagans/composer-patches from dist: RecursiveDirectoryIterator::__construct(D:\asc-dev/vendor/co
mposer/,D:\asc-dev/vendor/composer/): The system cannot find the path specified. (code: 3)
    Now trying to download from source
  - Installing cweagans/composer-patches (1.6.7): Cloning 2e6f72a2ad from cache

  [ErrorException]
  file_put_contents(D:\asc-dev/vendor/composer/installed.json): failed to open stream: No such file or directory`

**Comment by marco-santos-diamond** [comment]
I'm having the same issue.

Does anyone know how to solve?
