### ISSUE TITLE
Installing patches through vendor dependency

### ISSUE THREAD

**Issue by jellesiderius** [cweagans/composer-patches#302]
Hi

We're using the composer-patches and this is awesome. We're now trying to use a vendor package containing all patches we're using within our projects. This is throwing an error the first time composer is installing all vendor packages because composer can't find the file since it's not yet available in our vendor/patches package. Is there any way to get this working like we try to do?

**Comment by cweagans** [comment]
Not sure I fully understand what you're trying to do, but `main` doesn't support resolving patches from dependencies anymore, so this workflow likely won't work.
