### ISSUE TITLE
When patch exits on failure, it still writes to installed.json

### ISSUE THREAD

**Issue by threeg** [cweagans/composer-patches#305]
We had a patch fail to apply when running composer install. composer-exit-on-patch-failure is set to true.

Once the issue had been fixed, we ran composer install again, but it didn't pick up that there was anything to be done.

What we found, even though the patch had failed, "patches_applied" had still been written in /vendor/composer/installed.json.

Removing those lines from installed.json, and re-running install, then correctly applied the patch. So it seems like even though exit on failure occurred, installed.json shouldn't have been updated. 

This is using version 1.6.7.

**Comment by cweagans** [comment]
Thanks a lot for the info! This probably explains some of the funky behavior that people have been seeing. This is super super helpful!

**Comment by cweagans** [comment]
This doesn't happen in `main` anymore.
