### ISSUE TITLE
Invalid option --no-backup-if-mismatch

### ISSUE THREAD

**Issue by hp-gfz** [cweagans/composer-patches#308]
patch '-p1' --no-backup-if-mismatch -d '/data/webcontent/vhosts/...

`Executing command (CWD): patch '-p1' --no-backup-if-mismatch -d '/data/webcontent/vhosts/...`
`patch: Invalid options.`
`patch: Usage:   patch [-blNR] [-c|-e|-n] [-d dir] [-D define] [-i patchfile]\
              [-o outfile] [-p num] [-r rejectfile] [file]
`

Oracle Solaris 11.4 X86
Copyright (c) 1983, 2020, Oracle and/or its affiliates.  All rights reserved.
Assembled 03 March 2020

**Comment by cweagans** [comment]
Duplicate: https://github.com/cweagans/composer-patches/issues/182
