### ISSUE TITLE
Make compatible with Composer 2

### ISSUE THREAD

**Issue by balsama** [cweagans/composer-patches#313]
Drupal aims to be compatible with Composer 2. See [Issue #3126566](https://www.drupal.org/project/drupal/issues/3126566).

As one of the most widely used plugins in Drupal, we should aim to make this plugin compatible with Composer 2 too.

**Comment by cweagans** [comment]
see also https://github.com/cweagans/composer-patches/pull/309

definitely in favor of this.

**Comment by balsama** [comment]
Oh dang. I missed that when I searched for an existing issue because I wasn't searching PRs (shakes fist at github defaults).

Perhaps we should leave this open then for others who might do the same. Thanks.

**Comment by mxr576** [comment]
When do you plan to release a new version with Composer 2.x support? As I can see it is only available in `master` yet.

**Comment by mxr576** [comment]
Hm, and why `master` is not the alias of `1.x-dev`? :thinking: 
https://packagist.org/packages/cweagans/composer-patches#1.x-dev
https://packagist.org/packages/cweagans/composer-patches#dev-master

**Comment by NetStorm84** [comment]
I would also like compatibility with Composer 2. Do we have an idea when this is likely to happen?

**Comment by hussainweb** [comment]
I created a PR #321 to add support for Composer 2 to the 1.x branch. It's basically a cherry-pick from #309 and then changes to `composer.lock` (which I was not sure about).

**Comment by danepowell** [comment]
If I'm not mistaken this was added in https://github.com/cweagans/composer-patches/pull/321

Can we get a new stable release so end users can start using Composer 2?

**Comment by hussainweb** [comment]
@danepowell, we would also need #330 to go in before this works with composer 2.

**Comment by clxmstaab** [comment]
you could already beta-test composer v2 support with a constraint like

`"cweagans/composer-patches": "1.x-dev as 1.6.8-dev",`

one issue we ran into when using the plugin with composer-v2 is

```
Fatal error: Uncaught Error: Call to undefined method Composer\DependencyResolver\Operation\InstallOperation::getJobType() in /home/runner/work/daiber/daiber/vendor/cweagans/composer-patches/src/Patches.php:179
Stack trace:
#0 [internal function]: cweagans\Composer\Patches->gatherPatches()
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(165): call_user_func()
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(118): Composer\EventDispatcher\EventDispatcher->doDispatch()
#3 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(368): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent()
#4 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(309): Composer\Installer\InstallationManager->executeBatch()
#5 phar:///usr/local/bin/composer/src/Composer/Installer.php(711): Composer\Installer\InstallationManager->execute()
#6 phar:///usr/local/bin/composer/src/Composer/Installer.php(252): Composer\Installer in /home/runner/work/daiber/daiber/vendor/cweagans/composer-patches/src/Patches.php on line 179
```

**Comment by markdorison** [comment]
@clxmstaab I believe that issue is addressed in PR #330.

**Comment by balsama** [comment]
#330 was merged into 1.x: ae02121445ad75f4eaff800cc532b5e6233e2ddf

**Comment by balsama** [comment]
As of [1.7.0](https://github.com/cweagans/composer-patches/releases/tag/1.7.0), this is fixed. Thanks!
