### ISSUE TITLE
Can not apply patch Skipping when try to update drupal core

### ISSUE THREAD

**Issue by Prekshapatel** [cweagans/composer-patches#314]
I have a Could not apply patch! Skipping. issue while trying to update the drupal core. That patch is mentioned in GOVCMS installation profile composer.json. Issue is patch is already applied for panelizer module and auto generated in (modules/contrib/panelizer/PATCHES.txt) . And there is a project composer file which is outside docroot using which I am trying to update drupal core. There is another patch mentioned in project's composer.json file for the panelizer module. So whenever I try to update the drupal core, panelizer module is getting deleted and trying to apply both the patches one mentioned in GOVCMS composer.json and one mentioned in project's composer.json file. I tried to remove the patch mentioned in GOVCMS composer.json file but still the issue is there.

Can any one tell me how could I remove the patch completely from GOVCMS composer.json, auto generated by cweagans/composer-patches in modules/contrib/panelizer/PATCHES.txt etc?

**Comment by cweagans** [comment]
This doesn't happen in `main` anymore.
