### ISSUE TITLE
Master: Patches are not being installed from dependencies

### ISSUE THREAD

**Issue by mxr576** [cweagans/composer-patches#322]
Composer 2 support was added to master with #309. I am trying to use that on our projects but I have just noticed that patches from dependencies are not being installed, even if `"enable-patching": true,` is set.

The issue seems unrelated to #309, it looks like that was broken even before that.

Related: #313

**Comment by cweagans** [comment]
https://github.com/cweagans/composer-patches/pull/267

**Comment by mxr576** [comment]
Ahh, I see... Thanks for the info. I understand the security implications of this, but we had a metapackage that installed necessary patches on projects that we worked on. Now, with the new PatchResolver approach, we have to write our own plugin to make this work again.

**Comment by cweagans** [comment]
That's true. I wouldn't recommend using master for anything important right now though. Use 1.x (which still includes this functionality).

**Comment by cweagans** [comment]
Also, I'm planning on writing the plugin that does this as part of the 2.x release series, but it's just not important to the core functionality of this plugin right now.
