### ISSUE TITLE
Requires GNU patch 2.7 for correct behavior, but `composer-patches` does not warn the user about this!

### ISSUE THREAD

**Issue by wimleers** [cweagans/composer-patches#326]
> @cweagans holy shit, the need for `brew install gpatch` took me many hours to figure out, because for a particular project TravisCI builds were succeeding but local builds were failing. 😬  Can we make `cweagans/composer-patches` detect the `patch` version, and explicitly warn the user that any version below 2.7 may result in silent failures?

_Originally posted by @wimleers in https://github.com/cweagans/composer-patches/issues/172#issuecomment-674860594_

The solution:

> `brew install gpatch` (you'll need Homebrew installed for that to work (https://brew.sh))

_Originally posted by @cweagans in https://github.com/cweagans/composer-patches/issues/172#issuecomment-587147692_

**Comment by andypost** [comment]
Warning could lead to faq wiki page instead of patch build detection

**Comment by cweagans** [comment]
Definitely not opposed to a warning here if there's a reliable way to detect GNU Patch vs whatever macOS ships with.

**Comment by wimleers** [comment]
This is _still_ a problem. A colleague of mine wasted another hour on this.

To answer your question about detecting GNU patch:
```
$ which patch
/usr/local/bin/patch
$ /usr/bin/patch --version
patch 2.5.8
Copyright (C) 1988 Larry Wall
Copyright (C) 2002 Free Software Foundation, Inc.

This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of this program
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

written by Larry Wall and Paul Eggert
$ /usr/local/bin/patch --version
GNU patch 2.7.6
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert
```

→ I am pretty sure that you could do something like `preg_match('/^GNU patch/', …)` on the output of `patch --version`.

**Comment by joejoseph00** [comment]
Some colleagues are using brew ( I don't )

Here's the solution:

```
brew install gpatch;
brew link gpatch --force --overwrite;
```

Then restart terminal or reboot, try again, patch version should show up as 2.7.6

**Comment by marclaporte** [comment]
Related: https://github.com/cweagans/composer-patches/issues/262

**Comment by mfb** [comment]
Please review the PR @ #402 where we try to get the non-GNU version of patch working

**Comment by danepowell** [comment]
Can someone please provide a minimum failing example for this issue (i.e. a composer.json with failing patch)? I use the stock patch utility with Ventura and have not had any problems applying patches. I only see problems if I specify the wrong patch level, which is to be expected.

**Comment by cweagans** [comment]
Let's just close this. #447 has explicit support and detection for different versions of patch. The behavior in 2.x is going to be pretty different: the goal is to get the patch applied, and the mechanism for actually performing that work doesn't matter as much. As long as there is _a_ usable mechanism for applying a patch, the patch should be applied.

**Comment by joejoseph00** [comment]
@cweagans 

> Let's just close this. #447 has explicit support and detection for different versions of patch. The behavior in 2.x is going to be pretty different: the goal is to get the patch applied, and the mechanism for actually performing that work doesn't matter as much. As long as there is _a_ usable mechanism for applying a patch, the patch should be applied.

What I've noticed is colleagues using MacintApples are using brew and on the MacintApple the version of patch is an older version that has problems applying patches that move files around.  Test this by writing a patch that moves the same file from one folder to another.

Example: ```

git mv README.txt src/.
git diff HEAD > MacintAppleChokesByDefault.patch;
```
include this patch with your project and ask a MacintApple person to run the composer install.  

Unless they upgrade to use gpatch version 1.7.6 their system will fail to patch.

**Comment by joejoseph00** [comment]
before patch version:
`patch --version;`

output might look something like `2.0-12u11-Apple`  this version is unable to move files

To fix MacintApple brew environments use the following commands:
```
brew install gpatch;
brew link gpatch --force --overwrite;
```

after upgrading the command  `patch --version` should output `2.7.6`

**Comment by cweagans** [comment]
In that scenario (even in 1.x), Git should be able to apply the patch properly before it ever gets to `patch`, right? I've made a note to add a test for this scenario.

**Comment by joejoseph00** [comment]
cweagans, yes that is true but I'm not sure how to make git behave like patch , where patch applies to the current folder but git applies to the root respository which is not predictable.  Not only that, composer can include some git repos and other projects that are not git repos.

**Comment by cweagans** [comment]
Do you have `"config": {"preferred-install": "source"},` in your composer.json? I recommend that in the [readme](https://github.com/cweagans/composer-patches/tree/1.x#usage) specifically so that there is a higher chance of being able to use git for patching. Even so, my intent with 2.x is that the specific mechanism for applying patches shouldn't matter. If there aren't any suitable mechanisms available, the plugin will make noise about not being able to apply the patch.

One other idea that I've been kicking around is to distribute a version of patch compiled like [this](https://justine.lol/ape.html) so that there is a valid patcher no matter what. That might not be 2.0.0 though (and may not even be in the core plugin).

**Comment by joejoseph00** [comment]
@cweagans  no I don't have that entry

I have this instead:

```
  "config": {
      "allow-plugins": {
        "composer/installers": true,
        "cweagans/composer-patches": true,
        "oomphinc/composer-installers-extender": true,
        "drupal/console-extend-plugin": true,
        "drupal/core-composer-scaffold": true,
        "dealerdirect/phpcodesniffer-composer-installer": true
      }
  }
```

**Comment by joejoseph00** [comment]
ok I'll add that config option and try it out.  We're using cweagans version 1.x

```
  "config": {
    "preferred-install": "source"
  },
```

**Comment by joejoseph00** [comment]
```
  "config": {
      "allow-plugins": {
       "preferred-install": "source",
        "composer/installers": true,
        "cweagans/composer-patches": true,
        "oomphinc/composer-installers-extender": true,
        "drupal/console-extend-plugin": true,
        "drupal/core-composer-scaffold": true,
        "dealerdirect/phpcodesniffer-composer-installer": true
      }
  }
```

**Comment by joejoseph00** [comment]
@cweagans  wow facinating link you shared https://justine.lol/ape.html

this would be really cool to have a single executable do everything.  With that said, windows filesystems has a real tough time with Linux like symlinks but for everything else it could work.

**Comment by cweagans** [comment]
> After adding it will look like this.
> 
> 
> 
> ```
> 
>   "config": {
> 
>       "allow-plugins": {
> 
>         "preferred-install": "source",
> 
>         "composer/installers": true,
> 
>         "cweagans/composer-patches": true,
> 
>         "oomphinc/composer-installers-extender": true,
> 
>         "drupal/console-extend-plugin": true,
> 
>         "drupal/core-composer-scaffold": true,
> 
>         "dealerdirect/phpcodesniffer-composer-installer": true
> 
>       }
> 
>   }
> 
> ```

Preferred-install should be one level up (a sibling of allow-plugins).

**Comment by weitzman** [comment]
Just got bitten by this. Thanks for posting the brew solution

**Comment by mr-m0nst3r** [comment]
`brew link gnu-getopt --force` solved
