### ISSUE TITLE
Better error message if patches do not apply because "patch" binary is missing.

### ISSUE THREAD

**Issue by grichards** [cweagans/composer-patches#329]
Hi there!

I was pulling my hair out tonight (lie, I'm already bald)... because I got a generic "Could not apply patch" error message trying to apply the Magento 2.3.4 PayFlow Pro / SameSite patch.... in PROD, but not in DEV.

Took me a couple hours to realize that patch wasn't installed on the server (actually, I didn't realize it... my CTO discovered it for me after I told him I was pulling my hair out).

He suggested that a more descriptive error message like "patch not found" would have been helpful.

Is that a good idea? If a binary dependency on the server is expected and not found, can this library be more informative?

Thanks!
Gabe

**Comment by cweagans** [comment]
Yeah, absolutely. Are you intending to submit a PR for this?

**Comment by grichards** [comment]
Hello @cweagans, thanks for the reply.

Unfortunately not... my lame excuse is lack of time, and I'll spare you the details.

At least I hope my suggestion, if implemented, will be helpful to save someone else time in the future.

Gabe

**Comment by Renrhaf** [comment]
Thanks, this one helped me debug this issue on my Docker image.

**Comment by cjohansson** [comment]
Same thing here, thanks for creating this issue

**Comment by marclaporte** [comment]
Related: https://github.com/cweagans/composer-patches/issues/262

**Comment by cweagans** [comment]
`main` works differently now. There has to be at least _some_ patch mechanism available, but `patch` is no longer specifically required. If there aren't any usable patchers, an exception will be thrown.
