### ISSUE TITLE
Trying to work with Drupal 9.07

### ISSUE THREAD

**Issue by criley** [cweagans/composer-patches#335]
I have an issue where when the patch contains the information needed to allow for Drupal 9 such as adding:

core_version_requirement: ^8 || ^9 

the patch never happens and instead I am presented with the:

Can only install one of: drupal/core[8.4.0, 9.0.7]. messages

How can I get around this or am I stuck downloading the module manually and patching it manually?

Thanks in advance.

**Comment by anotherjames** [comment]
@criley see https://www.computerminds.co.uk/articles/apply-drupal-9-compatibility-patches-composer - you have to override the package compatibility metadata so that this plugin gets chance to apply the necessary patch.
