### ISSUE TITLE
Disable patches of subpackages

### ISSUE THREAD

**Issue by freshp** [cweagans/composer-patches#336]
Hey,

is there any way to prevent executing patches from sub-packages, but allow executing the given patch from the main project composer json?

thank you in advance.

**Example:** 

* I need to execute the example patch, but the yii packages have phpunit patch I dont want to execute, because I dont want to use phpunit v4
```js
{
    "require": {
        "yidas/yii2-composer-bower-skip": "~2.0.13",
        "cweagans/composer-patches": "~1.0",
        "yiisoft/yii2-authclient": "^2.2",
        "yiisoft/yii2-debug": "^2.1",
        "phpunit/phpunit": "^9.2"
    },
    "extra": {
        "patches": {
            "bower-asset/bootstrap-table": {
                "exampe patch": "some patch location"
            }
        }
    }
}
```

**Comment by cweagans** [comment]
There's no way to do that in 1.x, but `main` doesn't resolve patches from dependencies at all.
