### ISSUE TITLE
Patching Drupal 7 possible?

### ISSUE THREAD

**Issue by gitressa** [cweagans/composer-patches#345]
Currently, [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) looks like the best choice for Composer-based Drupal 7 projects, since [drupal/recommended-project](https://github.com/drupal/recommended-project) seems to only support Drupal 8 and Drupal 9.

Will [cweagans/composer-patches](https://github.com/cweagans/composer-patches) work for a Composer-based Drupal 7 project, together with [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project)?

**Comment by cweagans** [comment]
Anything that can be installed through composer can be patched with this plugin :)

**Comment by gitressa** [comment]
You're right @cweagans :-) I think I was aiming at the wrong package (maybe `drupal/core`?) in stead of `drupal/drupal`.

The `composer-patches` plugin worked fine with a  Drupal 7 site based on [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project), adding this under `patches` section in `composer.json`:
```
"drupal/drupal": {
  "[D7] Rename Permissions tab to Roles and permissions #2323963": "https://www.drupal.org/files/issues/2018-07-27/2323963.patch"
}
```
In my opinion the `composer-patches` plugin ought to be included in [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) and [drupal/recommended-project](https://github.com/drupal/recommended-project).
