### ISSUE TITLE
Cache downloaded patches

### ISSUE THREAD

**Issue by cweagans** [cweagans/composer-patches#35]
Right now, all patches are downloaded unconditionally every time they're applied. We should download them once and store them in the Composer cache. If we store the SHA-1 of the patch in `composer.lock`, and then save the patch as `$sha1OfPatch.patch` in the cache dir, offline installs with patches are possible.

Obviously, this wouldn't need to happen for local patches - only ones where we'd normally download them.

**Comment by mustanggb** [comment]
This would be welcome.

**Comment by sminnee** [comment]
Would it be possible/desirable to inline the entirety of the patch into the composer.lock file itself? Then you would be able to run "composer update" on your local environment, and distribute your composer.lock file to other environments with more confidence of the patches integrity when `composer install` is run.

It would bloat out the length of composer.lock, but does that actually have any practical downside?

**Comment by cweagans** [comment]
`main` now caches patch downloads. It uses the global composer cache, so if you're already caching this in your builds to speed up `composer install`, it should Just Work :tm:

**Comment by mustanggb** [comment]
Haven't tested it yet, but great news.
