### ISSUE TITLE
Patches for different versions of dependency

### ISSUE THREAD

**Issue by podarok** [cweagans/composer-patches#351]
There is a need to support 2 patches for different versions of same dependency
Example https://github.com/ymcatwincities/openy/blob/8.x-2.x/composer.json#L69

Is there a way to include 2 patches and let composer decide which one is used for specific dependency's version?

**Comment by cweagans** [comment]
There is no way to do this currently. I'm not really excited about the idea of doing it either, as it complicates things for everyone to support an edge case. Any reason why two different versions _must_ be supported?

**Comment by podarok** [comment]
Reason - upgrade path when budget is low.
Upgrading core is more important than upgrading everything. So keeping old dependencies but never core gives some time improvements for the maintenance

**Comment by cweagans** [comment]
I understand the intent, but I think there are other approaches. For instance, can you pin the dependency to a specific version that works with both D8 and D9?

You could also potentially write a small composer plugin that modifies the list of patches after dependency resolution happens, but before patching occurs.

**Comment by danepowell** [comment]
Can you create a sub-package for your project that just requires Drupal Core and the relevant patches? Then have a separate branch of this module for each version of Drupal core. And have a loose constraint on this subpackage in your main project.

**Comment by cweagans** [comment]
Probably not going to do this, sorry.

**Comment by cweagans** [comment]
You can do this by extending composer patches. See the documentation. You'd want to write a Resolver and come up with some way to notate the version constraints. Definitely out of scope for the core plugin though.

**Comment by cweagans** [comment]
Also if you do this, let me me and we can add it to a docs page linking to other plugins that extend this one.
