### ISSUE TITLE
Support patches in custom modules

### ISSUE THREAD

**Issue by geek-merlin** [cweagans/composer-patches#352]
Often i develop modules in modules/custom, to make them a separate package later. In the meantime, patches for that thing mess up in the project composer.json.

I thought about having one patches-file per custom module, but "patches-file" only allows 1 file.

The imho best option for this use-case imho would be (the option of) something like:
```
"include-composer-json-patterns": ["modules/custom/comoser.json"],
"patches-file-patterns: ["modules/custom/patches.json"], 
```

**Comment by cweagans** [comment]
Probably not going to do this, sorry. In `main`, you may be able to do this programmatically though -- you can write your own patch resolver. Docs for how to do that are Coming Soon :tm:.
