### ISSUE TITLE
patchLevel missing in master?

### ISSUE THREAD

**Issue by danepowell** [cweagans/composer-patches#357]
The patchLevel feature was merged to 1.x a few years ago, and documentation was also added to the README, but it looks like neither commit made it to master.

Is this an oversight, or do I not understand the branching structure? I'd expected anything in 1.x to also be in master, unless it was specifically deprecated.

**Comment by cweagans** [comment]
`master` is a rewrite. It'll be included eventually. I don't recommend using `master` for anything you care about at the moment.

**Comment by danepowell** [comment]
Thanks, sounds like a misunderstanding on my part and you are already tracking this yourself, so I'll close this.
