### ISSUE TITLE
COMPOSER_EXIT_ON_PATCH_FAILURE doesn't do anything

### ISSUE THREAD

**Issue by grasmash** [cweagans/composer-patches#359]
I've searched through the code and it doesn't appear to be used at all?

**Comment by cweagans** [comment]
1.x: https://github.com/cweagans/composer-patches/blob/1.x/src/Patches.php#L280

It won't be present in `master` directly -- the configuration bits have been split off into https://github.com/cweagans/composer-configurable-plugin (ref: https://github.com/cweagans/composer-patches/blob/master/src/Plugin/Patches.php#L97 and https://github.com/cweagans/composer-configurable-plugin/blob/master/src/ConfigurablePlugin.php#L99-L113 -- it looks like the environment var name for `master` is `COMPOSER_PATCHES_EXIT_ON_PATCH_FAILURE`).

**Comment by grasmash** [comment]
Thank you. I've yet to validate that COMPOSER_PATCHES_EXIT_ON_PATCH_FAILURE, but I'll do some testing.

**Comment by bobbygryzynger** [comment]
I'm seeing that `COMPOSER_EXIT_ON_PATCH_FAILURE` is used in the latest release (1.7.2): https://github.com/cweagans/composer-patches/blob/1.7.2/src/Patches.php#L285
