### ISSUE TITLE
composer.patches.json is ignored in dependencies/nested packages...

### ISSUE THREAD

**Issue by metalbote** [cweagans/composer-patches#361]
I have a project `composer.json` with following relevant structure:
```json
{
    "require": {
        "composer/installers": "~1.0 || ~2.0",
        "cweagans/composer-patches": "^1.7",
        "my_vendor/my_distro_package": ^1.0
    },
    "extra": {
        "enable-patching": true,
        "composer-exit-on-patch-failure": true
    }
}
```
and the package `my_vendor/my_distro_package` `composer.json`:
```json
{
    "name": "my_vendor/my_distro_package",
    "require": {
        "composer/installers": "~1.0 || ~2.0",
        "cweagans/composer-patches": "^1.7",
        [...]
    },
    "extra": {
        "enable-patching": true,
        "composer-exit-on-patch-failure": true,
        "patchLevel": {
            "drupal/core": "-p2"
        },
        "patches-file": "composer.patches.json"
    }
}
```
On composer update everything seems ok, but none of the patches in `my_vendor/my_distro_package` are applied. If I copy them  into the `my_vendor/my_distro_package` `composer.json` under key `extra.patches` everything is applied as expected.

Is this a bug or is something wrong with the  `"patches-file": "composer.patches.json"`? path description? It is next to composer.json in `my_vendor/my_distro_package`

**Comment by cweagans** [comment]
`main` doesn't resolve patches from dependencies anymore.
