### ISSUE TITLE
One for the "Wish List"...

### ISSUE THREAD

**Issue by begrafx** [cweagans/composer-patches#362]
I am presuming that this

`$ ddev composer update
Gathering patches for root package.
Removing package drupal/core so that it can be re-installed and re-patched.
  - Removing drupal/core (9.2.0-beta2)
Deleting web/core - deleted
Loading composer repositories with package information
Updating dependencies                                 
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/core (9.2.0-beta2): Extracting archive
  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/2020-12-13/1356276-633-by-mpotter-balsama-phenaproxima-9.1.0-9.2.x.patch (1356276 - Allow profiles to provide a base/parent profile and load them in the correct order)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2020-12-13/1356276-633-by-mpotter-balsama-phenaproxima-9.1.0-9.2.x.patch

                                                                               
  [Exception]                                                                  
  Cannot apply patch 1356276 - Allow profiles to provide a base/parent profil  
  e and load them in the correct order (https://www.drupal.org/files/issues/2  
  020-12-13/1356276-633-by-mpotter-balsama-phenaproxima-9.1.0-9.2.x.patch)!    
                                                                               

update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

composer [update] failed, composer command failed: exit status 1. stderr=`

is happening because that patch has already been applied. But I wish that there were some way of telling for sure... whether once the patch has been applied, that patch could be flagged, or removed from the composer.json list, or a log kept somewhere easily accessible, that shows what patches have been applied, and a nice visible message informing/reminding the admin who is running the update that the patch has been applied, so it can be removed from the JSON file.

**Comment by cweagans** [comment]
This isn't something that the plugin is going to be able to do. There's not really a difference between a bad patch and one that has already been applied as far as the plugin sees it, so this kind of detection wouldn't be possible without somehow inspecting various version control systems and issue trackers. Not really something I'd want to handle in this plugin. Maybe somebody more ambitious wants to handle it in a third party plugin though -- `main` emits events before patches are applied, so it would be possible for somebody to hook in, reach out to drupal.org, figure out whether or not the patch has been applied, and alert accordingly.
