### ISSUE TITLE
README needs updating in reguards netresearch/composer-patches-plugin

### ISSUE THREAD

**Issue by generalredneck** [cweagans/composer-patches#37]
See composer-patches-plugins [updated documentation](https://github.com/netresearch/composer-patches-plugin#user-content-provide-patches-by-package-only)

**Comment by cweagans** [comment]
Thanks for the heads up. I'll take a look.

**Comment by generalredneck** [comment]
still complicated in the sense that you got to provide your own "patches" package, but they don't make you specify version constraints anymore. The biggest challenge that most people I work with have is the fact that your "patches package" you create gets cached and makes for some shitty patching experience...

**Comment by cweagans** [comment]
I'm probably just going to remove the reference altogether. It's not worth keeping up with what other packages are doing.
