### ISSUE TITLE
[question] Patch falls on its face on windows encoded file

### ISSUE THREAD

**Issue by patrick-leb** [cweagans/composer-patches#372]
Hi Everyone,

My patch is the simplest thing, commenting out one line of code. However the source is windows encoded (^M carriage return)

Patch is unable to apply it.

I'm looking for ideas on how to get around that problem. Thanks!

Edit:
I'm creating the patches like that:
```
git format-patch --ignore-space-change -1 HEAD 
```

**Comment by cweagans** [comment]
'dos2unix' should be available with pretty much every Linux distro. Maybe it's in Git Bash and/or WSL.

**Comment by patrick-leb** [comment]
Thank you! - does composer-patch run after post_install_cmd ?

**Comment by patrick-leb** [comment]
OMG I never noticed the `pre-patch-apply` event! genius! it worked perfectly.  If someone arrives here by googling:

```
  "scripts": {
	"pre-patch-apply": ["find path/to/files/windows/encoded  -type f -print0 | xargs -0 dos2unix"]
  },
```
will do the trick!

**Comment by patrick-leb** [comment]
@cweagans It's not the end of the world but I thought I'd ask

```
  "scripts": {
	"pre-patch-apply": ["find path/to/files/windows/encoded  -type f -print0 | xargs -0 dos2unix"]
  },
```

This will run on every single patch being applied. I see the event gets the package:
````php
$this->eventDispatcher->dispatch(NULL, new PatchEvent(PatchEvents::PRE_PATCH_APPLY, $package, $url, $description));
````

Is it possible to run different `pre-patch-apply` depending on the package?

**Comment by cweagans** [comment]
You'd have to write a plug-in for that. You could also run that on one of the default composer events fired less frequently (e.g. https://getcomposer.org/doc/articles/scripts.md#command-events)

**Comment by patrick-leb** [comment]
I tried post-update-cmd but the plugin runs before that. I'm not sure what else I could use.

**Comment by cweagans** [comment]
`pre-update-cmd`?

**Comment by patrick-leb** [comment]
`pre-update-cmd` runs before the packages get extracted, therefore I can't manipulate the freshly installed code. Would it be possible to add maybe 2 events, like `pre-patch-cmd` and `post-patch-cmd` that run once before the patching loop and once after the patching loop? It could be useful I feel.

**Comment by cweagans** [comment]
Yeah, it can get kind of messy unfortunately. I think writing a plugin is probably your best bet if you want to do it this way. An even better path forward would be to ensure that your patches have been `dos2unix`'d beforehand. Converting line endings at the time where patches are being applied (IMO) is a sign that something has gone wrong in the process before that point.

**Comment by patrick-leb** [comment]
Unfortunately, I have zero power on how upstream packages their release :( I agree it's sucky they don't code with normal CR but it's out of my hands lol.
