### ISSUE TITLE
Composer patches is not installing the dependency after removing it for patch it?

### ISSUE THREAD

**Issue by isholgueras** [cweagans/composer-patches#373]
I've realized about this issue a few days ago and I don't know if this is a composer issue or a composer-patches issue. I've also tried to find a similar issue without luck so here is the issue.

I'm upgrading to composer 2 (2.1.3) a Drupal 8 project, and I've realized that our tests failed because drupal/core (and some other dependencies) are not present. After connecting into the machine and execute `composer install` these packages were installed and everything worked well.

And after many back and forth, I've realized in my local about composer removing a dependency to be patched but not installing it. Here is the screenshot:
![image](https://user-images.githubusercontent.com/140742/122971382-48cb5000-d38f-11eb-9065-a67ff4b82fb4.png)

The versions are Composer 2.1.3 and composer-patches:1.7.

If there is something I can do to help explain it better, let me know.

**Comment by YesCT** [comment]
https://github.com/cweagans/composer-patches/releases/tag/1.7.1

Mentions a fix for something that sounds like the same issue.

**Comment by isholgueras** [comment]
Oh! Thanks @YesCT ! Yes, it seems the same issue.

I think it can be closed then.
