### ISSUE TITLE
"composer install" needs to be called twice when a dependency adds a patch

### ISSUE THREAD

**Issue by prudloff-insite** [cweagans/composer-patches#376]
Say we have a package A that declares patches for package B.

If we install a new version of package A that contains new patches for package B, here is what happens when we deploy on our CI:
* At the first `composer install`, the new version of package A is installed but no new patch is applied.
* If we launch `composer install` again, the new patches are applied to package B.

I suppose this happens because the patches are collected before the package is updated.

**Comment by briantschu** [comment]
I was experiencing this issue on 1.7.0 but updating this package to 1.7.1 resolved it!

**Comment by prudloff-insite** [comment]
We were indeed using 1.7.0. I tried using 1.7.1 but I can still reproduce the issue.

**Comment by cweagans** [comment]
This doesn't happen in `main` anymore.
