### ISSUE TITLE
Patches Ignore Enhancements

### ISSUE THREAD

**Issue by wilroboly** [cweagans/composer-patches#378]
As noted in the PR #377, I've coded up a set of modifications to the plugin to allow for some sub-package flexibility. This ensures a better orchestration of patches and ignored patches across a project and its required packages. My hope is that it sparks a few ideas or is integrated into the overall plugin. 

Thank you!

**Comment by cweagans** [comment]
`main` doesn't resolve patches from dependencies anymore, so `patches-ignore` has been removed.
