### ISSUE TITLE
Multiple packages use the same patch throw an array to string exception

### ISSUE THREAD

**Issue by deviantintegral** [cweagans/composer-patches#38]
If I set up package A with a patch, and package B with the same patch, and set package A to require B, the URLs are merged into an array. This causes composer install to bail with an array to string conversion.

![www 2016-04-12 15-21-14](https://cloud.githubusercontent.com/assets/255023/14472728/7ca9a70a-00c2-11e6-8bfe-8c1315c506ac.png)

**Comment by cweagans** [comment]
Good find! That's definitely not the desired behavior :)

**Comment by grasmash** [comment]
This is caused by `$this->patches = array_merge_recursive($this->patches, $extra['patches']);`
in Patches.php.

**Comment by lacun** [comment]
Hello,
On a project, the array to string conversion problem occurs when calling composer install with already installed patches.
It's caused by the remaining call to `$this->patches = array_merge_recursive($this->patches, $extra['patches']);`
