### ISSUE TITLE
Add support for patchLevel being defined in external patch file

### ISSUE THREAD

**Issue by jurgenhaas** [cweagans/composer-patches#380]
The external patch file come handy when you want to use a shared list of patch among multiple projects. We keep the external patch file in a public file and refer to that with the `"patches-file": "https://repo/d9.json"` in the extra section of the project roots.

As it is very likely that for the same list of patches the setting for the `patchLevel` is always the same too, it would be nice if the external patch file could also contain that setting, e.g.:

```
{
  "patchLevel": {
    "drupal/core": "-p2"
  },
  "patches": {
    "drupal/core": {
      "Some patch": "https://www.drupal.org/files/issues/2021-08-30/d8-email-tld-requirement-97.patch"
    }
  }
}
```

Tried that right now but that patch level settings is ignored when provided in the external file.

**Comment by cweagans** [comment]
I've made a note to make the default configurable for a given package in 2.x. I probably won't pull the setting from the patches file though -- configuration and patch definitions are separate things in 2.x.
