### ISSUE TITLE
Provide patches-ignore from within main composer.json

### ISSUE THREAD

**Issue by handmade-medium** [cweagans/composer-patches#382]
I am developing a project with a large installed package (Drupal Core) and several patches applied against that package.
In turn, I have several other packages (contrib modules) that declare the large package as a dependency.
Every time I make updates to the packages that declare my large package as a dependency, it is deleted and reloaded.
But it does not need to be updated.

My proposal is to enable the same declaration that is supported in individual packages, enabled for the root package, and temporarily suspend patching for execution of composer.

This way, a developer could run this command to disable patching:
`composer config extra.patches-ignore true `

And to re-enable:
`composer config extra.patches-ignore false `

**Comment by cweagans** [comment]
`main` doesn't resolve patches from dependencies anymore.
