### ISSUE TITLE
Technical question: Passing hash from patches array into package information for installer?

### ISSUE THREAD

**Issue by ghost** [cweagans/composer-patches#383]
I'm using cweagans/composer-patches in combination with https://github.com/iwink/composer-global-installer. That installer changes the installpath to install packages in a global location per version.

But when one projects uses a patch it can overwrite the package of another project. To avoid that I'm looking for a way that the installer can check if a package has patches applied (preferably by a hash). But I'm not sure how to pass this information from a PRE_PACKAGE_INSTALL event to the installer.

If somehow cweagans/composer-patches can make that information available to the installer I can install a package under /vendorname/packagename/packageversion/patcheshash and each package could get installed separately.

@cweagans do you have any ideas on how that information could be made available to installers?

**Comment by cweagans** [comment]
I'd be surprised if this can ever work. `composer-global-installer` would need some way to differentiate between different installations (or make a dependency ineligible for global installation if it's patched). You may be able to figure something out with the events and capabilities in `main` though.
