### ISSUE TITLE
Cannot apply patch

### ISSUE THREAD

**Issue by factormaarten** [cweagans/composer-patches#385]
Hello,

For some reason I'm getting the error `Could not apply patch! Skipping. The error was: Cannot apply patch patches/webonyx-graphql-php-src-error-formattederror-php.patch`.

```
    "extra": {
      "patches": {
        "webonyx/graphql-php": [
          "patches/webonyx-graphql-php-src-error-formattederror-php.patch"
        ]
      }
    }
```
.patch file
```
--- /dev/null
+++ ../src/Error/FormattedError.php
@@ -155,6 +155,18 @@
     }
 
     /**
+     * Check if string is json
+     *
+     * @param $string
+     * @return bool
+     */
+    public static function isJson(string $value): bool
+    {
+        \json_decode($value);
+        return \json_last_error() === JSON_ERROR_NONE;
+    }
+
+    /**
      * Standard GraphQL error formatter. Converts any exception to array
      * conforming to GraphQL spec.
      *
@@ -176,8 +188,13 @@
         $internalErrorMessage = $internalErrorMessage ?? self::$internalErrorMessage;
 
         if ($exception instanceof ClientAware) {
+            $message = $exception->getMessage();
             $formattedError = [
-                'message'  => $exception->isClientSafe() ? $exception->getMessage() : $internalErrorMessage,
+                'message'  => $exception->isClientSafe()
+                    ? self::isJson($message)
+                        ? \json_decode($message)
+                        : $message
+                    : $internalErrorMessage,
                 'extensions' => [
                     'category' => $exception->getCategory(),
                 ],
```
I can't see what I'm doing wrong. Can anyone help?

**Comment by cweagans** [comment]
It looks like the patch doesn't apply cleanly. Try cloning the repo for `webonyx/graphql-php`, copy your patch into that dir, and then run `git apply yourpatch.patch`. See what fails and go from there. The patch might need to be re-rolled to get it to work.

**Comment by factormaarten** [comment]
I'm unfortunately getting this for each patch I perform, now for another one too:
error: new file src/Ratchet/Server/IoServer.php depends on old contents

I'm new to patching and have no clue what this means. How can I resolve this?
And does it matter that I'm running my PHP in docker?

**Comment by cweagans** [comment]
Docker shouldn't make a difference. I've never seen that particular error before so I'm afraid I can't be much help there.

Generally, I recommend reading through https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal, particularly the following:

* https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/making-a-patch
* https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/applying-a-patch-in-a-feature-branch
* https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/rerolling-patches
* https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/command-only-full-patch-workflow

Those all reference Drupal, but they're applicable to most patch-based workflows.
