### ISSUE TITLE
Question: Is there anyway to trigger apply patches without doing it automatically (using a script)

### ISSUE THREAD

**Issue by SirMishaa** [cweagans/composer-patches#386]
Hello there ! 

For some reason, I'd like to trigger to apply of patch using a script. 
But not automatically (when doing composer install), is that possible? 

Thank you!

**Comment by cweagans** [comment]
'''
cd path/to/package
curl https://example.com/foo.patch | git apply
# or:

curl https://example.com/foo.patch | patch -p1
#you may have to adjust the -p param depending on your patch and project

'''
