### ISSUE TITLE
Can't install with Composer 2.2 

### ISSUE THREAD

**Issue by zuernBernhard** [cweagans/composer-patches#387]
Hi, 

Composer 2.2 was released 3 hours ago. I have a cloud Deployment whre composer is installed via CURL in a Docker file during the build process. And on the last rebuilds composer install failed out of a sudden reproducable. 

```


200/200 [============================] 100%
--
957 | - Installing cweagans/composer-patches (1.7.1): Extracting archive
958 | For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
959 | You have until July 2022 to add the setting. Composer will then switch the default behavior to disallow all plugins.
960 | Plugin initialization failed (require(vendor/autoload.php): failed to open stream: No such file or directory), uninstalling plugin
961 | - Removing cweagans/composer-patches (1.7.1)
962 | Install of cweagans/composer-patches failed
963 |  
964 |  
965 | [ErrorException]
966 | require(vendor/autoload.php): failed to open stream: No such file or directory
967 |  
968 |  
969 | install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v\|vv\|vvv\|--verbose] [-o\|--optimize-autoloader] [-a\|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...
970 |  
971 | The command '/bin/sh -c composer install --prefer-dist' returned a non-zero code: 1


```

Once downgraded to the last version by using : 

```
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin -- --filename=composer --version=2.1.14
```

Instead of 

```
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin -- --filename=composer 
```

it is working again.

**Comment by cweagans** [comment]
> 958 | For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins

Did you try this? Did it fix your build?

**Comment by zuernBernhard** [comment]
Yes I have it in the config section of composer json. No it did not work. Had to use composer 2.1

**Comment by cweagans** [comment]
Can you please post your complete composer.json somewhere? If you don't want it to be public, you can email it to me. me@cweagans.net

**Comment by StuartCreed** [comment]
I have the same issue. Composer install broken with composer v2.2. Works fine with composer v2.1.

**Comment by zuernBernhard** [comment]
`{
    "name": "drupal-composer/drupal-project",
    "description": "Project template for Drupal 8 projects with composer",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "composer/installers": "^1.2",
        "cweagans/composer-patches": "^1.6.5",
        "doctrine/cache": "^1",
        "drupal/aws_secrets_manager": "1.x-dev",
        "drupal/better_exposed_filters": "^5.0@beta",
        "drupal/cdn": "^3.3",
        "drupal/composer_deploy": "^1.3",
        "drupal/config_split": "^1.7",
        "drupal/console": "^1.0.2",
        "drupal/core": "^8.9",
        "drupal/core-composer-scaffold": "^8.9",
        "drupal/core-recommended": "*",
        "drupal/devel": "^4.x-dev",
        "drupal/devel_entity_updates": "^3.0",
        "drupal/entity": "^1.0",
        "drupal/entity_browser": "^2.1",
        "drupal/entity_usage": "^2.0@beta",
        "drupal/env_variables": "^2.1",
        "drupal/flag": "^4.0@alpha",
        "drupal/graphql": "3.x-dev",
        "drupal/graphql_flag": "^1.0@alpha",
        "drupal/health_check": "^1.1",
        "drupal/jwt": "1.0-beta3",
        "drupal/key": "^1.8",
        "drupal/linkit": "^5.0",
        "drupal/mentions": "^1.0@alpha",
        "drupal/moderation_note": "^1.0@beta",
        "drupal/openid_connect_windows_aad": "^1.1",
        "drupal/override_node_options": "^2.5",
        "drupal/paragraphs": "^1.9",
        "drupal/prepopulate": "^2.2",
        "drupal/readonly_field_widget": "^1.3",
        "drupal/redis": "^1.5",
        "drupal/remove_entity_untranslatable_field_validation": "^1.1",
        "drupal/replicate_ui": "^1.0",
        "drupal/s3fs": "3.x-dev",
        "drupal/scheduler": "^1.0",
        "drupal/ses_mailer": "^1.0@alpha",
        "drupal/swiftmailer": "^2.2",
        "drupal/ultimate_cron": "^2.0@alpha",
        "drupal/upgrade_status": "^3.13",
        "drupal/votingapi": "<=3.0-beta1",
        "drush/drush": "^9.0.0",
        "thenetworg/oauth2-azure": "v2.0.0.x-dev",
        "vlucas/phpdotenv": "^5",
        "webflo/drupal-finder": "^1.0.0",
        "webmozart/path-util": "^2.3"
    },
    "require-dev": {
        "drupal/admin_toolbar": "^2.0",
        "drupal/coder": "^8.3",
        "drupal/dev-dependencies": "^8.7",
        "drupal/permissions_filter": "^1.1"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "cweagans/composer-patches": true
        }
    },
    "autoload": {
        "classmap": [
            "scripts/composer/ScriptHandler.php"
        ],
        "files": ["load.environment.php"]
    },
    "scripts": {
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "pre-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "post-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ]
    },
    "extra": {
        "drupal-scaffold": {
            "locations": {
                "web-root": "./web"
            }
        },
        "patchLevel": {
            "drupal/core": "-p2"
        },
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/libraries/{$name}": ["type:drupal-library"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/Commands/{$name}": ["type:drupal-drush"]
        },
        "patches": {
            "drupal/graphql": {
                "HTTP 500 persistent queries like NodeQuery, @see Github Issue #940": "patches/drupal/graphql/graphql-github-940.patch"
            },
            "drupal/moderation_note": {
                "Moderation Note and Paragraphs, @see https://www.drupal.org/project/moderation_note/issues/2954753": "https://www.drupal.org/files/issues/2020-05-13/moderation-note-and-paragraphs-2954753-25.patch"
            }
        }
    }
}
`

**Comment by zuernBernhard** [comment]
[387-composer_json_and_lock.zip](https://github.com/cweagans/composer-patches/files/7771782/387-composer_json_and_lock.zip)

Here are composers.json and composer.lock where it failed for me.

**Comment by balazswmann** [comment]
I can confirm the issue as well with composer-patches 1.7.1 and Composer 2.2.4

**Comment by cweagans** [comment]
This appears to be fixed now.
