### ISSUE TITLE
CircleCI can't apply patches

### ISSUE THREAD

**Issue by iammati** [cweagans/composer-patches#389]
Just got CircleCI configured and noticed that my patches are not working on CircleCI.
![image](https://user-images.githubusercontent.com/41418763/148061214-f048cec7-5edb-4022-b054-b2083ad94a41.png)

Would I need to configure on composer-patches' side something or is it CircleCI specific?
Local (WSL2 + DDEV-Local) it works fine.

**Comment by cweagans** [comment]
It's probably an environment issue. Make sure CircleCI has GNU Patch installed (the plugin will use either `patch` or `git apply`). You may also need to try a fresh clone + `composer install` on your local machine, as it's possible that you have stale versions of dependencies locally.

**Comment by iammati** [comment]
Oh yeah, the GNU patch is not installed by the docker image I've been using. Will try to fork the image and install the missing package. Will update the issue as soon I got things running. Thanks!

**Comment by iammati** [comment]
Was missing the GNU Patch package. Thanks for that @cweagans :)
