### ISSUE TITLE
Patch command not found while mapped in PATH on Win10 

### ISSUE THREAD

**Issue by ganckal** [cweagans/composer-patches#390]
Hello, I am building my drupal 9.2 website on Wamp 3.2 (Windows 10) with composer, drush and Git without issues. Then I required ceweagans/composer-patch, but patches cannot be installed, neither with full url nor local reference. Error tells me "Could not apply patch!", and putting verbose: the' patch' command couldn't be found, so I added the location of the patch.exe in my user PATH env variable (at C:\Program Files\Git\usr\bin), but it doesn't work. I run out of ideas, maybe you have some for me :D Many thanks!

**Comment by rakeshf** [comment]
Install patch this https://cygwin.com/packages/summary/patch.html

**Comment by marclaporte** [comment]
Related: https://github.com/cweagans/composer-patches/issues/262

**Comment by cweagans** [comment]
`patch.exe` isn't what the plugin is looking for. It needs `patch`.
