### ISSUE TITLE
Call to undefined method Composer\Package\CompleteAliasPackage::setExtra()

### ISSUE THREAD

**Issue by liquidcms** [cweagans/composer-patches#394]
A few days ago i went to update a project and it caused composer errors that had me go and try updating composer from (i think) 2.1.7 to 2.2.5.

Since then i seem to get this error somewhat sporadically.. but usually. I have tried a few different things like removing vendor folder and .lock and doing an update. Sometimes this fixes but then as soon as i add/remove a patch, things are busted again.

Sometimes rm vendor and .lock doesnt fix it.

Going back to 2.1.14 doesnt help.

Going back to 2.0.11 doesnt help.

I am on Windows10 running in a gitbash window (which has always worked).

Fatal error: Uncaught Error: Call to undefined method Composer\Package\CompleteAliasPackage::setExtra() in E:\www\myssc\vendor\cweagans\composer-patches\src\Patches.php:330
Stack trace:
#0 [internal function]: cweagans\Composer\Patches->postInstall(Object(Composer\Installer\PackageEvent))
#1 phar://C:/Users/Peter/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(191): call_user_func(Array, Object(Composer\Installer\PackageEvent))
#2 phar://C:/Users/Peter/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(135): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Installer\PackageEvent))
#3 phar://C:/Users/Peter/AppData/Local/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php(461): Composer\EventDispatcher\EventDispatcher->dispatchPackageEvent('post-package-in...', true, Object(Composer\Repository\InstalledFilesystemRepository), Array, Object(Composer\DependencyResolver\Operation\InstallOpera in E:\www\myssc\vendor\cweagans\composer-patches\src\Patches.php on line 330

**Comment by cweagans** [comment]
This doesn't happen in `main`.
