### ISSUE TITLE
Fail when patches cannot be applied

### ISSUE THREAD

**Issue by bartfeenstra** [cweagans/composer-patches#40]
When a patch cannot be applied, the build simply continues with a warning being output. On automated systems, this is hard to catch. This is a critical issue, as these patches can be used to fix security problems, for instance. Instead, in case of failures, the process should exit with a non-zero error code.

**Comment by cweagans** [comment]
I'd be okay with a flag that controls this. This shouldn't be the default though. Not till 2.0.0 anyway.

**Comment by bartfeenstra** [comment]
I suppose you want the flag for BC reasons, but that does mean this plugin will continue to do the opposite of what it advertises whenever patches fail to apply (which is to apply patches). I'm afraid this will lead to a lot of time being spent by developers trying to find the causes of bugs in their sites or security issues, caused by patches not being applied.

**Comment by cweagans** [comment]
It hasn't been that much of a problem, as the plugin *does* already add some output saying that a patch can't be applied. The main thing is, I don't want to just change a behavior that has been in place since 1.0.0 and hope for the best. A flag is better here because users can opt-in to functionality that will be in 2.0.0 (and in 2.0.0, it'll be an opt-out). I would also not be opposed to some additional messaging at the end of `composer install` or `composer update` if there were any patches that couldn't be applied.

I would also say that before blindly dropping patches into your `composer.json` (*especially* if those are security patches), you should be sure that all the patches will apply in the order that you specify. I'd also say that it's probably much safer to just upgrade the release in the event of a security update, rather than just applying the security patch.

**Comment by cweagans** [comment]
Actually, looks like we already added the flag as an environment variable: https://github.com/cweagans/composer-patches/pull/31

2.0.0 should also clean up the config flags such that they can be specified in composer.json or as an env var, rather than having a weird mix of stuff.

**Comment by bartfeenstra** [comment]
I did not say security releases; I gave examples of problems the current behavior can cause, including those that compromise security.

Adding additional messages will still not solve this problem for automated builds. If a CLI tool does not exit with a non-zero code on failure, it basically fails to tell its executing shell about the failure, which means any non-human observer (build tools) will not be able to take the necessary precautions to prevent worse failures, such as deploying a broken system to production.

**Comment by cweagans** [comment]
That's fair, and I mostly agree with you. However, this still can't be the default behavior until 2.0.0 because semver. It's a BC break. The best we can do in the 1.x releases is more messaging and a flag to let you opt-in to a non-zero exit code.

**Comment by bartfeenstra** [comment]
Thanks for referring https://github.com/cweagans/composer-patches/pull/31! I'll give that a try for now. A composer.json `config` setting may be useful as well, so projects do not have to depend on manual setup or additional build scripts wrapping the `composer install` command.

**Comment by cweagans** [comment]
Agreed. PRs welcome :)

**Comment by Leksat** [comment]
Hello! Thanks for the cool plugin!
Please check #46 for the "composer-exit-on-patch-failure" config option.

**Comment by jhedstrom** [comment]
I'd like to see the default fail the build. We could add a flag to disable that for BC purposes, but I'd be surprised if there are folks out there that consider patches specified in their `composer.json` as optional, and would appreciate knowing exactly which patches fail (and knowing immediately, whether locally or on a CI).

**Comment by cweagans** [comment]
The default in 2.0.0 will be to fail when a patch cannot be applied. 1.x needs to default to success, unfortunately. I'm not willing to change that behavior in a minor release.

**Comment by jhedstrom** [comment]
Fair enough. Is there a milestone (or list of issues) required for 2.0.0? Happy to help if possible :)

**Comment by cweagans** [comment]
Well, not really :( There's a 2.x branch which has some pretty aggressive refactoring in progress, but I haven't had time to finish. It's a rewrite, more or less, with the goal of good test coverage + smaller pieces to work with.

**Comment by TravisCarden** [comment]
Is this an appropriate place to offer feedback for the new implementation? (I'll assume so.)

- Failing the build by default is great.
- It would also be helpful to get a list of patches that couldn't be applied _all together_ at the end of the command output. If you have very many patches, it can be easy for failures to get lost in the backscroll where they're tedious to collate and at risk of getting overlooked altogether.
- For that to be useful in the case of more than one failed patch, the command would need to attempt to apply all patches before failing (as opposed to failing on the first problem).

**Comment by cweagans** [comment]
This is as good of place as any. 

> Failing the build by default is great.

:+1:

> It would also be helpful to get a list of patches that couldn't be applied all together at the end of the command output. If you have very many patches, it can be easy for failures to get lost in the backscroll where they're tedious to collate and at risk of getting overlooked altogether
> For that to be useful in the case of more than one failed patch, the command would need to attempt to apply all patches before failing (as opposed to failing on the first problem).

These would apply when the plugin is configured to *not* fail when a patch can't be applied. Definitely still valid behaviors, as the plugin can be configured either way. The default will just be different in 2.0.0.

**Comment by cweagans** [comment]
Looks like this has been resolved for some time now.

If you're still looking for 2.x issues, see #93. Lots of stuff to tackle there.
