### ISSUE TITLE
php 8 support with drupal 9.3

### ISSUE THREAD

**Issue by manojiksula** [cweagans/composer-patches#406]
[TypeError]                                                                  
  Composer\Util\RemoteFilesystem::copy(): Argument #1 ($originUrl) must be of  
   type string, null given, called in /var/www/html/vendor/cweagans/composer-  
  patches/src/Patches.php on line 383

**Comment by criley** [comment]
I am also running into this issue.

**Comment by laurentiu-lese-collinson** [comment]
Make sure that patch file exists. I had the same error while creating some docker images and I realized that patches folder was not available.

**Comment by DanielSiepmann** [comment]
Thanks @laurentiu-lese-collinson. Had the same issue with another project and patch. Your suggestion solved me to fix the issue.
Indeed, a mate did only add some files excluding our folder containing the patches prior the composer install step.

**Comment by Abdo-93** [comment]
I am facing the same issue and I made sure that Patches.php file exists. I have repeated the composer install several times yet the install has not been successful.

**Comment by Abdo-93** [comment]
Hi, is there anyway I could get this file MDVA-43395_EE_2.4.3-p1_COMPOSER_v1_pt2.patch ?? Thanks

**Comment by stef-van-looveren** [comment]
> Make sure that patch file exists. I had the same error while creating some docker images and I realized that patches folder was not available.

Yes, this was the (non)issue indeed! Thanks.

**Comment by dreiren** [comment]
I had the same issue, I deleted the vendor folder then run composer update again.

**Comment by cweagans** [comment]
Sounds like this is resolved. I've made a note to add a test for this scenario in #447

**Comment by usman786cs** [comment]
I had same problem and after some R&D I found that the issue was with the patches section in composer.json file. It was manual mistake while removing some patches. It's a non issue actually.

**Comment by uqjhawk3** [comment]
I had this error happening due to a ":" being present in the initial comment about the patch. Remove the ":" and it all worked.

**Comment by jasson112** [comment]
i feel so dumb the files where not present, fixed by this commend Thanks !

> Make sure that patch file exists. I had the same error while creating some docker images and I realized that patches folder was not available.

**Comment by clairedupree** [comment]
Same issue for me, I had entered the path to the patch incorrectly in my composer.json. I typed the correct relative path and it worked as expected.

**Comment by gitressa** [comment]
I had the correct file name, everything looked correct ... but I forgot to include the path:
"`assets/patches/`1234-rendering-is.diff"
