### ISSUE TITLE
Automatically store a copy of remotely hosted patches

### ISSUE THREAD

**Issue by hestenet** [cweagans/composer-patches#410]
Related to resolving #347 

Together with: #388 

If the composer plugin could store it's own copy of remote patch urls, it could help ensure that not only are the hashes stable (via #388) but also that a repeatable artifact is kept.

Best practices should have users committing that patch artifact anyway, but this would be a strong safety belt.

**Comment by cweagans** [comment]
`main` caches downloaded patches in the composer cache by default now.
