### ISSUE TITLE
Nested composer dependency patches don't patch in composer update

### ISSUE THREAD

**Issue by adam-delaney** [cweagans/composer-patches#411]
If you define a composer dependency and within that composer dependency you define a patch for another dependency, when running composer update I'm not seeing that project removed and re-added with a patch applied. Seems like if you update the package itself it willIs this expected behavior? 
App root composer.json
```json
 "require": {
        "vendor/my-package": "^1.9",
}
```
Dependency vendor/my-package composer.json
```json
"patches": {
      "drupal/project": {
        "My patch": "https://vendor.com/path-to-my-patch.patch"
      },
}
```
Run `composer update`.

I'd expect that drupal/project would be removed and re-installed to patch.

**Comment by adam-delaney** [comment]
After more investigation it seems that re-applying patches won't occur for nested composer dependencies that don't explicitly have an update even if the composer.lock file has been updated. It seems that vendor/composer/installed.json may be used to track what may need to be patched. Removing this file before running and update resolves this issue.

**Comment by furtivesock** [comment]
Got the same issue. It seems like `patches` in the part specific to dependency in file `vendor/composer/installed.json` do not get updated at all. If you delete it or change its content to match your updated patches configuration, yes it works but it's not convenient...

Eventually I end up using [vaimo/composer-patches](https://github.com/vaimo/composer-patches/) instead which looks more versatile. If you still define your patches in `composer.json` of your dependency, you will get the same problem. You should use a separate `patches.json` file that `composer.json` will refer to (see [docs](https://github.com/vaimo/composer-patches/blob/master/docs/USAGE_BASIC.md#declaration-patchesjson)). Every time you update your patches configuration, use the command `composer patch:apply` that will update `installed.json` itself : 

```json
"target/package": {
    "extra": {
        "patches_applied": {
            "my/package::::patches/my_patch.patch": "A very interesting title, md5:..."
        }
    },
}
```

**Comment by cweagans** [comment]
`main` doesn't resolve patches from dependencies anymore.

**Comment by markfullmer** [comment]
> main doesn't resolve patches from dependencies anymore.

Can you clarify this comment? Does this mean that, in a future relase, **all** patches must be defined in the root `composer.json` file?  Can you point to the documentation about the rationale for this change? (I looked and wasn't able to find it.)

**Comment by nicksantamaria** [comment]
>main doesn't resolve patches from dependencies anymore.

Yeah this is not expected behavior. Can you elaborate if this is intended behavior or just a current gap in the featureset?

**Comment by cweagans** [comment]
I removed it intentionally at the time. Please see https://github.com/cweagans/composer-patches/discussions/478 for further info.
