### ISSUE TITLE
Installing json Extra cannot apply these patches

### ISSUE THREAD

**Issue by simantstha** [cweagans/composer-patches#413]
The image is the error and the other one is composer.json
![6fb8e51c-1e93-4c9c-978d-d40f87b712e2](https://user-images.githubusercontent.com/30699044/176519670-620af1ff-8e86-4485-a39d-86c64a1c66bd.jpg)
{
  "name": "apigee/devportal-kickstart-project",
  "description": "Composer project template for the Apigee Developer Portal Drupal distribution.",
  "type": "project",
  "license": "GPL-2.0-or-later",
  "homepage": "https://www.drupal.org/project/apigee_devportal_kickstart",
  "support": {
    "docs": "https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://packages.drupal.org/8"
    },
    {
      "type": "package",
      "package": {
        "name": "furf/jquery-ui-touch-punch",
        "version": "dev-master",
        "type": "drupal-library",
        "dist": {
          "url": "https://github.com/furf/jquery-ui-touch-punch/archive/master.zip",
          "type": "zip"
        }
      }
    }
  ],
  "require": {
    "php": "^7.4 || ^8.0",
    "apigee/apigee_devportal_kickstart": "^2",
    "composer/installers": "^1.9",
    "drupal/apigee_m10n": "^2",
    "drupal/commerce": "^2.21",
    "drupal/core-composer-scaffold": "^9",
    "drupal/core-project-message": "^9",
    "drupal/core-recommended": "^9",
    "drupal/google_analytics": "^3.1",
    "drupal/jsonapi_extras": "^3.20",
    "drupal/smtp": "^1.0",
    "furf/jquery-ui-touch-punch": "dev-master"
  },
  "require-dev": {
    "apigee/apigee-mock-client-php": "^1.1",
    "drupal/core-dev": "^9",
    "drush/drush": "^11"
  },
  "conflict": {
    "drupal/drupal": "*"
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "config": {
    "sort-packages": true,
    "process-timeout": 0,
    "allow-plugins": {
      "dealerdirect/phpcodesniffer-composer-installer": true,
      "cweagans/composer-patches": true,
      "composer/installers": true,
      "drupal/core-composer-scaffold": true,
      "drupal/core-project-message": true
    }
  },
  "extra": {
    "drupal-scaffold": {
      "locations": {
        "web-root": "web/"
      }
    },
    "installer-paths": {
      "web/core": ["type:drupal-core"],
      "web/libraries/{$name}": ["type:drupal-library"],
      "web/modules/contrib/{$name}": ["type:drupal-module"],
      "web/profiles/contrib/{$name}": ["type:drupal-profile"],
      "web/themes/contrib/{$name}": ["type:drupal-theme"],
      "drush/Commands/contrib/{$name}": ["type:drupal-drush"],
      "web/modules/custom/{$name}": ["type:drupal-custom-module"],
      "web/themes/custom/{$name}": ["type:drupal-custom-theme"]
    },
    "drupal-core-project-message": {
      "include-keys": ["homepage", "support"],
      "post-create-project-cmd-message": [
        "<bg=blue;fg=white>                                                                                 </>",
        "<bg=blue;fg=white>  Congratulations, you’ve installed the Apigee Developer Portal Drupal codebase  </>",
        "<bg=blue;fg=white>  from the apigee/devportal-kickstart-project template!                          </>",
        "<bg=blue;fg=white>                                                                                 </>",
        "",
        "<bg=yellow;fg=black>Next steps</>:",
        "  * Install the site: https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart/get-started-with-kickstart",
        "  * Read the guide: https://www.drupal.org/docs/8/modules/apigee-developer-portal-kickstart",
        "  * Report issues : https://github.com/apigee/apigee-devportal-kickstart-drupal/issues"
      ]
    },
    "enable-patching": true,
    "patches": {
      "drupal/core": {
          "Support entities that are neither content nor config entities":"https://www.drupal.org/files/issues/2020-12-02/3042467-50.patch"
      },
      "drupal/jsonapi_extras":{
          "JSON APIS EXTRAS BULK PATCH": "https://www.drupal.org/files/issues/2020-02-20/add-enable-disable-all-buttons--2896799--10.patch"
      },
      "vendor/project": {
      "Patch title1": "https://www.drupal.org/files/issues/2020-12-02/3042467-50.patch",
      "Patch title2": "https://www.drupal.org/files/issues/2018-12-17/core-undefined-index-summary_attributes-2998194-9.patch",
      "Patch title3": "https://www.drupal.org/files/issues/2021-04-23/validate-reference-constraint-3210319-3.patch",
      "Patch title4": "https://www.drupal.org/files/issues/2020-11-06/default_content-existing-entities-2698425-1-x.patch",
      "Patch title4": "https://www.drupal.org/files/issues/2020-02-20/add-enable-disable-all-buttons--2896799--10.patch"
      }
    },
    "patchLevel": {
      "drupal/core": "-p2"
    }
  },
  "scripts": {
    "quick-start": [
      "composer install",
      "php web/core/scripts/drupal quick-start apigee_devportal_kickstart"
    ]
  }
}

**Comment by cweagans** [comment]
Try running it again with '-vvv'. You may see more info. One common thing to look into if you know that these patches apply elsewhere is whether or not you have GNU Patch installed. The patch that comes with macOS is different and doesn't work with this plugin. 'brew install gpatch'

**Comment by simantstha** [comment]
Thank you for reply. i got this with -vvv and i am on windows how to install GNU patch in windows

![image](https://user-images.githubusercontent.com/30699044/176536505-cc9f3d48-7300-44cd-b6db-5d4db3cc7baf.png)

**Comment by simantstha** [comment]
but still not able to patch it

**Comment by simantstha** [comment]
![image](https://user-images.githubusercontent.com/30699044/176540157-327e11cc-3902-462f-bdbf-e7670f8e9b7d.png)

**Comment by cweagans** [comment]
So in that case, the patch doesn't apply cleanly. You'll have to fix the patch. That's a little outside the scope of what I can directly support here though.
