### ISSUE TITLE
How to ignore a patch already applied?

### ISSUE THREAD

**Issue by liquidcms** [cweagans/composer-patches#414]
The only way i have been able to process a new "ignored" patch is to edit the description text of a patch on the same module. This triggers that module to be removed and re-patched; which then takes in to account any new ignores which have been added. Not ideal, but easy enough.

But if i have no patch being done in my top level composer.json for a specific module; how do i trigger running patches (and therefore ignore a lower level patch).

I have seen a few posts here about manually forcing patching to be redone; this would work (better if it was took option of a specific module); but i don't think this has ever been solved.

**Comment by liquidcms** [comment]
I can trigger re-patching by adding a blank entry in the patches for the module i am trying to re-patch. Not ideal, but a workaround over having a proper way to trigger this.

**Comment by dpi** [comment]
`composer update --lock` !

**Comment by cweagans** [comment]
`main` has a way to re-trigger patching now: `composer patches-repatch`.
