### ISSUE TITLE
Find some help to deal with pull requests and issues

### ISSUE THREAD

**Issue by marclaporte** [cweagans/composer-patches#420]
The number of contributions is quite high here: https://github.com/cweagans/composer-patches/pulls but the number of commits is quite low: https://github.com/cweagans/composer-patches/commits/master     

I wonder if it would be a good idea to ask all previous contributors if someone would be interested in helping with the project?

**Comment by cweagans** [comment]
I'm interested in help, but it has to be done with care given the barely-present tests. Just merging the PRs isn't the right thing. Highest value work here would be to write tests.

I'm also not super interested in having _all_ the features directly in this package. I'm more inclined to support ways for other people to extend this plugin with their own.

All of that said, there's been some work behind the scenes here organizing some work + it's looking like I will have some time this month to finally do some work on this plugin again.

**Comment by danepowell** [comment]
I'm helping to merge the most critical PRs. Like Cameron said, we can't merge anything risky due to the limited test coverage, but if there's something truly breaking you can ping me and I'll try to review it.

**Comment by cweagans** [comment]
FYI: As part of my work on 2.x (#447), I intend to review issues and pull requests and either fix or close them. There will probably be a lot of things that just get closed, but we'll see.
