### ISSUE TITLE
Need more flexible patch-levels 

### ISSUE THREAD

**Issue by j2s** [cweagans/composer-patches#421]
With the recommended Drupal code structure of web/ module patches fail.
The non-git underlying command is, eg: 
`patch -p0 --no-backup-if-mismatch -d web/modules/contrib/mymodule <  /var/www/mysite/patches/mymodule-addtitle.patch`

Because -d is used patch expects the line filename in the patchfile to be without the path - otherwise fails.
In getAndApplyPatch() -p4 used to do this but now we need -p5 (or no -p).

**Comment by j2s** [comment]
There is a related point with drupal/core patches where 'Check for specified patch level for this package.' returns a value 1 less than needed. In this case '-p2' is returned when '-p3' works.  This is fixed by changing value in composer.json. (see ./vendor/cweagans/composer-patches/README.md), and adding to $patch_level

**Comment by cweagans** [comment]
I think you may be rolling your patches incorrectly if you're using `-p5`. You should be creating packages from the root of the package that the patch should apply to.

**Comment by j2s** [comment]
Thanks for the comment. I keep all patches in one upper-level directory for ease of management. I adjust paths where required for patches published with issues etc.

**Comment by cweagans** [comment]
Patches are applied relative to the dependency - even if you're storing a die full of patches, you can still create the patches relative to the root of the dependency that you're patching, which should make it so that they just work (at -p1)

**Comment by cweagans** [comment]
`main` is now very flexible wrt patch depth. You can define it in a number of ways:

* Per-patch in the patch definition
* (coming soon) Per-package in your composer.json
* Per-package in `Util::getDefaultPackagePatchDepth()` (this is global for all composer-patches users -- just trying to have good defaults for ecosystems with different workflows like Drupal)
* Global default as a fallback (which defaults to `-p1`).

**Comment by j2s** [comment]
thanks I'll check it out
