### ISSUE TITLE
Documentation about composer-patches-skip-reporting config in README.md

### ISSUE THREAD

**Issue by Sweetchuck** [cweagans/composer-patches#424]
It would be good to have a mention about the `composer-patches-skip-reporting` in the README.md

[1.x - src/Patches.php](https://github.com/cweagans/composer-patches/blob/1.x/src/Patches.php#L286) line 286.

**Comment by cweagans** [comment]
Probably not going to do this, sorry. 2.x doesn't write PATCHES.txt anymore at all. Trying to spend efforts on the 2.x release.
