### ISSUE TITLE
PHP 8.2 Creation of dynamic property is deprecated

### ISSUE THREAD

**Issue by sc0rp10** [cweagans/composer-patches#427]
Hello! Just ran composer install on my fresh PHP 8.2 installation and got an error

```
Deprecation Notice: Creation of dynamic property cweagans\Composer\Patches::$installedPatches is deprecated in /Volumes/dev/profile/new/vendor/cweagans/composer-patches/src/Patches.php:63
```

**Comment by danepowell** [comment]
Would be fixed by https://github.com/cweagans/composer-patches/pull/422

**Comment by sc0rp10** [comment]
ah, got it thanks!

**Comment by andypost** [comment]
Duplicate of https://github.com/cweagans/composer-patches/pull/409

**Comment by back-2-95** [comment]
New release is needed to get it to the Packagist
