### ISSUE TITLE
Same patch file gathered multiple times

### ISSUE THREAD

**Issue by Sweetchuck** [cweagans/composer-patches#432]
When there are two or more dependency which provide the same patch file, but with different description, then then second time the patch file cannot be applied.

Dependency 1
```json
{
  "patches": {
    "a/a": {
      "Desc 01": "https://example.com/a.patch"
    }
  }
}
```

Dependency 2
```json
{
  "patches": {
    "a/a": {
      "Desc 02": "https://example.com/a.patch"
    }
  }
}
```

Then the \cweagans\Composer\Patches::gatherPatches gives the following result:
```
{
  "a/a": {
    "Desc 01": "https://example.com/a.patch",
    "Desc 02": "https://example.com/a.patch"
  }
}
```

\cweagans\Composer\Util::arrayMergeRecursiveDistinct

**Comment by cweagans** [comment]
I'm guessing you're using 1.x (and if you're not, you should be at this exact moment). In that case, you can use https://github.com/cweagans/composer-patches#ignoring-patches to disable one of the patches.

The test you're looking at is for 2.x. Gathering patches from dependencies is no longer supported in 2.x. I might add a command to import patches from installed dependencies, but the plugin won't do it automatically anymore.

**Comment by Sweetchuck** [comment]
I am quite sure this is composer 2.x
