### ISSUE TITLE
GIT_DIR and Windows

### ISSUE THREAD

**Issue by celston** [cweagans/composer-patches#47]
I might be in the minority but my primary workstation is a Windows machine.  I believe this is causing parts of this plugin to not work.

I'm working on a Drupal 7.x project in which I'm trying to use the Twitter module.  There's a documented bug, with patch, posted here:

https://www.drupal.org/node/2584363

When I attempt to apply that patch through this plugin, I get the following:

```
https://www.drupal.org/files/issues/trying_to_get_property-2584363-5_0.patch (Property of non-object)
cd "web/sites/all/modules/contrib/twitter/" && GIT_DIR=. git apply --check "-p1" "/tmp/575f098747286.patch"
'GIT_DIR' is not recognized as an internal or external command,
operable program or batch file.
```

Best I can tell, the GIT_DIR is redundant to the cd command.  If I remove the GIT_DIR clause directly from the plugin source, the patch works.

**Comment by cweagans** [comment]
Can you please post your complete `composer.json` so that I can attempt to reproduce? I'll have to set up a Windows box soon anyway, so happy to take a look.

Note that I'm unlikely to add Windows support to 1.x unless it's a *very* simple change, but I'm happy to plan for it in 2.x, which should be out soon (I'm hoping to get to a beta this weekend, but we'll see).

**Comment by celston** [comment]
My workaround currently is to just remove the "GIT_DIR=." from the patch commands and it's working.  I don't have a perfect understanding of git and those environment variables so I'm not sure what impact just removing that piece has.

[composer.json.txt](https://github.com/cweagans/composer-patches/files/317127/composer.json.txt)

**Comment by cweagans** [comment]
Looks like that came in toward the beginning of the project. Since we're `cd`ing into the right dir, I guess `GIT_DIR` is probably not needed.

**Comment by morsok** [comment]
We are having the same issue on a windows machine, anything I can do to help ?

**Comment by cweagans** [comment]
I'd say just open a PR to remove the GIT_DIR usage.

**Comment by cweagans** [comment]
Looks like this is good now?
