### ISSUE TITLE
COMPOSER environment variable vs patches.lock

### ISSUE THREAD

**Issue by Sweetchuck** [cweagans/composer-patches#490]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my idea.

### Is your feature request related to a problem?

Currently the `./patches.lock` filename is independent from the [`COMPOSER`](https://getcomposer.org/doc/03-cli.md#composer) environment variable.

When a project has the following files, and all of them tracked with Git:

* `composer.json`
* `composer.lock`
* `composer-foo.json`
* `composer-foo.lock`
* `patches.lock`

`composer-foo.json` contains a different definitions in `#/required` and/or `#/required-dev` that means the `#/extra/patches` definition also has to be different,
but the same output filename is used for the lock file.

```bash
unset COMPOSER
composer update
composer patches-relock
composer patches-repatch

export COMPOSER='composer-foo.json'
composer update
composer patches-relock
composer patches-repatch
```

At this point not obvious which `composer*.lock` the `patches.lock` file belongs to.

If the `/composer-*.json` and `/composer-*.lock` files were ignored by VCS it would still caused a problem by accidentally commit the changed `./patches.lock` into the VCS.

### Describe your proposed solution(s)

The patches lock file name should depend on the value of the `${COMPOSER:-composer.json}` environment variable. Use it as a prefix or a suffix or make it configurable in `#/extra/composer-patches`.

```php
$composer_filename = \Composer\Factory::getComposerFile();
$base = pathinfo($composer_filename, \PATHINFO_FILENAME);

$patches_lock_filename = "$base.patches-lock.json";
```

Related discussions:

* [Feedback for v2 - patches.lock filename](https://github.com/cweagans/composer-patches/discussions/485)

### Expected result is

* `composer.json`
* `composer.lock`
* `composer.patches-lock.json`
* `composer-foo.json`
* `composer-foo.lock`
* `composer-foo.patches-lock.json`

**Comment by cweagans** [comment]
Can you help me understand why it would be desirable to have multiple `composer.json` files like this? That seems unnecessary.

**Comment by Sweetchuck** [comment]
I can explain it, but that is not the point.
The point is that it is a native Composer feature, and I think the cweagans/composer-patches plugin should work with it well.

The main purpose of the `composer.lock` file is to make the exactly the same code base reproducible.
When the cweagans/composer-patches plugin is used in a project the `patches.lock` is also mandatory in order to reproduce the same code base.
So, the `composer.lock` and `patches.lock` always has to be attached together.

One project can have multiple *.json file which can function as project definition thanks to the `COMPOSER` environment variable. That means a project has to be able store multiple patches lock file as well.

---

Uses cases for multiple composer.json

To try out different forks of the same project.
Maybe this case no need to change the `#required` part, but `#repositories` needs to be changed.
```json
{
   "repositories": {
       "a/b": {
           "type": "git",
           "url": "https://github.com/fork-a/b"
       }
   }
}
```

---

I want to easily switch between package versions, but the `composer update --prefer-lowest` does not provide enough flexibility. 
```json
{
    "required": {
        "a/b": "^1.0 || ^2.0 || ^3.0"
    }
}
```


For more examples check the documentation of these projects:

* [composer-suite-handler library](https://github.com/Sweetchuck/composer-suite-handler)
* [composer-suite Composer plugin](https://github.com/Sweetchuck/composer-suite)
* [composer-suite CLI](https://github.com/Sweetchuck/composer-suite-cli)

**Comment by cweagans** [comment]
I don't feel a strong need to support every possible configuration/feature of Composer, but I'll give this some thought. While I understand the examples you gave, I'm not sure why they are necessary or practical in a typical Composer project. In fact, this is the first time that I've _ever_ heard of somebody doing something like this.

**Comment by Sweetchuck** [comment]
I tried to find it (I couldn't), but one of the Drupal scaffolding or Drupal project template also uses the `COMPOSER` environment variable to define an alternative *.json file. I seen it 2-3 weeks ago.

**Comment by Sweetchuck** [comment]
Other example:

* I want to fix a [drupal/drupal](https://git.drupalcode.org/project/drupal) core bug.
* There is no developer helper tooling.
* `drush/drush` would be handy, along with `drupal/devel` or `drupal/module_filter`, so on ...
* I don't want to add them to the `composer.json`, because I might accidentally include it into the patch file or into the GitLab MR.
* I create an alternative composer-my.json
* `export COMPOSER='composer-my.json'`
* I add some new rules into the `./.git/info/exclude`
* Then I am good to go.

Maybe the scenario above doesn't include patches, but more developer use this feature than you think.
