### ISSUE TITLE
Redirect loop in documentation pages - Github says to go to docs.cweagans.net/composer-patches - that page says the documentation is in README.md on Github...

### ISSUE THREAD

**Issue by alexharriesredactive** [cweagans/composer-patches#498]
### Verification

- [X] I have searched existing issues _and_ discussions for my problem.

### Which file do you have feedback about? (leave blank if not applicable)

https://docs.cweagans.net/composer-patches/

### Feedback

Hello folks,

For context, I'm trying to work around the problem where patches which don't apply now cause composer to stop rather than failing and moving on - this has broken my builds, but that's not the issue I'm reporting here :)

I looked on the module's Github homepage to see if I could specify a "continue on error" flag in my patches config in composer.json - here: https://github.com/cweagans/composer-patches

That page says: "Documentation: https://docs.cweagans.net/composer-patches"

So I follow that link, and see this:

"Nothing here applies to 1.x

All documentation for the current, production-ready version of the plugin is in the README.md in the project repository."

... but the README.md pointed me to this page.

Help, please! Where can I find full usage destructions for this essential plugin, please?

Thank you all ever so much in advance :)

/Alex

**Comment by cweagans** [comment]
Use the readme in the 1.x branch.

**Comment by alexharriesredactive** [comment]
Ok, perhaps we could add a link to the 1.x readme on the documentation homepage - e.g.:

```
This site provides documentation for the 2.x branch; if you're looking for documentation for 1.x, please visit this page:

https://github.com/cweagans/composer-patches/tree/1.x
```

... maybe? :)
