### ISSUE TITLE
Add option to allow composer to continue if patches don't apply

### ISSUE THREAD

**Issue by alexharriesredactive** [cweagans/composer-patches#499]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my idea.

### Is your feature request related to a problem?

Hello all,

After updating to MacOS Ventura, patch is no longer working so I've updated composer-patches to the head of `main` to use Git.

Before, when patches didn't apply - e.g. their fix has already been committed to the module being patched - composer would complain about it and then continue.

Now when a patch doesn't apply, composer fails noisily and I have lost two days' development time trying to fix this issue.

If there isn't already, please could we have a way to allow composer to continue if patches don't apply?

Many thanks in advance,

Alex

### Describe your proposed solution(s)

If there isn't already, please could we have a way to allow composer to continue if patches don't apply?

**Comment by cweagans** [comment]
You probably just need to 'brew install gpatch'. You should definitely not be using 'main' for anything important rn.

Probably will not be adding this switch - it'a not valid to specify that a patch should be applied and then end up not applying the patch.

**Comment by cweagans** [comment]
Let me know if you need more info here. Closing for now.

**Comment by alexharriesredactive** [comment]
All good - thank you :)
