### ISSUE TITLE
New documentation website is missing the ignore-patches

### ISSUE THREAD

**Issue by nvaken** [cweagans/composer-patches#500]
### Verification

- [X] I have searched existing issues _and_ discussions for my problem.

### Feedback

I was searching for the documentation about ignoring patches but was presented with the new and great looking new docs: https://docs.cweagans.net/composer-patches/

I searched for the ignoring patches documentation, but this seems to be missing? I could find it eventually by looking into the history of `README.md`:

https://github.com/cweagans/composer-patches/blob/267a32b8105464686cdade12c34d32c54c77baa8/README.md#ignoring-patches

**Comment by cweagans** [comment]
The docs site doesn't apply to 1.x per the note and the upcoming 2.x version doesn't currently have this functionality.
