### ISSUE TITLE
[Bug or new feature] Add support for local patch files and external patch file in dependencies

### ISSUE THREAD

**Issue by michaelw85** [cweagans/composer-patches#505]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my idea.

### Is your feature request related to a problem?

Yes, a patch will not be applied from one of the packages I'm installing (my own package).

Setup:
```
Root project
|_ dep 1 (required by root, containing patch)
|_ dep 2 (required by dep 1, should be patched by dep 1) 
```
**issue 1**
When dependency 1 uses an [external patch](https://github.com/cweagans/composer-patches/blob/1.x/README.md#using-an-external-patch-file) file the patches are not detected and thus never applied.
[gatherPatches](https://github.com/cweagans/composer-patches/blob/1.x/src/Patches.php#L192) only searches for the `patches` key.

**issue 2**
When switching to the `patches` configuration the patch will be found but when it's not an url but a local path e.g. `patches/my-patch.patch` an error occurs because paths are only [resolved](https://github.com/cweagans/composer-patches/blob/1.x/src/Patches.php#L378) relative to the root directory.
My current workaround is adding a symlink in my root project.

### Describe your proposed solution(s)

Add support for the `patches-file` configuration for dependencies and use dependency/package root that defines a patch to resolve relative paths for patches.

### Describe alternatives

Add documentation that an external patch file only works for root projects (although this does not make a lot of sense to me).
To resolve the relative path issue an alternative could be to copy all gathered patches into a temp dir.

**Comment by michaelw85** [comment]
Automatically closing doesn't seem right to me. It would be nice to see a response acknowledging or declining the ticket

**Comment by gitressa** [comment]
I agree, perhaps the staleness threshold has been set to low, at one month? It seems very fast ...

**Comment by cweagans** [comment]
Hi all, apologies for the quick close and radio silence. I was trying out the stale bot and the thresholds were indeed set too low.

At this point, the 2.x version isn't going to support importing patches/patch defs from dependencies. It's a pretty complicated problem and an endless source of support requests and bugs. I do not have the time or energy to devote to it and I just can't commit to maintaining that particular functionality right now.

If you feel very strongly about having this kind of workflow (and being able to define patches via imported dependencies in general), I'd be glad to help you start up a plugin that extends this one and get you pointed in the right direction and give you an early heads up on where you might run into complications.

**Comment by michaelw85** [comment]
@cweagans thanks for the reply. 
It would be nice to at least add a little bit of documentation on this limitation and a work-around.
I could do that if you want.

**Comment by cweagans** [comment]
I'm never going to turn down help with docs! 😄

Couple of potentially helpful tidbits:
* there is some info about how to write docs in this project here: https://docs.cweagans.net/meta/
* this is related to the removal of dependency patch resolution in 2.x, which was being discussed earlier this year. I'm about to publish a blog post (in the next few days) about that decision which may have some helpful info.
* this functionality can also be added by extending Composer Patches (you can write a plugin for the plugin!) if you really need it.

**Comment by michaelw85** [comment]
@cweagans I've created a PR to extend the documentation based on the info I reported here. I think the description is quite extensive, feel free to edit/reduce the text if you feel it's too much.

**Comment by cweagans** [comment]
Thanks! I'll take a look ASAP.

**Comment by rajeshreeputra** [comment]
@cweagans Not sure but I started something [here](https://github.com/rajeshreeputra/composer-patches-plugin) to apply patches from local and from url(lile from drupal.org patch file url).
Looking for help.
