### ISSUE TITLE
How to apply patches from URL to a private GitHub repo?

### ISSUE THREAD

**Issue by Moongazer** [cweagans/composer-patches#507]
### Verification

- [X] I have searched existing issues _and_ discussions for my problem.

### Feedback

First of all, thank you for this amzing package, it works perfect (in the most common cases). But currently we having big troubles and can't figure out if its a bug or if we missing some configuration.

We want to apply patches from an URL to our private repo on GitHub, so we setup the following `patches.json`:
```
{
  "patches": {
    "mautic/core-lib": {
      "Patches something in the Mautic core": "https://patch-diff.githubusercontent.com/raw/our-company/our-private-repo/pull/6.patch?token=AAM[...]E3G"
    }
  }
}
```
The above URL is given by the browser, if we navigate to `https://github.com/our-company/our-private-repo/pull/6.patch`. But it doesn't matter which URL we're using, composer always logs the following error message:
```
﻿﻿Package operations: 1 install, 0 updates, 0 removals
Gathering patches from patch file.
Gathering patches for dependencies. This might take a minute.
  - Installing mautic/core-lib (4.4.7): Extracting archive
  - Applying patches for mautic/core-lib
    https://patch-diff.githubusercontent.com/raw/our-company/our-private-repo/pull/6.patch?token=AAM[...]E3G (Patches something in the Mautic core)
   Could not apply patch! Skipping. The error was: The "https://github.com/our-company/our-private-repo/pull/6.patch" file could not be downloaded (HTTP/1.1 404 Not Found)
```
The 404 Not Found happens also if we try to open the URL in a private-tab of the browser, so probably it has something to do with missing credentials.

We're running composer inside of a DDEV container, so we made sure composer and git having access to their host-credentials by symlinking `~/.ssh/`, `~/.gitconfig/` and `~/.composer/auth.json` to the global `~/.ddev/homeadditions/` folder. 

If we manually run `git clone git@github.com:our-company/our-private-repo.git` from inside the container, the repository is cloned successfully (means, that git inside DDEV finds the host credentials to authenticate and clone). The same should be true for composer (but not sure how to test this).

What can be the issue here? How does `composer-patches` fetches the patch-files from URLs?
If we're using `curl` from inside DDEV with the token, it works as well:
```
// get patch file via API
curl -H 'Authorization: Bearer ghp_oqS[...]v8Lj' -H 'Accept: application/vnd.github.patch' https://api.github.com/our-company/our-private-repo/pulls/6
```

Any help highly appreciated 🙏🏼

**Comment by cweagans** [comment]
This isn't supported right now. Generally, I would discourage people from using the /pull/#.patch URLs anyway (especially for public repos), as it becomes significantly harder to have reproducible builds if all of the build inputs aren't static :)

In any case, the most straightforward solution here would be to download the patch, save it somewhere in your project, and specify a relative path to the patch in your `composer.json`.

**Comment by Moongazer** [comment]
It was a requirement of the customer, I personally see it in the same way as you do and would prefer a local patch commited into the project repository. Thank you a lot for the fast response and the straight answer 👍🏼
