### ISSUE TITLE
Removing package for re-install and re-patch does not trigger if patches definition is empty (1.7.3)

### ISSUE THREAD

**Issue by GamesmenJordan** [cweagans/composer-patches#525]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my problem.
- [X] My problem is _not_ addressed in the [troubleshooting guide](https://docs.cweagans.net/composer-patches/troubleshooting/guide).

### What were you trying to do (and why)?

This is using composer-patches 1.7.3

Removing and re-installing patched modules does not behave correctly when no patches are provided in the `composer.json` or external patches JSON file.

For example, assuming the following starting state, the below patches have been applied:

```json
{
    "patches": {
        "acme/module-1": {
            "mock-patch-1": "mock-patch-1.patch"
        },
        "acme/module-2": {
            "mock-patch-2": "mock-patch-2.patch"
        }
    }
}
```

If the user wants to remove both `mock-patch-1` and `mock-patch-2`, and do so by modifying the JSON to the following:
```json
{
    "patches": {}
}
```

Then running `composer install`, the previously applied patches would not be removed and the output would be as follows:
```
Gathering patches from patch file.
No patches supplied.
```

This differs from expected behavior, for example if we were instead removing only `mock-patch-2` the following JSON could be provided:

```json
{
    "patches": {
        "acme/module-1": {
            "mock-patch-1": "mock-patch-1.patch"
        }
    }
}
```

Running `composer install` now would re-install `acme/module-2` and remove `mock-patch-2`, and the output would be as follows:
```
Gathering patches from patch file.
Removing package acme/module-2 so that it can be re-installed and re-patched.
  - Removing acme/module-2 (1.0.0)
```

The expectation is this same process would be applied to an empty `patches` definition too. I believe, but haven't verified that this did used to be the case.

I have worked around this issue temporarily by providing fake empty patch in my patches JSON that targets a non-existent module which appears to have the desired behavior.

### What happened? What did you expect to happen?

Expected `composer install` to re-install previously patched modules, restoring them to the un-patched state.

`composer install` returned "no patches supplied" but did not re-install modules that were previously patched. Previously applied patches remained in place.

**Comment by cweagans** [comment]
Thanks for your contribution! I am no longer maintaining the 1.x branch. Because of how widely used it is and how little test coverage of that branch there is, I won't be making any more changes to the 1.x branch. Please upgrade to 2.x.
