### ISSUE TITLE
Link in the README 404s: Documentation: https://docs.cweagans.net/composer-patches

### ISSUE THREAD

**Issue by thejimbirch** [cweagans/composer-patches#542]
### Verification

- [X] I have searched existing issues _and_ discussions for my problem.

### Which file do you have feedback about? (leave blank if not applicable)

README.md

### Feedback

Dreamhost page not found error.
https://docs.cweagans.net/composer-patches

**Comment by cweagans** [comment]
Thanks! Resolved.

**Comment by thejimbirch** [comment]
Thank you!
