### ISSUE TITLE
Add a `patches-import` subcommand as a way to support discovering patches from dependencies

### ISSUE THREAD

**Issue by cweagans** [cweagans/composer-patches#546]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my idea.

### Is your feature request related to a problem?

Right now, including patches from dependencies isn't a supported workflow. Many users rely on this functionality.

### Describe your proposed solution(s)

Let's add a subcommand to this project that looks through all `composer.json` files in the project and imports all of the patch definitions into a root-level `patches.json`. We'll need some way to differentiate between user-added patches and patches defined by a dependency. If the command is re-run, any updated patches from dependencies should be re-discovered. It might make sense to make this a separate patches file.

This removes a _ton_ of the complexity around discovering and applying patches from dependencies and is a workflow that I might be willing to support in the long term.

The workflow would be roughly as follows:

1. `composer install` - get all of the dependencies on disk
2. `composer patches-import` - crawl through all of the `composer.json` files, grab patch defs, and add them to a patches file
3. `composer patches-relock` - re-generate the patches lock file
4. `composer patches-repatch` - remove and re-patch installed dependencies

To composer patches, this would just look like you defined the patches by hand. The only real difference is that there would be a helper command that you can run separately from `composer install`.

**Comment by mxr576** [comment]
1. How can we opt-out from discovering/applying patches from dependency X with this feature?

How can we exclude all patches from dependency X or just some of them? I assume the generated "patch collection file" could be modified manually but on the next run `composer patches-import` would automatically add them back.

2. How can we validate if existing dependencies did not introduce a new or a modified patch after a dependency update?

Maybe a `composer validate` extension could also come handy for this purpose? 

Maybe it is also worth collecting user-story-like scenario descriptions that would detail how these commands could/should be leveraged when:
* new dependencies are installed (incl. transitive dependencies)
* a dependency are updated (incl. transitive ones)
* a dependency is removed

**Comment by cweagans** [comment]
> 1. How can we opt-out from discovering/applying patches from dependency X with this feature?

An additional configuration directive could be added to ignore patches from specific dependencies. I don't think I'd be interested in ignoring specific _patches_ from specific dependencies (the workaround being to ignore the entire dependency and manage the patches in the root project manually).

> 2. How can we validate if existing dependencies did not introduce a new or a modified patch after a dependency update?

Since the `patches-import` subcommand would be modifying a real file at the root of your project, this change would a) be visible through `git status` or similar and b) only take place after taking an explicit action in your project.

> Maybe it is also worth collecting user-story-like scenario descriptions that would detail how these commands could/should be leveraged when:

I specifically _do not_ want this to be an automatic thing by default. If people want to add this to their [`post-update-cmd`](https://getcomposer.org/doc/articles/scripts.md#command-events) scrips, they can do that. I do not want to make any assumptions about how/when patches are imported from dependencies.

That said, I can add some stuff to the [Recommended Workflows](https://docs.cweagans.net/composer-patches/usage/recommended-workflows/) docs for users that need something a little more prescriptive.

**Comment by cweagans** [comment]
Actually. Ignore this entire issue.

#547
