### ISSUE TITLE
Add info about composer -v for extended verbosity

### ISSUE THREAD

**Issue by tantebootsy** [cweagans/composer-patches#557]
### Verification

- [X] I have searched existing issues _and_ discussions for my problem.

### Which file do you have feedback about? (leave blank if not applicable)

docs/troubleshooting/guide.md

### Feedback

As you make use of composer's IOInterface, it would be nice to let newbies like me know, that troubleshooting can also be started via e.g. `composer -v patches-repatch`. The verbose-flag makes looking into failures much more easy in some cases.

**Comment by cweagans** [comment]
Thanks! This will go live on the docs site on Monday morning (a little slow, but that's just how the docs site is set up right now 🤷🏻‍♂️ )

**Comment by tantebootsy** [comment]
thank you, cameron
