### ISSUE TITLE
Support multiple patches-files or patches-file with root patches together

### ISSUE THREAD

**Issue by sascha-meissner** [cweagans/composer-patches#581]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my idea.

### Is your feature request related to a problem?

Currently you can either choose to have one patches-file containing the patches OR having the patches in the root composer json,

if you try to use: 

```
        "patches": {
            "some/package": {
                "do-this-and-that": "path/to/my.patch"
            }
        },
        "patches-file": "composer.patches.json"
```
it will ignore the patches-file no matter the order.

BUT it would be a very nice feature to have multiple patch-sources, in example to have a centralized patchmanagement and still have the possibility to have exotic project-specific patches only in the project and not in the central.

### Describe your proposed solution(s)

Either support multiple patchfiles, in example: 

`"patches-file": ["upstream.patches.json", "custom.patches.json"]`

which would be the desired solution 

### Describe alternatives

for our use case two-dimensional approach would also work in example when having

```
        "patches": {
            "some/package": {
                "do-this-and-that": "path/to/my.patch"
            }
        },
        "patches-file": "composer.patches.json"
```

that both, the patches in root composer json will be applied as well as the patches in patches file

**Comment by sascha-meissner** [comment]
I´m sorry i didnt find https://github.com/cweagans/composer-patches/issues/139 in the first place, this issue here should be a duplicate

**Comment by cweagans** [comment]
2.x does what you want :)
