### ISSUE TITLE
Support multiple "patches-file"

### ISSUE THREAD

**Issue by mendrupal** [cweagans/composer-patches#599]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my idea.

### Is your feature request related to a problem?

There are cases where having more than one patches file will be really useful. For example when using Drupal Profiles and having child repositories that depend on other profile repositories, there is no simple way to apply patches for the child if the parent is a protected or immutable repository.

There is an issue closed #581 in the issue queue mentioning this as part of the problem and suggested solution but that specific part was not addressed.

### Describe your proposed solution(s)

The proposed solution allows for having multiple patches files defined.

`    "extra": {
        "composer-patches": {
            "patches-file": [
              "patches.json",
              "patches_two.json"
            ]
        },`

Attaching a patch before creating a PR for the community to review and improve if necessary.
[multiple-patches-files.patch](https://github.com/user-attachments/files/17639851/multiple-patches-files.patch)

**Comment by cweagans** [comment]
I'm not going to support this in the core plugin. If you want additional patches files, you can write a composer plugin that provides a [Resolver](https://docs.cweagans.net/composer-patches/api/capabilities/), which can discover patches from wherever you want.
