### ISSUE TITLE
Apply patches to scaffolding files?

### ISSUE THREAD

**Issue by eelkeblok** [cweagans/composer-patches#65]
I have a patch I want to apply to sites/default/default.settings.php (D8 project). Is there any way to currently do that? 

Applying the patch against drupal/core won't work, because it is only the contents of the core directory. It is actually the drupal-project/drupal-scaffolding package that is responsible for updating the scaffolding files (basically anything from the standard Drupal distribution outside the core directory). (Patching against it also is not what's needed, because it actively downloads the scaffolding files; the package itself is just the code to figure out what to download).

**Comment by cweagans** [comment]
Conceptually, what you're asking for is a way to patch the root package, but I'm not sure why you'd need to do that. You have control over the root package, so why not just change the file?

What I'd recommend in this case is the following:

* Add `"omit-defaults": false` to your `drupal-scaffold` configuration
* Add the list of default includes to your `drupal-scaffold` configuration sans the `default.settings.php` line. This way, Drupal Scaffold won't update it when core changes and you can just commit your changes to the project repo. Of course, that means that you'll have to manually resolve any differences between updated core versions and what you have in your version, but that's kind of the norm with a patch workflow.

An alternative is that you could write a script that fires after the Drupal Scaffold script that can detect if `default.settings.php` was updated, and if so, append `require_once __DIR__ . '/my_settings.default.php`, and then do all of your modifications in `my_settings.default.php` where your changes won't get overwritten in the first place.

**Comment by eelkeblok** [comment]
Thanks for your suggestions. The downside of the "maintain your own version" is that you'd have to check for changes in the file every time you update Drupal; the advantage of working with a patch is that in most cases, the patch will just apply the required changes, while upstream changes are incorporated automatically as well (actually, this argument could be applied to anything you might like to patch; just fork the module and maintain your own version...). 

Your second suggestion (as far as running a script is concerned, I would still like to apply a patch that way) is actually my "plan B", so I guess I'll be trying that.
