### ISSUE TITLE
Patches on external file aren't installed

### ISSUE THREAD

**Issue by ralkeon** [cweagans/composer-patches#67]
Hi, I'm trying to use an external file to install patches, but they are only installed if I set them into the composer.json.

My extra section:
![image](https://cloud.githubusercontent.com/assets/10153072/17927608/bd2176e4-69f6-11e6-96f3-cc986a414b25.png)

My external file:
![image](https://cloud.githubusercontent.com/assets/10153072/17927576/9e92e53c-69f6-11e6-9348-71e13b76ea18.png)

composer.json and composer.patches.json are in the same folder. If I move the code in the composer.patches.json in the extra section it works perfectly. I don't know what I'm doing wrong...
Sorry for my bad english and thanks for any help.

**Comment by bka** [comment]
Had this issue today. Had a look into the code and discovered a hidding option you need to set in order to make external patch files work. 

Try setting `enable-patching` in your extra session like this:

    "extra": {
        ...
        "enable-patching": true,
        ...
    }

**Comment by ralkeon** [comment]
Thank you so much @bka ! It works perfectly!!!
