### ISSUE TITLE
Patches added to dependency after initial install not applied to root package on update

### ISSUE THREAD

**Issue by acbramley** [cweagans/composer-patches#71]
Steps to reproduce:
- Add a dependency to your root package which contains patches
- Add a new patch to that dependency
- Run composer update my/dependency in your root package

Expected:
New patch is applied

Actual:
New patch is not applied

**Comment by mike-potter** [comment]
This might be related to https://github.com/cweagans/composer-patches/issues/66.  It might think the cached dependency without the patch is still valid.

**Comment by sylus** [comment]
Think I have been running into this as well ^_^ Whenever my initial composer install worked perfectly, but when using `composer require vendor/project` on a new project which itself had patches, composer didn't seem to detect them.

**Comment by acbramley** [comment]
Fixed in https://github.com/cweagans/composer-patches/commit/d9d31d812d483cefbae89238e52ba2a25d8a1cbb
