### ISSUE TITLE
Patches plugin fails some urls

### ISSUE THREAD

**Issue by webflo** [cweagans/composer-patches#73]
I tried to download a certain commit directly from http://cgit.drupalcode.org/. The patches plugin skips the URL with "Could not apply patch! Skipping."

The code in Patches::getAndApplyPatch can't handle the url. I used http://cgit.drupalcode.org/drupal/patch/?id=7393e427390570e770579fe9119e0d577b753578 for example

**Comment by cweagans** [comment]
The plugin uses the Composer file transfer stuff, which blocks http by default now. Since cgit isn't available via https currently, see https://getcomposer.org/doc/06-config.md#secure-http
