### ISSUE TITLE
Patch up to a specific version

### ISSUE THREAD

**Issue by hanoii** [cweagans/composer-patches#75]
Patches gets outdated, is it possible to restrict one patch to one version and make sure it doesn't apply to newer ones?

README says it's not required, but couldn't find if it's still be possible.

**Comment by cweagans** [comment]
This is not possible right now, but I'm not sure why it's necessary at all.

If I run `composer install` and get `my/package` v1.0.0, that version is written to the lock file. Anyone else that does a `composer install` with that lock file gets that version of the module. If I run `composer update my/package` and get 1.1.0 and my patch no longer applies, at that point, I'm going to have to re-patch the module (whether that's by re-rolling the patch or not having the patch anymore or whatever). When you update your module, just update your patch.

Am I missing something?

**Comment by hanoii** [comment]
No, you are absolutely right! Thanks!

**Comment by andrewbelcher** [comment]
I've got a specific case where I can't think of an alternative. I've a module that needs a patch to core. All is good for 8.3.x. That patch has been committed to 8.4.x, which is not yet released, but I want to be able to run my tests against it so I can be prepared if anything changes or breaks.

**Comment by mougrim** [comment]
Tere is fork vaimo/composer-patches, which allow patch up to a specific version.
