### ISSUE TITLE
Dependencies + Patches + Composer Require in a sub composer.json file

### ISSUE THREAD

**Issue by sylus** [cweagans/composer-patches#79]
Hi there, first of I wanted to say thanks for the awesome repo!

Given the following composer.json file:

https://github.com/drupalwxt/drupal_wxt/blob/master/composer.json

When I run composer install everything gets installed correctly and in addition modules are correctly patched. In this composer.json file you will notice the line: `"drupalwxt/wxt": "dev-8.x-2.x"` this in turns calls this composer.json file:

https://github.com/drupalwxt/wxt/blob/8.x-2.x/composer.json

Given the above works I was curious why doing the following doesn't work and composer fails to see any patches.

In the same directory after everything is installed / scaffolded I then run:

``` sh
composer require drupalwxt/wxt_search:dev-8.x-1.x
```

Which does download all of the correct modules but there is no patch applied. 

https://github.com/drupalwxt/wxt_search/blob/8.x-1.x/composer.json#L40

I was wondering if there was something I was perhaps missing or misunderstanding :)

**Comment by cweagans** [comment]
First off, sorry for the long delay in getting back to you. I was on vacation until this past Saturday and I'm still playing catch up.

At first glance, everything that you have there *should* work. Frankly, it seems a little overcomplicated to me, but I understand why you're doing it this way and the plugin *should* handle it. Unfortunately, the plugin has somewhat gotten out of control lately and I'm guessing that this workflow hasn't been tested so there's probably some silly bug somewhere preventing it.

If you'd like to debug the 1.x version of the plugin to figure this out, the help would be much appreciated. Most of my efforts at this point are being spend on the 2.x branch, so tagging to remind myself to come back to this later and write an integration test for it. If I have time, I'll try to dive into this a bit, but it's extremely unlikely for the next couple of weeks.

**Comment by sylus** [comment]
No worries at all, completely understood.

I also wanted to say thank you very much for this great tool as for the most part it works perfectly!

I will try to debug my issue further in the short term and report back. ^_^

**Comment by cweagans** [comment]
`main` no longer resolves patches from dependencies, so this won't be possible at the moment.
