### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by danepowell** [cweagans/composer-patches#84]
The last stable release was over 7 months ago, and there have been some pretty significant commits since then. There also haven't been any commits in over a month now, which indicates to me that the current build is probably relatively stable.

It would be nice to get a new tagged release, so that folks don't have to kill kittens by relying on an unpinned dev branch or commit ref of composer-patches.

**Comment by m4olivei** [comment]
Totally agree, in particular this one would be nice for me today https://github.com/cweagans/composer-patches/pull/44.

**Comment by danepowell** [comment]
Thanks @cweagans !!
