### ISSUE TITLE
Patching a packages composer.json file before it installs dependencies

### ISSUE THREAD

**Issue by MichaelMallett** [cweagans/composer-patches#86]
I'm trying to install a couple of drupal modules, one of which I suspect has never been tested for installation with composer as it simply can't work in it's current state.

[s3fs](https://www.drupal.org/project/s3fs) and [s3fs_cors](https://www.drupal.org/project/s3fs_cors)

Both of these require the aws s3 sdk, and as is implied, s3fs_cors depends on s3fs. 

Anyway, the requirements in each is as follows:
s3fs:
`"require": {
        "aws/aws-sdk-php": "^3.18"
    },`

s3fs_cors
`"require": {
        "aws/aws-sdk-php": "~3.3.8"
    },`

Of course this leads to a long error list from composer like this:
- Can only install one of: aws/aws-sdk-php[3.3.8, 3.20.1].

Where those two requirements are conflicting

My proposal to get round this would be to patch the composer.json of s3fs to allow a newer version of the aws adk, so have a patch in place to do this which simply changes the requirement to ~3.18

The problem there of course is that the patch is not applied until the end (and I have tested it in isolation, the patch is applied), and it makes no difference.

How can I tell composer to run the patch first and then install the dependencies? Otherwise the only way to get this working would be to fork the package, but that would be last resort.

**Comment by cweagans** [comment]
This is not how composer works. You can't just patch the local copy of the composer.json to change the requirement. The composer.json in a repository is read by Packagist (or whatever system is serving the composer repo), which generates the package metadata that Composer retrieves to know where to download the package from. i.e. Composer has read this information before it ever gets to your filesystem.

The proper path forward here is to get the s3fs_cors maintainer to fix their version constraint. That's honestly the only thing that will fix this.

**Comment by MichaelMallett** [comment]
Thanks for the response I suspected that may be the case!
