### ISSUE TITLE
Preferred-install source necessary?

### ISSUE THREAD

**Issue by simPod** [cweagans/composer-patches#91]
I removed preferred-install source and it seems to work. Is there any catch? Is this setting necessary for this to work and somehow I don't see it?

Thanks

**Comment by cweagans** [comment]
Dist should definitely work too.

**Comment by mathiasselleslach** [comment]
Whoops, im just finding this now.
This is an important thing imho, as this (potentially) blow up the vendor folder in size...

```
  "config": {
    "preferred-install": "source"
  },
```

will cause all dependencies to include the `.git` folder...

@cweagans , if it is not strictly needed, i would suggest removing it from the readme.
If it is needed, then please clarify.

In a project that i have tested source gave me a vendor folder size of 900Mb (!!), dist gave me 54Mb.
