### ISSUE TITLE
Force update on packages with new or changed patches

### ISSUE THREAD

**Issue by yanniboi** [cweagans/composer-patches#98]
Firstly, thank you! This project is so incredibly useful so a shout out to everyone working on it!

Now from my limited understanding of reading through the code, it appears to me, patches are checked and gathered whenever composer executes either an install or update event. However there are some scenarios that I can think of when a change in patches should trigger an update even if the version/code hasn't changed.

Eg.

I have a Drupal module, **contacts**. It has a dependency on another module, **ctools**. It also patches _ctools_.
When I first install my module, it gathers the patches and installs/updates both _contacts_ and _ctools_ and patches everything correctly.
However if I add more _ctools_ patches to contacts and update my composer project. It will gather the _ctools_ patches, but since _ctools_ isn't being updated, it will not apply the patches.

So I think to some extent we want to be able to force composer to rebuild packages that composer-patches believes need to be re-patched. I am planning to look into how to do this, but could do with someone confirming that this is a valid issue (and not just me missing something) and maybe a couple of pointers as I am pretty new still to composer.

**Comment by yanniboi** [comment]
I've had a look at how this might be solved.

Ideally we would want to add another script for the InstallerEvents::POST_DEPENDENCIES_SOLVING event. At this point, composer has just decided which packages need updating/installing/removing in the operations array and is about to log "Nothing to install or update" if the array is empty.

If it were possible to add to operations through the InstallerEvent we could tell composer to rebuild packages here, however there doesn't seem to be any way of adding to the operations array.

**Comment by cweagans** [comment]
Thanks for doing the research on this! I'm hoping to implement this in the 2.x branch, which is a complete rewrite of the plugin with a focus on making it not so fragile (i.e. by testing the plugin obsessively). I just need to find a few more hours to spend on the plugin and it should be ready for an alpha release.

**Comment by nalipaz** [comment]
Is there any further development on this?

**Comment by hifi** [comment]
This is inconvenient when updating a patch and you need to delete the package from `vendor/` to get the patch re-applied. :+1: for getting this fixed.

**Comment by neilh-cogapp** [comment]
One workaround if you have modified an existing patch is to rename the key for the patch in the `patches.json`.

**Comment by rickkowal** [comment]
@neilh-cogapp, that did it for me.  Thanks!

**Comment by cweagans** [comment]
`main` has this now. `composer patches-relock` to discover and lock all patches, then `composer patches-repatch` to remove, re-install, and re-patch all patched dependencies.
