### ISSUE TITLE
Very noisy 

### ISSUE THREAD

**Issue by REBELinBLUE** [cweagans/composer-patches#99]
Firstly, thanks for this package it is awesome, exactly what I have been looking for

Is there a way to silence the `Patches already gathered. Skipping` which is output between every single package?

**Comment by wimleers** [comment]
+100!

**Comment by wimleers** [comment]
Apparently #90 already improved this. But the last release is https://github.com/cweagans/composer-patches/releases/tag/1.6.0, which doesn't yet include commit 2b19d64fe4e13874e2f665bcce32b5d163dc7c7e.

**Comment by wimleers** [comment]
I think this can be closed as a duplicate, at least once a new release is tagged.

**Comment by REBELinBLUE** [comment]
Ah thanks, I did search before posting but I didn't find that >_<
